### ISSUE TITLE
Error starting Oxidized

### ISSUE THREAD

**Issue by loopodoopo** [ytti/oxidized#1013]
Since a couple of days, my Oxidized installation started failing. When I try to start the Oxidized service I get the following error: 

```
[oxidized@oxidized oxidized]$ /usr/local/bin/oxidized
undefined method `dig' for ["status", "error"]:Array
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load': undefined method `dig' for ["status", "error"]:Array (NoMethodError)
	from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:42:in `block in load'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:38:in `each'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:38:in `load'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchronize'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_lock'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:10:in `load'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:122:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `new'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
	from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

I have automatic OS updates enabled. Running Centos 7

**Comment by laf** [comment]
I've seen this recently, for me it was that I was using the wrong API key for LibreNMS integration, fixing that got it working so I'd say it's because the response from the http call isn't valid json maybe - have you tested it manually?

**Comment by loopodoopo** [comment]
Thank you for the quick response! LibreNMS API key was the issue!

Would be nice to have some better error handling here.

**Comment by brunobritocarvalho** [comment]
Ran into the same issue too, was indeed an API key error.
