### ISSUE TITLE
Error launching oxidized for the first time

### ISSUE THREAD

**Issue by Ondjultomte** [ytti/oxidized#1020]
```
[oxidized@localhost ~]$ /usr/local/bin/oxidized
Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 29 column 3
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/config.rb:52:in `rescue in load': Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 29 column 3 (Oxidized::InvalidConfig)
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/config.rb:49:in `load'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:24:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
[oxidized@localhost ~]$
```
`
```
username: username
password: password
model: ios
interval: 3600
log: ~/.config/oxidized/log
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
pid: /home/oxidized/.config/oxidized/pid
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: /home/oxidized/deviceconfigs
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
  map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos
```
`

**Comment by Ondjultomte** [comment]
29,3 is "default: csv" in the conf file. I don't see the error there. Any ideas?

**Comment by laf** [comment]
```
    delimiter: !ruby/regexp /:/
  map:
      name: 0
```

map: looks indented incorrectly. Try adding 2 more spaces before it.

**Comment by Ondjultomte** [comment]
Thnx! That solved it!

[oxidized@localhost oxidized]$ oxidized
Puma starting in single mode...
* Version 3.10.0 (ruby 2.0.0-p648), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
Use Ctrl-C to stop


Now I need to check why I get a timeout trying to access the vms IP, 0.0.0.0 should listen to any IP.

**Comment by laf** [comment]
Feel free to jump on gitter/irc if you need about the timeout issue. Seems most likely to be a firewall issue now. Run `lsof -i:8888` to make sure it's actually listening.
