### ISSUE TITLE
initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)

### ISSUE THREAD

**Issue by Ondjultomte** [ytti/oxidized#1079]
It seems that with 0.20 something changed, both in config and router.db

I did a new installation with 0.20 and ran into problems with oxid unable to find usable nodes. It worked out of the box with 0.19

`[oxidized@xxxx oxidized]$ oxidized
I, [2017-10-31T16:03:29.161167 #1920]  INFO -- : Oxidized starting, running as pid 1920
I, [2017-10-31T16:03:29.161922 #1920]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
E, [2017-10-31T16:03:29.168581 #1920] ERROR -- : node {:name=>"hostname, ios", :model=>nil} **is not resolvable, raised Resolv::ResolvError with message 'no address for hostname, ios'**
E, [2017-10-31T16:03:29.242778 #1920] ERROR -- : node {:name=>"172.23.20.2", :model=>nil} raised **Oxidized::ModelNotFound with message 'cisco not found for node 172.23.20.2'**
E, [2017-10-31T16:03:29.244859 #1920] ERROR -- : node {:name=>"hostname", :model=>nil} raised **Oxidized::ModelNotFound with message 'cisco not found for node 172.23.20.2'**
E, [2017-10-31T16:03:29.248565 #1920] ERROR -- : node {:name=>"hostname,172.23.20.2,ios", :model=>nil} is not resolvable, raised Resolv::ResolvError with message 'no address for hostname,172.23.20.2,ios'
I, [2017-10-31T16:03:29.248637 #1920]  INFO -- : **lib/oxidized/nodes.rb: Loaded 0 nodes**
F, [2017-10-31T16:03:29.248683 #1920] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
source returns no usable nodes
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:15:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'`

So I added a few different versions to router.db but none works. In 0.19 I just added the hostnames, but it doesnt work in 0.20

router.db:
```
hostname, ios
172.23.20.2
hostname
hostname,172.23.20.2,ios
```

/etc/hosts :
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4

::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

172.23.20.2 hostname
```

**Comment by Ondjultomte** [comment]
oxidizedconf:

`username: uuuuu
password: ppppp
model: cisco
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: /home/oxidized/.config/oxidized/oxidized.git
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  cisco: ios
  juniper: junos`

**Comment by Ondjultomte** [comment]
User error as usual :)
