### ISSUE TITLE
cannot find hook "slackdiff" (KeyError)

### ISSUE THREAD

**Issue by richbibby** [ytti/oxidized#1091]
Hi, 

I get the following after adding the slackdiff hook: 

```
cannot find hook "slackdiff"
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/hook.rb:43:in `rescue in register': cannot find hook "slackdiff" (KeyError)
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/hook.rb:40:in `register'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/hook.rb:8:in `block (2 levels) in from_config'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/hook.rb:7:in `each'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/hook.rb:7:in `block in from_config'
        from /var/lib/gems/2.1.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /var/lib/gems/2.1.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/hook.rb:6:in `from_config'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:13:in `initialize'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
        from /var/lib/gems/2.1.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```

I have installed the slack-api:

`gem install slack-api`

and my config looks like this: 

```
hooks:
  slack:
    type: slackdiff
    events: [post_store]
    token: MY_TOKEN
    channel: "#network-changes"
```
 and my Bot has joined the #network-changes slack channel

Thanks

**Comment by laf** [comment]
You need version 0.20.0 for slack support: https://github.com/ytti/oxidized/blob/master/CHANGELOG.md#0200

Please update and if your config is correct it should just work.

**Comment by richbibby** [comment]
Thanks Neil.  that's done it
