### ISSUE TITLE
"cannot find hook "slackdiff" [KeyError]" with Oxidized (0.21.0)

### ISSUE THREAD

**Issue by jchristopher327** [ytti/oxidized#1134]
Hi All,

I'm trying to get slack notifications for diffs but run into the following error (from crash file):

```
--------------------------------------------------
2017-12-22 17:31:49 UTC
cannot find hook "slackdiff" [KeyError]
--------------------------------------------------
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/hook.rb:44:in `rescue in register'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/hook.rb:41:in `register'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/hook.rb:8:in `block (2 levels) in from_config'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/hook.rb:7:in `each'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/hook.rb:7:in `block in from_config'
/home/oxidized/.gem/ruby/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/home/oxidized/.gem/ruby/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/hook.rb:6:in `from_config'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/core.rb:13:in `initialize'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
/home/oxidized/.gem/ruby/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
```
Here is the relevant hook config:
```
hooks:
  slack:
    type: slackdiff
    events: [post_store]
    token: yay
    channel: "#blah"
```
Oxidized and Slack gems.
```
[root@oxidized administrator]# gem list | grep ox
oxidized (0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.9.3)
[root@oxidized administrator]# gem list | grep slack
slack-api (1.6.0)
```

**Comment by laf** [comment]
```
[root@librenms01 ~]# gem list | grep -P 'oxidized|slack'
oxidized (0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.9.3)
slack-api (1.6.0)
```
I've just tested this on mine and it works ok for me.

You've restarted since updating to a newer version?

**Comment by jchristopher327** [comment]
Hi Laf, 
There was no updating to a newer version (I'm guessing you're talking about Oxidized). This a fresh install. Either way, the service was restarted after making the configuration changes.

**Comment by jchristopher327** [comment]
For giggles, I commented out `require slack` from `slackdiff.rb` and was able to start Oxidized. Now the error I get is the following (similar attempts in #969):
```
I, [2018-01-04T15:06:51.672438 #33727]  INFO -- : SlackDiff: Connecting to slack
E, [2018-01-04T15:06:51.672724 #33727] ERROR -- : Hook slack (#<SlackDiff:0x00000001ff52c0>) failed (#<NameError: uninitialized constant SlackDiff::Slack>) for event :post_store
```

**Comment by laf** [comment]
I can't see anything wrong I'm afraid. It works for me on these versions.

Maybe post your entire config, I'll use it to retest.

**Comment by jchristopher327** [comment]
Here you go laf.

```
---
username: sxxxx
password: xxxx
model: ios
interval: 3600
log: ~/.config/oxidized/log
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars:
   enable: xxxxx
groups: {}
models: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@xxx.com
    repo: "~/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco-ios: ios
  arista-eos: eos
  f5-big-ip: tmos
  juniper-junos: junos
  fortinet-fortios: fortios
  cisco-aireos: aireos
hooks:
  slack:
    type: slackdiff
    events: [post_store]
    token: xoxb-xxxxxxxx
    channel: "#network-configs"
```

**Comment by jchristopher327** [comment]
Hi @laf, any chance you were able to test with my config?

**Comment by laf** [comment]
Sorry @jchristopher327 I had forgot. I've just tested it now and it still works ok for me. I had to change the source to http and the git output so it worked in my env (I also have single repo set for git output) but aside from that everything else was the same :(

**Comment by jchristopher327** [comment]
Hey @laf! I was just poking around and got it to work! I ended up uninstalling the slack-api gem and reinstalled it as the oxidized user. Not sure why that worked but figured I'd try it out and got lucky :).

**Comment by laf** [comment]
Ace. Glad it's working.
