### ISSUE TITLE
Problem launching oxidized as systemd service

### ISSUE THREAD

**Issue by andyburridge** [ytti/oxidized#1202]
Hi Guys,

I'm trying to use the oxidized service and am having a few issues.  I've copied the service to systemd as follows, making no amendments to the default:

```
sudo cp /var/lib/gems/2.3.0/gems/oxidized-0.21.0/extra/oxidized.service /lib/systemd/system
sudo systemctl enable oxidized.service
```

When I launch it with:

`sudo systemctl start oxidized.service`

I get the following:

```
sudo systemctl status oxidized.service   
â— oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/lib/systemd/system/oxidized.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-03-02 13:30:23 GMT; 5s ago
  Process: 2066 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)
 Main PID: 2066 (code=exited, status=1/FAILURE)

Mar 02 14:26:27 oxila01lv oxidized[2126]: Permission denied @ unlink_internal - /home/oxidized/.config/oxidized/pid
Mar 02 14:26:27 oxila01lv oxidized[2126]: /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:81:in `delete': Permission denied @ unlink_internal - /home/oxidized/.config/oxidized/pid (Errno::EACCES)
Mar 02 14:26:27 oxila01lv oxidized[2126]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:81:in `check_pid'
Mar 02 14:26:27 oxila01lv oxidized[2126]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:7:in `run'
Mar 02 14:26:27 oxila01lv oxidized[2126]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
Mar 02 14:26:27 oxila01lv oxidized[2126]:         from /usr/local/bin/oxidized:23:in `load'
Mar 02 14:26:27 oxila01lv oxidized[2126]:         from /usr/local/bin/oxidized:23:in `<main>'
Mar 02 14:26:27 oxila01lv systemd[1]: oxidized.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 14:26:27 oxila01lv systemd[1]: oxidized.service: Unit entered failed state.
Mar 02 14:26:27 oxila01lv systemd[1]: oxidized.service: Failed with result 'exit-code'.
```

Running oxidized directly from the CLI with:

`sudo oxidized`

Works absolutely fine.  Is this likely that this is failing because the oxidized service is running as the base 'oxidized' user, without sudo?  Or is there something else I've missed?

**Comment by laf** [comment]
Check the permissions on the /home/oxidized/.config/oxidized/pid and directories above that to make sure it's owned correctly.

SELinux if not?

**Comment by andyburridge** [comment]
Thanks, you got it.  Root owned all the files/folders in the /home/oxidized/.config directory downwards.  A quick:

`find . | xargs sudo chown oxidized`

Hooked me up.  Really appreciate the quick reply.
