### ISSUE TITLE
Issues adding a new model

### ISSUE THREAD

**Issue by andyburridge** [ytti/oxidized#1363]
I have a Cisco router that performs some background function that causes it to see the configuration as updated every 6 hours.  Oxidized sees this as a change to the running configuration, and acts accordingly.

I want to exclude the 'Last configuration change at....' line from the running configuration for only that device so that I can make it less noisy.

I've created a new model **ios-noconfigupdated.rb** and place it in .config/oxidized/model/

This model is an exact copy of the **ios.rb** model, but with the following amendment:

```
 cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1]
    cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join
    cfg.gsub! /^Current configuration : [^\n]*\n/, ''
    cfg.gsub! /^! Last configuration change at .*/, ''          --Added this line
    cfg.gsub! /^\ tunnel\ mpls\ traffic-eng\ bandwidth[^\n]*\n*(
                  (?:\ [^\n]*\n*)*
                  tunnel\ mpls\ traffic-eng\ auto-bw)/mx, '\1'
    cfg
  end
```

I then edited my config file as follows:

```
model_map:
  cisco: ios
  juniper: junos
  cisco-noconfigupdated: ios-noconfigupdated
```

And edited the router.db file to force the device in question to match the new model.  When I run oxidized, it recognises the model, loads it, but then crashes as follows:

```
Jun  5 09:22:00 oxila01lv oxidized[7172]: node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
Jun  5 09:22:00 oxila01lv oxidized[7172]: node.rb: returning node key 'input' with value 'ssh'
Jun  5 09:22:00 oxila01lv oxidized[7172]: node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
Jun  5 09:22:00 oxila01lv oxidized[7172]: node.rb: returning node key 'output' with value 'git'
Jun  5 09:22:00 oxila01lv oxidized[7172]: node.rb: resolving node key 'model', with passed global value of '' and node value 'ios-noconfigupdated'
Jun  5 09:22:00 oxila01lv oxidized[7172]: node.rb: setting node key 'model' to value 'cisco' from global
Jun  5 09:22:00 oxila01lv oxidized[7172]: node.rb: returning node key 'model' with value 'ios-noconfigupdated'
Jun  5 09:22:00 oxila01lv oxidized[7172]: lib/oxidized/node.rb: Loading model "ios-noconfigupdated"
Jun  5 09:22:00 oxila01lv oxidized[7172]: lib/oxidized/model/model.rb Added all to the commands list
Jun  5 09:22:00 oxila01lv oxidized[7172]: lib/oxidized/model/model.rb Added secret to the commands list
Jun  5 09:22:00 oxila01lv oxidized[7172]: lib/oxidized/model/model.rb Added show version to the commands list
Jun  5 09:22:00 oxila01lv oxidized[7172]: lib/oxidized/model/model.rb Added show vtp status to the commands list
Jun  5 09:22:00 oxila01lv oxidized[7172]: lib/oxidized/model/model.rb Added show inventory to the commands list
Jun  5 09:22:00 oxila01lv oxidized[7172]: lib/oxidized/model/model.rb Added show running-config to the commands list
Jun  5 09:22:00 oxila01lv oxidized[7172]: Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
```

With the crash output:

```
--------------------------------------------------
2018-06-05 08:22:00 UTC
undefined method `new' for nil:NilClass [NoMethodError]
--------------------------------------------------
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/manager.rb:18:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/manager.rb:46:in `add_model'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:164:in `resolve_model'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:23:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `synchronize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `with_lock'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:123:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

Would anyone be able to advise on what I can do to resolve this?

Thanks!

**Comment by wk** [comment]
If the filename of a model is modified, the name of the class (i.e. `class IOS < Oxidized::Model`) will also need to be modified to match the filename. It's advised to avoid special characters in model and class names.

**Comment by andyburridge** [comment]
Cool, that did the trick.  

Renaming the class to match the model name stopped the crash, but then oxidized just hung at loading the actual model.  When I removed the special character from the model name, it worked great.

Thanks for your help.
