### ISSUE TITLE
Cisco MDS switches no config back-up 

### ISSUE THREAD

**Issue by v4l3x76** [ytti/oxidized#1368]
Hello,

 it seems no end of line identified on command output those switches.
Any idea?

model]# /usr/local/share/gems/bin/oxs -m nxos -u user -p passwd -v -d device 'show running-config'
execution expired

/usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:130:in `sleep': execution expired (Timeout::Error)
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:130:in `block (2 levels) in expect'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:221:in `preprocess'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:206:in `process'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:129:in `block in expect'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:128:in `expect'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:122:in `cmd_shell'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:62:in `cmd'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/model/model.rb:84:in `cmd'
	from /usr/local/share/gems/gems/oxidized-script-0.2.0/lib/oxidized/script/script.rb:22:in `cmd'
	from /usr/local/share/gems/gems/oxidized-script-0.2.0/lib/oxidized/script/cli.rb:16:in `run'
	from /usr/local/share/gems/gems/oxidized-script-0.2.0/bin/oxs:5:in `<top (required)>'
	from /usr/local/share/gems/bin/oxs:23:in `load'
	from /usr/local/share/gems/bin/oxs:23:in `<main>'

**Comment by wk** [comment]
Please follow the [debugging](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#debugging) instructions and append a log of interaction with the device to this issue.

**Comment by v4l3x76** [comment]
Hello, here the debug and command output

D, [2018-06-11T07:59:51.125783 #2619] DEBUG -- : resolving DNS for device...
D, [2018-06-11T07:59:51.183899 #2619] DEBUG -- : lib/oxidized/node.rb: Loading model "nxos"
D, [2018-06-11T07:59:51.185029 #2619] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2018-06-11T07:59:51.185082 #2619] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2018-06-11T07:59:51.185107 #2619] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2018-06-11T07:59:51.185142 #2619] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2018-06-11T07:59:51.185574 #2619] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to device
D, [2018-06-11T07:59:51.815414 #2619] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^(\r?[\w.@_()-]+[#]\s?)$/ at device
D, [2018-06-11T07:59:53.420180 #2619] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at device
D, [2018-06-11T07:59:53.420288 #2619] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal length 0", block: nil at device
D, [2018-06-11T07:59:53.420321 #2619] DEBUG -- : lib/oxidized/input/ssh.rb terminal length 0 @ device with expect: /^(\r?[\w.@_()-]+[#]\s?)$/
D, [2018-06-11T07:59:53.420453 #2619] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^(\r?[\w.@_()-]+[#]\s?)$/ at device
D, [2018-06-11T07:59:53.821568 #2619] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2018-06-11T07:59:53.821686 #2619] DEBUG -- : lib/oxidized/input/ssh.rb show version @ device with expect: /^(\r?[\w.@_()-]+[#]\s?)$/
D, [2018-06-11T07:59:53.821860 #2619] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^(\r?[\w.@_()-]+[#]\s?)$/ at device



[root@oxi]# /usr/local/share/gems/bin/oxs -m nxos -u user -p pwd -v -d device 'show version'
execution expired
/usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:130:in `sleep': execution expired (Timeout::Error)
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:130:in `block (2 levels) in expect'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:221:in `preprocess'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:206:in `process'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:129:in `block in expect'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:128:in `expect'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:122:in `cmd_shell'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/input/ssh.rb:62:in `cmd'
	from /usr/local/share/gems/gems/oxidized-0.16.1/lib/oxidized/model/model.rb:84:in `cmd'
	from /usr/local/share/gems/gems/oxidized-script-0.2.0/lib/oxidized/script/script.rb:22:in `cmd'
	from /usr/local/share/gems/gems/oxidized-script-0.2.0/lib/oxidized/script/cli.rb:16:in `run'
	from /usr/local/share/gems/gems/oxidized-script-0.2.0/bin/oxs:5:in `<top (required)>'
	from /usr/local/share/gems/bin/oxs:23:in `load'
	from /usr/local/share/gems/bin/oxs:23:in `<main>'

thank you

**Comment by wk** [comment]
Could you include the ssh log file which contains the exact interaction with the device? Additionally, it would be interesting to know the output of `show version` on the device, as well as the device name and prompt.

From the log, it indeed seems the prompt can't be detected after the first command executed, but I am unble to reproduce it on an NX-OS device (5.2.1(N1)).

**Comment by v4l3x76** [comment]
Hello, is there an ssh log file related to  oxs??
Or I'll need to run ssh in debug mode?
I did find on the internet a similar issue with rancid --> http://www.shrubbery.net/pipermail/rancid-discuss/2008-April/003042.html

this is the output of the show version

Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2014, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

Software
  BIOS:      version 2.1.17
  loader:    version N/A
  kickstart: version 6.2(9)
  system:    version 6.2(9)
  BIOS compile time:       01/08/14
  kickstart image file is: bootflash:///m9100-s5ek9-kickstart-mz.6.2.9.bin
  kickstart compile time:  6/3/2014 1:00:00 [07/11/2014 19:47:38]
  system image file is:    bootflash:///m9100-s5ek9-mz.6.2.9.bin
  system compile time:     6/3/2014 1:00:00 [07/11/2014 21:45:36]

Hardware
  cisco MDS 9148S 16G 48 FC (1 Slot) Chassis ("2/4/8/16 Gbps FC/Supervisor")
  Motorola, e500v2, core 0  with 4155776 kB of memory.
  Processor Board ID JAE201705JF

  Device name: swmds001
  bootflash:    4001760 kB
Kernel uptime is 706 day(s), 5 hour(s), 10 minute(s), 47 second(s)

Last reset at 981275 usecs after  Wed Jul 13 10:52:30 2016

  Reason: Reset Requested by CLI command reload
  System version: 6.2(9)
  Service: 

plugin
  Core Plugin


thank you

**Comment by v4l3x76** [comment]
Hello do you have an update?

**Comment by posixx** [comment]
We are looking into oxidezed for backup condifurations of our new Cisco MDS 9132T switches running NX-OS. According to this issue it;'s not possible to backup these configs. Is this conclusion based on funcionality or because of not enough debuglogs available? In other words; can this be made working when having enough info?
