### ISSUE TITLE
use custom secret block

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#1384]
Hello,

Trying this out https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md
Prior to this we simply re-defined the whole module and added our own custom 'cmd' and 'secrets' we wanted to remove.
This is sort of a pain when it comes to upgrades because then it means that the custom models need to be adjusted too. 

Been playing with it and found that this works good:
```
class IOS < Oxidized::Model
  
  cmd :secret do |cfg|
    cfg.gsub! /^(snmp-server community) \S+ (.*)/, '\\1 <redacted> \\2'
    cfg.gsub! /^username \S+ password \d \S+/, '<redacted>'
    cfg.gsub! /^enable password \d \S+/, '<redacted>'
    cfg.gsub! /wpa-psk ascii \d \S+/, '<redacted>'
    cfg.gsub! /^tacacs-server key \d \S+/, '<redacted>'
    cfg.gsub! /^(username (\S+) privilege (\d+) (\S+) (\d+)).*/, '\\1 <redacted>'
    cfg.gsub! /^(radius-server key).*/, '\\1 <redacted>'
    cfg.gsub! /(pre-shared-key (\S+) (\d+)).*/, '\\1 <redacted>'
    cfg.gsub! /^(\s+sap pmk \d) .* (\S+ \S+)/, '\\1 <redacted> \\2'
    cfg.gsub! /^(tacacs-server key \d) (\S+)/, '\\1 <secret hidden>'
    cfg.gsub! /^(crypto isakmp key) (\S+) (.*)/, '\\1 <secret hidden> \\3'
    cfg
  end

  cmd 'dir' do |cfg|
    comment cfg
  end

require 'oxidized/model/ios.rb'

end
```

Now i put the `require` at the end because i want the `dir` to be commented at the top, and those are the results i get. 

Now my issue: is there a way to say `dont use default :secret: block but use my secrete instead`? 

Consider my ruby skill = 0  :/

Thank you in advance,

dave

**Comment by davama** [comment]
@ytti thank you for the sample

using the `pre do` definitely makes the output go to the very top of the backup as a comment. Thats great! more clean looking. :+1: 

the default `:secret` block is still being used. I want to use my `custom :secret` block instead. 

Is that possible?

**Comment by davama** [comment]
In other words, i want to redact what i want/need

**Comment by ytti** [comment]
Can you test this branch https://github.com/ytti/oxidized/tree/feature-mode_cfg_reorder

**Comment by davama** [comment]
sure thing!
give me a sec

**Comment by davama** [comment]
Ok, here are my results:

Testing with `ciscosmb`, `ios`, and `procurve`. All Extended-models looks similar as here https://github.com/ytti/oxidized/issues/1384#issue-331967373 but with the `pre do` and `require` on top as @ytti  suggested.

**Output results:**
With the `.unshift` changes all the `commented` output that would normally go at the top in `lib/oxidized/model/<model.rb>` are placed at the bottom of the running-config; with any custom `cmd` in `~/.config/oxidized/model/<model>.rb` placed on top of the running-config. 

At least in regard to output comments, this is quite new. Not sure how it might impact other users, though it's just a comment but whatever.

In regard to using "custom" `:secret` block,  the `:secret` block in the `lib/oxidized/...` folder is prefered over the `~/.config/oxidized/...` folder. 

```
-username manager privilege 15 secret 5 <redacted>
+username manager privilege 15 <secret hidden>
 !
 !
-snmp-server community <redacted> RO
+snmp-server community <configuration removed>
```
The `redacted` one is the custom one `~/.config/oxidized/..`
The `removed`, `hidden` is default `lib/oxidized/...`

Thanks!

**Comment by ytti** [comment]
So let me get this straight:

```
      def cmd _cmd = nil, &block
        if _cmd.class == Symbol
          @cmd[_cmd].unshift block
        else
          @cmd[:cmd].unshift [_cmd, block]
        end
        Oxidized.logger.debug "lib/oxidized/model/model.rb Added #{_cmd} to the commands list"
      end
```

and

```
      def cmd _cmd = nil, &block
        if _cmd.class == Symbol
          @cmd[_cmd] << block
        else
          @cmd[:cmd] << [_cmd, block]
        end
        Oxidized.logger.debug "lib/oxidized/model/model.rb Added #{_cmd} to the commands list"
      end
```

On both cases the distribution secret block is the result that you end up seeing? Because the first example should cause your secret block to be ran last where as the last example should cause distribution secret block to be ran last.

But if I'm reading you correctly, in both cases it seems to be the distribution :secret which is being ran last?

**Comment by davama** [comment]
> But if I'm reading you correctly, in both cases it seems to be the distribution :secret which is being ran last?

yes


**Git diffs:**

from before the creation of this ticket to testing the Extended-models with @ytti's suggestion; the diff is:
```
@@ -1,3 +1,16 @@
+! Directory of flash:/
+! 
+!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
+!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
+!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
+!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
+!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
+!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
+!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
+!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
+!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
+! 
+! 31808000 bytes total (19696640 bytes free)
 ! Cisco IOS Software, C1600 Software (AP1G2-K9W7-M), Version 15.3(3)JD, RELEASE SOFTWARE (fc3)
 ! 
 ! Image: Software: AP1G2-K9W7-M, 15.3(3)JD, RELEASE SOFTWARE (fc3)
@@ -14,19 +27,6 @@
 ! PID: AIR-SAP1602E-A-K9 , VID: V01, SN: FGL1748X0ZB
 ! 
 ! 
-! Directory of flash:/
-! 
-!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
-!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
-!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
-!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
-!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
-!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
-!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
-!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
-!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
-! 
-! 31808000 bytes total (19696640 bytes free)
 !
 ! Last configuration change at 03:35:49 UTC Wed Jun 28 1995 by hwetzel
 version 15.3
@@ -106,7 +106,7 @@ archive
   logging enable
   notify syslog contenttype plaintext
   hidekeys
-username manager privilege 15 secret 5 <redacted>
+username manager privilege 15 <secret hidden>
 !
 !
 bridge irb
@@ -255,7 +255,7 @@ logging origin-id hostname
 logging facility local0
 logging host ipv6 xxx:xxx:xxx
 !
-snmp-server community <redacted> RO
+snmp-server community <redacted> removed>
```

using branch https://github.com/ytti/oxidized/tree/feature-mode_cfg_reorder with extended-models; the diff is:

```
@@ -11,22 +11,6 @@
 !     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
 ! 
 ! 31808000 bytes total (19696640 bytes free)
-! Cisco IOS Software, C1600 Software (AP1G2-K9W7-M), Version 15.3(3)JD, RELEASE SOFTWARE (fc3)
-! 
-! Image: Software: AP1G2-K9W7-M, 15.3(3)JD, RELEASE SOFTWARE (fc3)
-! Image: Compiled: Fri 29-Jul-16 02:49 by prod_rel_team
-! Image: flash:/ap1g2-k9w7-mx.153-3.JD/ap1g2-k9w7-xx.153-3.JD
-! Chassis type: AIR-SAP1602E-A-K9
-! Memory: main 187386K/74672K
-! Processor ID: FGL1748X0ZB
-! CPU: PowerPC, PowerPC CPU at 533Mhz, revision number 0x2151
-! 
-! VTP: show vtp status
-! 
-! NAME: "AP1600", DESCR: "Cisco Aironet 1600 Series (IEEE 802.11n) Access Point"
-! PID: AIR-SAP1602E-A-K9 , VID: V01, SN: FGL1748X0ZB
-! 
-! 
 !
 ! Last configuration change at 03:35:49 UTC Wed Jun 28 1995 by hwetzel
 version 15.3
@@ -255,7 +239,7 @@ logging origin-id hostname
 logging facility local0
 logging host ipv6 2607:2400:901:36::12
 !
-snmp-server community <redacted> removed>
+snmp-server community <configuration removed>
 snmp-server location WIFI1
 snmp-server contact CDE
 snmp ifmib ifalias long
@@ -306,3 +290,19 @@ line vty 5 15
 !
 end
 
+! NAME: "AP1600", DESCR: "Cisco Aironet 1600 Series (IEEE 802.11n) Access Point"
+! PID: AIR-SAP1602E-A-K9 , VID: V01, SN: FGL1748X0ZB
+! 
+! 
+! VTP: show vtp status
+! 
+! Cisco IOS Software, C1600 Software (AP1G2-K9W7-M), Version 15.3(3)JD, RELEASE SOFTWARE (fc3)
+! 
+! Image: Software: AP1G2-K9W7-M, 15.3(3)JD, RELEASE SOFTWARE (fc3)
+! Image: Compiled: Fri 29-Jul-16 02:49 by prod_rel_team
+! Image: flash:/ap1g2-k9w7-mx.153-3.JD/ap1g2-k9w7-xx.153-3.JD
+! Chassis type: AIR-SAP1602E-A-K9
+! Memory: main 187386K/74672K
+! Processor ID: FGL1748X0ZB
+! CPU: PowerPC, PowerPC CPU at 533Mhz, revision number 0x2151
+! 
```

With the branch `.unshift` edits the distribution comments get moved to the bottom, not sure if an issue...

But as you can see, the distribution `:secret` runs last. In the distribution `:secret`, with other models, there are lines that are "hidden" that we dont need hidden. That is why we had redefined the existing models we used in the first place, which goes back to the first post about updating custom models on each upgrade.

So,to be clear... dont use distribution `:secret` instead use user defined `:secret`.
Not sure if possible or feasible

Thank you again for the kind support @ytti

**Comment by ytti** [comment]
Can you try this: https://github.com/ytti/oxidized/commit/ec09840b305b42d87724489ec44ba4ab5d9d2ba7

```
cmd :secret, clear: true do |cfg|
   ..
end
```

**Comment by davama** [comment]
Tried your changes
How my `~/.config/oxidized/model/ios.rb` looks like
```
require 'oxidized/model/ios.rb'
class IOS < Oxidized::Model
  cmd :secret, clear: true do |cfg|
    cfg.gsub! /^(snmp-server community) \S+ (.*)/, '\\1 <redacted> \\2'
    cfg.gsub! /^(username (\S+) privilege (\d+) (\S+) (\d+)).*/, '\\1 <redacted>'
    cfg.gsub! /^(radius-server key).*/, '\\1 <redacted>'
    cfg.gsub! /(pre-shared-key (\S+) (\d+)).*/, '\\1 <redacted>'
    cfg
  end
  pre do
    cmd "dir" do |cfg|
      comment cfg
    end
  end
end
```

After applying your changes https://github.com/ytti/oxidized/commit/ec09840b305b42d87724489ec44ba4ab5d9d2ba7 here is the diff.

```
@@ -1,3 +1,16 @@
+! Directory of flash:/
+! 
+!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
+!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
+!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
+!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
+!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
+!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
+!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
+!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
+!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
+! 
+! 31808000 bytes total (19696640 bytes free)
 ! Cisco IOS Software, C1600 Software (AP1G2-K9W7-M), Version 15.3(3)JD, RELEASE SOFTWARE (fc3)
 ! 
 ! Image: Software: AP1G2-K9W7-M, 15.3(3)JD, RELEASE SOFTWARE (fc3)
@@ -14,19 +27,6 @@
 ! PID: AIR-SAP1602E-A-K9 , VID: V01, SN: FGL1748X0ZB
 ! 
 ! 
-! Directory of flash:/
-! 
-!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
-!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
-!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
-!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
-!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
-!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
-!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
-!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
-!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
-! 
-! 31808000 bytes total (19696640 bytes free)
 !
 ! Last configuration change at 03:35:49 UTC Wed Jun 28 1995 by hwetzel
 version 15.3
@@ -106,7 +106,7 @@ archive

-username manager privilege 15 secret 5 <redacted>  ##if it can stay like this line... :(##
+username manager privilege 15 <secret hidden>       ##clearly from the distribution##
 !

 !
-snmp-server community <redacted> RO   ##if it can stay like this line... :(##
+snmp-server community <redacted> removed>   ##looks distribution ran then mine ran##
```

**observations**
* My `dir` output was moved to the top
* distribution `:secret` output is mixed (see comments on diff)

Either way distribution `:secret` always runs

**Comment by ytti** [comment]
Hahah, I have logic wrong way around. I'm pushing new one, if it's clean, and if clean is not set, i'm replacing.

Try setting clean to false :>

If it works, we should be good to go, just need to swap the if/else.

**Comment by ytti** [comment]
I have hopefully the generic/clean/final version in the branch

**Comment by davama** [comment]
:smile: 

Saw your update https://github.com/ytti/oxidized/commit/eba7a75879cf8b8ed57a694c70a41bff9764152f

I think it works, doing some verification

**Comment by davama** [comment]
@ytti 

thank you again! you have been great!
I think i get an crash error.

not sure if related to https://github.com/ytti/oxidized/commit/35487166c0a930c1d8309c9be1dd12c6d876dc93

```
oxidized -d
no implicit conversion of Symbol into Integer
/usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/model/model.rb:90:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/model/model.rb:90:in `process_args_block'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/model/model.rb:39:in `cmd'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/model/ios.rb:18:in `<class:IOS>'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/model/ios.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/config/.config/oxidized/model/ios.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/manager.rb:9:in `load'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/manager.rb:59:in `loader'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/manager.rb:47:in `add_model'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/node.rb:170:in `resolve_model'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/node.rb:22:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:20:in `new'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:20:in `block (2 levels) in load'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:16:in `each'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:16:in `block in load'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:128:in `synchronize'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:128:in `with_lock'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:10:in `load'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/nodes.rb:123:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/core.rb:14:in `new'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/core.rb:14:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.23.0/lib/oxidized/cli.rb:12:in `run'
	from /usr/local/share/gems/gems/oxidized-0.23.0/bin/oxidized:8:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

**Comment by ytti** [comment]
argument order issue fixed

**Comment by ytti** [comment]
another breaking issue fixed

**Comment by davama** [comment]
hehe still playing with it

been noticing the changes :+1:

**Comment by davama** [comment]
Results:

Going from latest [master](https://github.com/ytti/oxidized) branch to current [feature](https://github.com/ytti/oxidized/compare/feature-mode_cfg_reorder) branch, my diff looks like so:

```
@@ -1,3 +1,16 @@
+! Directory of flash:/
+! 
+!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
+!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
+!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
+!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
+!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
+!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
+!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
+!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
+!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
+! 
+! 31808000 bytes total (19696640 bytes free)
 ! Cisco IOS Software, C1600 Software (AP1G2-K9W7-M), Version 15.3(3)JD, RELEASE SOFTWARE (fc3)
 ! 
 ! Image: Software: AP1G2-K9W7-M, 15.3(3)JD, RELEASE SOFTWARE (fc3)
@@ -14,19 +27,6 @@
 ! PID: AIR-SAP1602E-A-K9 , VID: V01, SN: FGL1748X0ZB
 ! 
 ! 
-! Directory of flash:/
-! 
-!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
-!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
-!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
-!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
-!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
-!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
-!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
-!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
-!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
-! 
-! 31808000 bytes total (19696640 bytes free)
 !
 ! Last configuration change at 03:35:49 UTC Wed Jun 28 1995 by hwetzel
 version 15.3
@@ -106,7 +106,7 @@ archive
   logging enable
   notify syslog contenttype plaintext
   hidekeys
-username manager privilege 15 secret 5 <redacted>
+username manager privilege 15 <secret hidden>
 !
 !
 bridge irb
@@ -255,7 +255,7 @@ logging origin-id hostname
-snmp-server community <redacted> RO
+snmp-server community <redacted> removed>
```
Unfortunately, no change :frowning_face: 


BUT!

checkingout instead from commit https://github.com/ytti/oxidized/commit/eba7a75879cf8b8ed57a694c70a41bff9764152f looks better:

```
@@ -1,3 +1,16 @@
+! Directory of flash:/
+! 
+!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
+!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
+!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
+!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
+!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
+!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
+!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
+!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
+!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
+! 
+! 31808000 bytes total (19696640 bytes free)
 ! Cisco IOS Software, C1600 Software (AP1G2-K9W7-M), Version 15.3(3)JD, RELEASE SOFTWARE (fc3)
 ! 
 ! Image: Software: AP1G2-K9W7-M, 15.3(3)JD, RELEASE SOFTWARE (fc3)
@@ -14,19 +27,6 @@
 ! PID: AIR-SAP1602E-A-K9 , VID: V01, SN: FGL1748X0ZB
 ! 
 ! 
-! Directory of flash:/
-! 
-!     2  -rwx      161776  Aug 16 1995 13:46:10 +00:00  event.r0
-!     3  -rwx        2072  Jun 28 1995 03:35:50 +00:00  private-multiple-fs
-!    14  drwx         896  Mar 12 1995 12:04:54 +00:00  ap1g2-k9w7-mx.153-3.JD
-!     4  -rwx      110931  Mar 16 1995 07:15:57 +00:00  event.log
-!     5  -rwx        1904  Jun 28 1995 03:35:50 +00:00  private-config
-!     6  -rwx      160122  Aug 16 1995 13:46:26 +00:00  event.r1
-!     7  -rwx        6236  Jun 28 1995 03:35:50 +00:00  config.txt
-!    12  -rwx           4  Apr 16 1995 07:46:53 +00:00  FOC17436B1F
-!     8  -rwx         232   Dec 4 1995 07:12:14 +00:00  env_vars
-! 
-! 31808000 bytes total (19696640 bytes free)
 !
 ! Last configuration change at 03:35:49 UTC Wed Jun 28 1995 by hwetzel
 version 15.3
```
Here i only get the `dir` changes which comments it to the very top. which means that the local `:secret` was run instead because there is no change there.

```
username manager privilege 15 secret 5 <redacted>
snmp-server community <redacted> RO
```

**Comment by ytti** [comment]
Ehh, I used verb 'clean' in the feature branch, and 'clear' in the commit. It probably works fine. I'll change the verb back to 'clear'. I think it's better, I'm also open to suggestion what verb to use.

**Comment by davama** [comment]
Woohoo!

Looks good!

So if i understand this correctly, these changes on the feature branch, allow for the usage of custom `:secret` instead of the distribution `:secret`. Yes?

I am more than happy to submit a PR for some verbiage for this on the [doc](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md) file. 

Thank you very much @ytti

**Comment by ytti** [comment]
The change allows any cmd, cfg, pre, post or expect to reset the call-back array and insert only the proceeding call-back there.

It also allows you to change the call back addition from push to unshift (needed for another use case).

I'll merge to master, thanks for testing.
