### ISSUE TITLE
Oxidized crash: Cannot assign requested address - bind(2)

### ISSUE THREAD

**Issue by rongtler** [ytti/oxidized#1454]
Hi guys, 
I'm trying to integrating Oxidized into LibreNMS. When I run `oxidized`, an error appear:

```
[oxidized@localhost ~]$ oxidized
I, [2018-07-18T15:42:29.896795 #14638]  INFO -- : Oxidized starting, running as pid 14638
I, [2018-07-18T15:42:29.898713 #14638]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2018-07-18T15:42:29.899018 #14638] DEBUG -- : resolving DNS for 192.168.10.11...
D, [2018-07-18T15:42:29.899102 #14638] DEBUG -- : IPADDR 
D, [2018-07-18T15:42:29.899622 #14638] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ios'
D, [2018-07-18T15:42:29.899678 #14638] DEBUG -- : node.rb: setting node key 'model' to value 'cisco' from global
D, [2018-07-18T15:42:29.899738 #14638] DEBUG -- : node.rb: returning node key 'model' with value 'ios'
D, [2018-07-18T15:42:29.899848 #14638] DEBUG -- : lib/oxidized/node.rb: Loading model "ios"
D, [2018-07-18T15:42:29.902588 #14638] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2018-07-18T15:42:29.902683 #14638] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2018-07-18T15:42:29.902729 #14638] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2018-07-18T15:42:29.902766 #14638] DEBUG -- : lib/oxidized/model/model.rb Added show vtp status to the commands list
D, [2018-07-18T15:42:29.902801 #14638] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2018-07-18T15:42:29.902837 #14638] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2018-07-18T15:42:29.903489 #14638] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'telnet, ssh' and node value ''
D, [2018-07-18T15:42:29.903566 #14638] DEBUG -- : node.rb: returning node key 'input' with value 'telnet, ssh'
D, [2018-07-18T15:42:30.223243 #14638] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2018-07-18T15:42:30.223341 #14638] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2018-07-18T15:42:30.454280 #14638] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2018-07-18T15:42:30.454366 #14638] DEBUG -- : node.rb: setting node key 'username' to value 'username' from global
D, [2018-07-18T15:42:30.454413 #14638] DEBUG -- : node.rb: returning node key 'username' with value 'username'
D, [2018-07-18T15:42:30.454442 #14638] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2018-07-18T15:42:30.454474 #14638] DEBUG -- : node.rb: setting node key 'password' to value 'password' from global
D, [2018-07-18T15:42:30.454508 #14638] DEBUG -- : node.rb: returning node key 'password' with value 'password'
I, [2018-07-18T15:42:30.454619 #14638]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2018-07-18T15:42:31.684188 #14638] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2018-07-18T15:42:31.684517 #14638] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2018-07-18T15:42:31.684884 #14638] DEBUG -- : lib/oxidized/worker.rb: Added 192.168.10.11 to the job queue
D, [2018-07-18T15:42:31.684973 #14638] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-07-18T15:42:31.685163 #14638] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 192.168.10.11 at 2018-07-18 08:42:31 UTC
Puma starting in single mode...
* Version 3.11.4 (ruby 2.0.0-p648), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://192.168.10.11:8888
F, [2018-07-18T15:42:31.782547 #14638] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
Cannot assign requested address - bind(2)
/usr/local/share/gems/gems/puma-3.11.4/lib/puma/binder.rb:270:in `initialize': Cannot assign requested address - bind(2) (Errno::EADDRNOTAVAIL)
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/binder.rb:270:in `new'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/binder.rb:270:in `add_tcp_listener'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/binder.rb:105:in `block in parse'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/binder.rb:88:in `each'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/binder.rb:88:in `parse'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/runner.rb:144:in `load_and_bind'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/single.rb:87:in `run'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/launcher.rb:184:in `run'
	from /usr/local/share/gems/gems/puma-3.11.4/lib/rack/handler/puma.rb:70:in `run'
	from /usr/local/share/gems/gems/oxidized-web-0.11.1/lib/oxidized/web.rb:29:in `block in run'
```

Here is my config file:
```
---
username: username
password: password
model: cisco
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.10.11:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: telnet, ssh
  debug: true
output:
  default: git
  git:
    user: sysadmin
    email: o@example.com
    repo: "/home/oxidized/.config/oxidized/devices"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  cisco: ios
  juniper: junos
```
And the router.db file:

```
#Switch1
192.168.10.11:ios:username:password
```

Any idea to solve this problem? 
I'm also curious to know about the meaning of `rest: 192.168.10.11:8888` in the config file and how to config it properly. 
Thanks!

**Comment by ytti** [comment]
The rest tell which IP address on your local device the web server is listening to. You told it to listen on IP 192.168.10.11 your operating system is telling you it cannot bind to such address. 

You should change that IP address to some IP address you have configured on your device and where you want the web server to listen.

**Comment by ytti** [comment]
Have you read this document? https://docs.librenms.org/#Extensions/Oxidized/

I read your question as if you're asking me what is the IP address of a switch in your network, but I must misunderstand as that would be non-sensical question to ask.

**Comment by rongtler** [comment]
I did finished provide the detailed integration information step. Here is my config.php file: 

```
<?php
## Have a look in defaults.inc.php for examples of settings you can set here. DO NOT EDIT defaults.inc.php!

### Database config
$config['db_host'] = 'localhost';
$config['db_port'] = '3306';
$config['db_user'] = 'librenms';
$config['db_pass'] = 'cmctelekom';
$config['db_name'] = 'librenms';
$config['db_socket'] = '';

// This is the user LibreNMS will run as
//Please ensure this user is created and has the correct permissions to your install
$config['user'] = 'librenms';

### Locations - it is recommended to keep the default
#$config['install_dir']  = "/opt/librenms";
### This should *only* be set if you want to *force* a particular hostname/port
### It will prevent the web interface being usable form any other hostname
#$config['base_url']        = "http://librenms.company.com";

### Enable this to use rrdcached. Be sure rrd_dir is within the rrdcached dir
### and that your web server has permission to talk to rrdcached.
#$config['rrdcached']    = "unix:/var/run/rrdcached.sock";

### Default community
$config['snmp']['community'] = array("public");

### Authentication Model
$config['auth_mechanism'] = "mysql"; # default, other options: ldap, http-auth
#$config['http_auth_guest'] = "guest"; # remember to configure this user if you use http-auth

### List of RFC1918 networks to allow scanning-based discovery
#$config['nets'][] = "10.0.0.0/8";
#$config['nets'][] = "172.16.0.0/12";
#$config['nets'][] = "192.168.0.0/16";

# Update configuration
#$config['update_channel'] = 'release';  # uncomment to follow the monthly release channel
#$config['update'] = 0;  # uncomment to completely disable updates

# Fping Config
$config['fping'] = "/usr/sbin/fping";

# Oxidized Config
$config['oxidized']['enabled']         = TRUE;
$config['oxidized']['url']             = 'http://192.168.10.11:8888';
$config['oxidized']['features']['versioning'] = true;
$config['oxidized']['group_support'] = true;
$config['oxidized']['default_group'] = 'default';
```

Do I need to finish all the steps in that instruction ?

**Comment by ytti** [comment]
I don't personally use any NMS, including LibreNMS. So I can't unfortunately tell you exactly what you need to do, step by step. But I'm confident if you spend bit of time researching, reading and experimenting you are able to either get it working or arrive with specific question which is answerable.

I can tell you few things which might help

 1. The ```rest``` tells the IP address where web server listens, it is not your switch
 2. The ```router.db``` file lists your switches and routers, but you don't need it, if you implement LibreNMS integration, Oxidized will learn the switches and routers from LibreNMS.

**Comment by rongtler** [comment]
Thanks for the advice! 
I reread the instruction and change the `rest` to the IP 127.0.0.1:8888 then Oxidized operates smoothly. 
I still wonder why the server listens to the IP loopback in this case but I'll try to research more. The topic can be closed now.

**Comment by ytti** [comment]
The server listens on the IP you ask it to listen. If you want it to listen on your public IP, it will. But you asked it to listen on some IP address you didn't even have on your computer, that of course won't work.

**Comment by ytti** [comment]
To see what IP addresses you have ```ip -4 addr```
