### ISSUE TITLE
Oxidized crash

### ISSUE THREAD

**Issue by kaaaa44** [ytti/oxidized#1476]
Hello
Can you tell me, please, why my config crashing

Oxidized config
```
username: username
password: password
interval: 3600
use_syslog: true
debug: true
threads: 30
timeout: 120
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars:
  remove_secret: true
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
log: "/home/oxidized/.config/oxidized/log"
input:
  default: telnet, ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    repo: "/home/oxidized/.config/oxidized/default.git"
    debug: true
source:
  default: http
  debug: true
  http:
    url: http://127.0.0.1/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '1234566575756756756756756767567'
model_map:
  cisco: ios
  juniper: junos
```
Log file
```
D, [2018-07-31T13:18:27.488250 #23683] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at rs-4506-nnov-02.nnov.corp.local
D, [2018-07-31T13:18:27.488750 #23683] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet ran for rs-4506-nnov-02.nnov.corp.local successfully
D, [2018-07-31T13:18:27.488903 #23683] DEBUG -- : lib/oxidized/job.rb: Config fetched for rs-4506-nnov-02.nnov.corp.local at 2018-07-31 10:18:27 UTC
F, [2018-07-31T13:18:28.372054 #23683] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
```

Crash file

```
Invalid value; config files can only store string, bool or int keys [TypeError]
--------------------------------------------------
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:192:in `[]='
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:192:in `update_repo'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:170:in `update'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:57:in `store'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/worker.rb:54:in `process'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/worker.rb:16:in `block in work'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/worker.rb:16:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/worker.rb:16:in `work'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:36:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:28:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
```

**Comment by ytti** [comment]
You need to set user and email in git, if you had not done any git config, working one would have been created for you.

**Comment by kaaaa44** [comment]
Thanks!!
This worked fo me.

Add email address to oxidized config and it worked.
