### ISSUE TITLE
tmos.rb -- invalid byte sequence in UTF-8 [ArgumentError]

### ISSUE THREAD

**Issue by yzguy** [ytti/oxidized#1498]
```
invalid byte sequence in UTF-8 [ArgumentError]
--------------------------------------------------
/usr/lib/ruby/gems/2.4.0/gems/oxidized-0.24.0/lib/oxidized/model/tmos.rb:5:in `gsub!'
/usr/lib/ruby/gems/2.4.0/gems/oxidized-0.24.0/lib/oxidized/model/tmos.rb:5:in `block in <class:TMOS>'
/usr/lib/ruby/gems/2.4.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:111:in `instance_exec'
```

I believe it's throwing ArgumentError on the weird symbols in part of the config when running `tmsh -q show sys hardware field-fmt`

```
sys hardware hardware-version psu2 {
    model 73-610-125
    name psu2
    type psu
    versions.0.name Location
    versions.0.version 2
    versions.1.name Manufacturer
    versions.1.version ARTESYN��
    versions.2.name Revision
    versions.2.version A1
    versions.3.name Serial number
    versions.3.version ABC123
}
```

**Comment by ytti** [comment]
You can either change the model to fix that, or you can tell Oxidized not to expect UTF8 clean input by setting:

```
input:
  utf8_encoded: false
```

https://github.com/ytti/oxidized/blob/master/lib/oxidized/config.rb#L43

**Comment by yzguy** [comment]
That worked! Thank you. Very weird that weird characters come up in the config.
