### ISSUE TITLE
Latest Docker image is missing charlock_holmes installation

### ISSUE THREAD

**Issue by vowywowy** [ytti/oxidized#1531]
Nothing fancy in my oxidized setup. It was previously working and upon watchtower updating the image for my container it now says this:
```
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': libicuuc.so.60: cannot open shared object file: No such file or directory - /var/lib/gems/2.5.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes/charlock_holmes.so (LoadError)
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /var/lib/gems/2.5.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /var/lib/gems/2.5.0/gems/oxidized-web-0.11.1/lib/oxidized/web/webapp.rb:9:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /var/lib/gems/2.5.0/gems/oxidized-web-0.11.1/lib/oxidized/web.rb:10:in `initialize'
        from /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:26:in `new'
        from /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:26:in `initialize'
        from /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/cli.rb:12:in `run'
        from /var/lib/gems/2.5.0/gems/oxidized-0.24.0/bin/oxidized:8:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```
Even recreating the container from scratch with no additional config doesn't seem to help.
I'm guessing it has something to do with 5414cb61972c9c2957a5d69c0ad1fbc92ce1e260

**Comment by vowywowy** [comment]
If anyone else hits this, I was able to work around this with the following inside the container:
```
# apt-get install make build-essential libicu-dev
# gem install charlock_homes
```
Perhaps those packages should be added into the Dockerfile
