### ISSUE TITLE
key was 257 bytes (Expected 32) [RbNaCl::LengthError]

### ISSUE THREAD

**Issue by tomasell** [ytti/oxidized#1557]
Running Oxidized (v 0.24.0) on Ubuntu 18.04, I cannot connect to some devices. 

I'm using `net-ssh` gem (version 4.1.0 as required), but I've had to install `rbnacl` (version 40.2):

```
/var/lib/gems/2.5.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519_loader.rb:19:in `raiseUnlessLoaded': OpenSSH keys only supported if ED25519 is available (NotImplementedError)
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
```

Oxidized cannot cannot to devices, and this is the crash log file:
```
key was 257 bytes (Expected 32) [RbNaCl::LengthError]
--------------------------------------------------
/gems/rbnacl-4.0.2/lib/rbnacl/signatures/ed25519/verify_key.rb:33:in `initialize'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:25:in `new'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:25:in `initialize'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:128:in `new'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:128:in `initialize'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:152:in `new'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/ed25519.rb:152:in `read'
/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:113:in `block in classify_key'
/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:60:in `load_data_private_key'
/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:43:in `load_private_key'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:53:in `connect'
/gems/oxidized-0.24.0/lib/oxidized/node.rb:66:in `run_input'
/gems/oxidized-0.24.0/lib/oxidized/node.rb:43:in `block in run'
/gems/oxidized-0.24.0/lib/oxidized/node.rb:38:in `each'
/gems/oxidized-0.24.0/lib/oxidized/node.rb:38:in `run'
/gems/oxidized-0.24.0/lib/oxidized/job.rb:9:in `block in initialize'
```

**Comment by tomasell** [comment]
Adding:
```
vars:
  auth_methods: [ "keyboard-interactive", "password"]
```
it works.
