### ISSUE TITLE
Public key auth for groups

### ISSUE THREAD

**Issue by kingtriumph** [ytti/oxidized#1710]
I'm trying to get more information on configuring public key ssh authentication for device groups in oxidized. I've looked at the oxidized documentation as well as a few forum posts I've found semi-related to this topic, but I've not found anything that provides the correct syntax so far. 

Here is a portion of my oxidized config showing what I currently have for public key ssh authentication:
`groups: `
 `hp:`
    `username: user`
    `publickey: /home/oxidized/.ssh/id_rsa.pub`
    `privatekey: /home/oxidized/.ssh/id_rsa`
   ` vars:`
      `auth_methods: publickey`

And here is the output of one of the debug logs for a switch using public key authentication:

2019-02-22 21:29:18 UTC
Inappropriate ioctl for device [Errno::ENOTTY]
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `noecho'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `ask'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:66:in `rescue in load_data_private_key'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:59:in `load_data_private_key'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/key_factory.rb:43:in `load_private_key'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/input/ssh.rb:49:in `connect'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:65:in `run_input'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:42:in `block in run'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/job.rb:9:in `block in initialize'

I appreciate any assistance! Thanks.

**Comment by kingtriumph** [comment]
Okay, so I've got ssh authentication working with Oxidized. If others have this question in the future, here is what I've done to make it work:

1. Generated a rsa keypair and kept the default names of id_rsa and id_rsa.pub
2. Kept the keys in the oxidized user's ssh folder, /home/oxidized/.ssh/
3. Removed the `password` field from the device group in my oxidized config
4. Added the `vars: auth_method: publickey` field to the oxidized config
    * Note that the `publickey` and `privatekey` field I had in the snippet of my oxidized config in the original post are not necessary and I removed them from my config
5. Verified that the oxidized service is running under the oxidized user
6. Removed the passphrase from the private key in my keypair

Now, removing the passphrase is a less than ideal way to do things, however, I kept running into problems where my ssh agent would accept the key when added it via `ssh add` and entered the passphrase but would then forget the key soon afterwards. This would cause oxidized to fail when attempting to log into the devices that use ssh key authentication. I'm going to keep troubleshooting the problem with the passphrase because I don't want to leave the private key without it in the long term.
