### ISSUE TITLE
Oxidized Running as a Service - Tries to Enter Enable Mode

### ISSUE THREAD

**Issue by nsn-amagruder** [ytti/oxidized#1735]
I have oxidized running on CentOS 7.5.  It runs fine when you type oxidized.  Configs download okay.
Configuring it to run as a service runs okay, after some trial and error.  Any configuration that requires enable mode, the configs download.  The issue is when running as as service only, the devices that already put you in enable mode, oxidized keeps typing enable and failing.

Any thoughts as to why this only happens when running as a service and not when running from the command line?

**Comment by nsn-amagruder** [comment]
I found the issue.  Trying to get the service to run I was copying files all over the place and put a modified ios.rb file in another directory it was reading.  After changing it back to the default values, service starts and runs as expected.

2019-03-13 16:12:14 UTC
undefined method `gsub!' for #<Array:0x0000000003d93b38> [NoMethodError]
--------------------------------------------------
/etc/oxidized/model/ios.rb:112:in `block in <class:IOS>'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:114:in `instance_exec'
