### ISSUE TITLE
Missing dependencies for net-ssh

### ISSUE THREAD

**Issue by aneagoe** [ytti/oxidized#1742]
Running docker container version 0.25.1 fails with following error
```oxidized_1  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
oxidized_1  | *** Running /etc/my_init.d/10_syslog-ng.init...
oxidized_1  | Mar 15 13:32:11 4136e72fe801 syslog-ng[15]: syslog-ng starting up; version='3.13.2'
oxidized_1  | *** Booting runit daemon...
oxidized_1  | *** Runit started as PID 24
oxidized_1  | Mar 15 13:32:12 4136e72fe801 cron[33]: (CRON) INFO (pidfile fd = 3)
oxidized_1  | Mar 15 13:32:12 4136e72fe801 cron[33]: (CRON) INFO (Running @reboot jobs)
oxidized_1  | I, [2019-03-15T13:32:13.080593 #31]  INFO -- : Oxidized starting, running as pid 31
oxidized_1  | I, [2019-03-15T13:32:13.082018 #31]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
oxidized_1  | I, [2019-03-15T13:32:13.173443 #31]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
oxidized_1  | Puma starting in single mode...
oxidized_1  | * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
oxidized_1  | * Min threads: 0, max threads: 16
oxidized_1  | * Environment: development
oxidized_1  | * Listening on tcp://127.0.0.1:8888
oxidized_1  | Use Ctrl-C to stop
oxidized_1  | #<Oxidized::Job:0x000055deb4830db8@/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/job.rb:7 run> terminated with exception (report_on_exception is true):
oxidized_1  | /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded': OpenSSH keys only supported if ED25519 is available (NotImplementedError)
oxidized_1  | net-ssh requires the following gems for ed25519 support:
oxidized_1  |  * ed25519 (>= 1.2, < 2.0)
oxidized_1  |  * bcrypt_pbkdf (>= 1.0, < 2.0)
oxidized_1  | See https://github.com/net-ssh/net-ssh/issues/565 for more information
oxidized_1  | Gem::MissingSpecError : "Could not find 'ed25519' (~> 1.2) among 251 total gem(s)
oxidized_1  | Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information"
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:202:in `classify_key'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:53:in `load_data_private_key'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/input/ssh.rb:27:in `connect'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:67:in `run_input'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:44:in `block in run'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:38:in `each'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:38:in `run'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/job.rb:9:in `block in initialize'
oxidized_1  | /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/ed25519_loader.rb:21:in `raiseUnlessLoaded': OpenSSH keys only supported if ED25519 is available (NotImplementedError)
oxidized_1  | net-ssh requires the following gems for ed25519 support:
oxidized_1  |  * ed25519 (>= 1.2, < 2.0)
oxidized_1  |  * bcrypt_pbkdf (>= 1.0, < 2.0)
oxidized_1  | See https://github.com/net-ssh/net-ssh/issues/565 for more information
oxidized_1  | Gem::MissingSpecError : "Could not find 'ed25519' (~> 1.2) among 251 total gem(s)
oxidized_1  | Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information"
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:202:in `classify_key'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:53:in `load_data_private_key'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/key_factory.rb:44:in `load_private_key'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:85:in `block in authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `each'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/authentication/session.rb:71:in `authenticate'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:250:in `start'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/input/ssh.rb:27:in `connect'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:67:in `run_input'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:44:in `block in run'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:38:in `each'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:38:in `run'
oxidized_1  | 	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/job.rb:9:in `block in initialize'
oxidized_1  | I, [2019-03-15T13:32:16.657060 #43]  INFO -- : Oxidized starting, running as pid 43
oxidized_1  | I, [2019-03-15T13:32:16.658605 #43]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
oxidized_1  | I, [2019-03-15T13:32:16.748377 #43]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
oxidized_1  | Puma starting in single mode...
oxidized_1  | * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
oxidized_1  | * Min threads: 0, max threads: 16
oxidized_1  | * Environment: development
oxidized_1  | * Listening on tcp://127.0.0.1:8888
oxidized_1  | Use Ctrl-C to stop
```

Easily fixed by adding following dependencies to oxidized.gemspec:
```
diff --git a/oxidized.gemspec b/oxidized.gemspec
index b1f7ee5..230ebef 100644
--- a/oxidized.gemspec
+++ b/oxidized.gemspec
@@ -20,6 +20,8 @@ Gem::Specification.new do |s|
   s.required_ruby_version =           '>= 2.3'
   s.add_runtime_dependency 'asetus',  '~> 0.1'
   s.add_runtime_dependency 'net-ssh', '~> 5'
+  s.add_runtime_dependency 'bcrypt_pbkdf', '>= 1', '< 2'
+  s.add_runtime_dependency 'ed25519', '>= 1.2', '< 1.3'
   s.add_runtime_dependency 'net-telnet', '~> 0.2'
   s.add_runtime_dependency 'rugged',  '~> 0.28'
   s.add_runtime_dependency 'slop',    '~> 4.6'
```

**Comment by aneagoe** [comment]
PR fixed the issue, I could confirm after a docker pull.
