### ISSUE TITLE
updated to ruby23; systemd crashes 

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#1782]
Hello,

Just did an update on one of my oxidized servers to latest `0.26.3`
updated my service file
```
# /usr/lib/systemd/system/oxidized.service
#For debian 8 put it in /lib/systemd/system/
#and call it with systemctl start oxidized.service

[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=slapd.service network-online.target multi-user.target
Wants=network-online.target slapd.service

[Service]
ExecStart=/opt/rh/rh-ruby23/root/usr/local/bin/oxidized
User=config

[Install]
WantedBy=multi-user.target
```
but fails:
```
systemctl status oxidized
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/oxidized.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Mon 2019-04-22 20:36:36 UTC; 2min 54s ago
  Process: 14065 ExecStart=/opt/rh/rh-ruby23/root/usr/local/bin/oxidized --deamonize (code=exited, status=127)
 Main PID: 14065 (code=exited, status=127)

Apr 22 20:36:35 jpn-off-1se-ecr-1 systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Apr 22 20:36:36 jpn-off-1se-ecr-1 systemd[1]: oxidized.service: main process exited, code=exited, status=127/n/a
Apr 22 20:36:36 jpn-off-1se-ecr-1 systemd[1]: Unit oxidized.service entered failed state.
Apr 22 20:36:36 jpn-off-1se-ecr-1 systemd[1]: oxidized.service failed.
```

I can start the it as `config` user with no issues. configs are updated/pulled

```
[config@jpn-off-1se-ecr-1 ~]$ oxidized
Puma starting in single mode...
* Version 3.11.4 (ruby 2.3.8-p459), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9002
Use Ctrl-C to stop
```

I believe it has to do with the enviroment variables. Been trying to figure out how to set them but struggling...unless it is something else entirely

I did delete old `2.0` oxidized gem in `/usr/local/share/gems/gems/`.
Now all is under `/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/`

gem list (from ruby23)
```
gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.13.0)
bigdecimal (1.2.8)
bundler (default: 1.17.3)
charlock_holmes (0.7.6)
did_you_mean (1.0.0)
emk-sinatra-url-for (0.2.1)
ffi (1.10.0)
haml (5.0.4)
htmlentities (4.3.4)
io-console (0.4.5)
json (1.8.3.1)
multi_json (1.13.1)
net-ssh (5.2.0)
net-telnet (0.1.1)
oxidized (0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)
psych (2.1.0.1)
puma (3.11.4)
rack (1.6.11)
rack-protection (1.5.5)
rack-test (0.7.0)
rb-fsevent (0.10.3)
rb-inotify (0.10.0)
rdoc (4.2.1)
rubygems-update (3.0.3)
rugged (0.28.1)
sass (3.7.4)
sass-listen (4.0.0)
sequel (5.19.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
sqlite3 (1.4.0)
temple (0.8.1)
tilt (2.0.9)
```

from old gem 2.0.14.1
```
gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.11.3)
bcrypt_pbkdf (1.0.1)
bigdecimal (1.3.5)
charlock_holmes (0.7.6)
ed25519 (1.2.4)
emk-sinatra-url-for (0.2.1)
ffi (1.9.25)
haml (5.0.4)
htmlentities (4.3.4)
io-console (0.4.6)
json (2.1.0)
multi_json (1.13.1)
net-ssh (4.1.0)
net-telnet (0.1.1)
psych (2.0.0)
puma (3.11.4)
rack (1.6.4)
rack-protection (2.0.3)
rack-test (0.7.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (4.0.0)
temple (0.8.0)
tilt (2.0.9)
```

Any input would be appreciated!

Thank you,
Dave

**Comment by davama** [comment]
I thought i updated...

I ended up removing all other gems from 2.0.14.1 version
so only ruby23 gems are installed

**Comment by davama** [comment]
Fixed!

It was the ENV variables:

created:
```
cat /etc/sysconfig/oxidized 
LD_LIBRARY_PATH=/opt/rh/rh-ruby23/root/usr/local/lib64:/opt/rh/rh-ruby23/root/usr/lib64
```

and updated systemd file
```
systemctl cat oxidized
# /usr/lib/systemd/system/oxidized.service
blabla

[Service]
EnvironmentFile=/etc/sysconfig/oxidized
ExecStart=/opt/rh/rh-ruby23/root/usr/local/bin/oxidized
User=config

blabla
```

If want PR for this let me know
Thanks!

**Comment by ytti** [comment]
Sure what the PR would do, intuitively it looks like specific issue at local installation. Usually people us rbenv or rvm to manage ruby in creative locations and in those cases they have wrappers to ensure the environment works. It looks like here something is off if you require LD_LIBRARY_PATH.

**Comment by davama** [comment]
Thanks for the tip!
Ill look into it and report if anything different.
Thanks

**Comment by davama** [comment]
Update:

Probably some ENV issue with me. I had installed/updated using [Centos](https://github.com/ytti/oxidized#centos-oracle-linux-red-hat-linux) instructions but "alternatively" you can use [RVM](https://github.com/ytti/oxidized#installing-ruby-23-using-rvm). So went with RVM...

I probably wasnt using scl method properly since my setup was not stable. It would fail every now and then. Either way updated my systemd file

```
ExecStart=/usr/local/rvm/gems/ruby-2.3.8/wrappers/oxidized

``` 
and removed my previous EnviromentFile

Hopefully it is more stable.

**Comment by davama** [comment]
not sure if related to here or elsewhere but our servers is crashing constantly...not sure where to look

```
F, [2019-07-15T15:50:37.256256 #29171] FATAL -- : Oxidized crashed, crashfile written in /home/config/.config/oxidized/crash
F, [2019-07-15T15:51:34.509065 #29206] FATAL -- : Oxidized crashed, crashfile written in /home/config/.config/oxidized/crash
F, [2019-07-15T15:52:05.923210 #29230] FATAL -- : Oxidized crashed, crashfile written in /home/config/.config/oxidized/crash
F, [2019-07-15T17:04:49.362124 #30215] FATAL -- : Oxidized crashed, crashfile written in /home/config/.config/oxidized/crash
F, [2019-07-15T17:12:16.775508 #30591] FATAL -- : Oxidized crashed, crashfile written in /home/config/.config/oxidized/crash
F, [2019-07-15T17:19:14.326982 #30738] FATAL -- : Oxidized crashed, crashfile written in /home/config/.config/oxidized/crash
F, [2019-07-15T17:36:50.599020 #31108] FATAL -- : Oxidized crashed, crashfile written in /home/config/.config/oxidized/crash
```

```
cat /home/config/.config/oxidized/crash
--------------------------------------------------
2019-07-15 17:51:45 UTC
failed to insert entry: invalid object specified - aus-pr-2tc-ap-1 [Rugged::TreeError]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `write_tree'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `update_repo'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:160:in `update'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:57:in `store'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:65:in `process_success'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:47:in `process'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `block in work'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `work'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:36:in `run'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:29:in `initialize'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.8/bin/oxidized:23:in `load'
/usr/local/rvm/gems/ruby-2.3.8/bin/oxidized:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `<main>'
--------------------------------------------------
```
Our service file

```
[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=slapd.service network-online.target multi-user.target
Wants=network-online.target slapd.service

[Service]
ExecStart=/usr/local/rvm/gems/ruby-2.3.8/wrappers/oxidized
User=config
KillSignal=SIGKILL
Environment="OXIDIZED_HOME=/home/config/.config/oxidized"

[Install]
WantedBy=multi-user.target
```

Here is the crash log...interestingly that device does not exist on our DB...not sure why it is saying it is there. Not sure what to check.

Any input??

Thank you,
Dave

**Comment by davama** [comment]
I believe i found the issue.
Had to do with git. I believe some repos got corrupted somehow.
Fully not sure exactly why but redoing those repos from scratch makes oxidized stable again.
