### ISSUE TITLE
phpIPAM rest api as http source error

### ISSUE THREAD

**Issue by zombah** [ytti/oxidized#1839]
Hello, Im trying to use phpIPAM rest api response as http source for oxidized docker container, i expect it to work fine as issue #695 is resolved for nested json keys, but my attempt leads to this error in log:
```
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:53:in `block in string_navigate': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:52:in `each'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:52:in `string_navigate'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:29:in `block (2 levels) in load'
	from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:28:in `block in load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:23:in `each'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:23:in `load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `synchronize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `with_lock'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:125:in `initialize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
	from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```
Here is oxidized config:
```
username: test
password: test123
model: junos
resolve_dns: false
interval: 7200
# log is ignored if use_syslog is true
use_syslog: false
log: /root/.config/oxidized/log
debug: true
threads: 30
timeout: 30
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: true
vars:
  remove_secret: false
groups: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  utf8_encoded: true
output:
  default: git
  git:
    type_as_directory: true
    single_repo: false
    user: Oxidized
    email: oxidized@oxidized.example.com
    repo: "/root/.config/oxidized/devices/default.git"
source:
  default: http
  http:
    url: https://phpipam.example.com/api/apikey/tools/device_types/17/devices
    scheme: https
    delimiter: !ruby/regexp /:/
    user: false
    map:
      name: data.hostname
      model: data.custom_OS
      group: data.custom_group
      ip: data.ip
    headers:
      X-Auth-Token: ‘token’
```
And here is output from phpIPAM rest api via curl call:
```
curl -X GET https://phpipam.example.com/api/apikey/tools/device_types/17/devices -i --header 'token: token’
``` 
```
{"code":200,"success":true,"data":[{"id":"2","hostname”:”router-ios-1.example.com”,”ip”:”10.0.0.1”,”type":"17","description”:”Router ios oxidized test”,”sections":"4;5;6","snmp_community”:”test”,”snmp_version":"0","snmp_port":"161","snmp_timeout":"1000","snmp_queries":"get_system_info;get_arp_table;get_mac_table;get_interfaces_ip;get_vlan_table;get_vrf_table","rack":"5","rack_start":"8","rack_size":"7","location":"1","editDate":"2019-06-14 17:41:24","snmp_v3_sec_level":"none","snmp_v3_auth_protocol":"none","snmp_v3_auth_pass":null,"snmp_v3_priv_protocol":"none","snmp_v3_priv_pass":null,"snmp_v3_ctx_name":null,"snmp_v3_ctx_engine_id":null,"custom_OS":"ios","custom_group":"router-cisco"}],"time":0.006}
```

**Comment by nidebr** [comment]
Hi @zombah,

try in your config file to add "hosts_location" like that : 

```
source:
  default: http
  http:
    url: https://phpipam.example.com/api/apikey/tools/device_types/17/devices
    hosts_location: data
    scheme: https
    delimiter: !ruby/regexp /:/
    user: false
    map:
      name: hostname
      model: custom_OS
      group: custom_group
      ip: ip
    headers:
      X-Auth-Token: ‘token’
```

**Comment by zombah** [comment]
Hello @nidebr,
Thanks i tried but this way it causes diffrent error, tried with latest docker image:
```
Apr 20 23:55:16 b667542fac98 oxidized[52]: Oxidized starting, running as pid 52
Apr 20 23:55:16 b667542fac98 oxidized[52]: lib/oxidized/nodes.rb: Loading nodes
Apr 20 23:55:16 b667542fac98 oxidized[52]: Oxidized crashed, crashfile written in /root/.config/oxidized/crash
undefined method `each' for nil:NilClass
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:23:in `load': undefined method `each' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `synchronize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `with_lock'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:125:in `initialize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/cli.rb:13:in `run'
	from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/bin/oxidized:8:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

**Comment by glaubway** [comment]
Hello, have the same problem.
oxidized 0.28

```
--------------------------------------------------
2020-05-29 14:15:31 UTC
undefined method `each' for nil:NilClass [NoMethodError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:23:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```
If curl use curl request:
```
curl  --header "token: token" -X GET https://example.com/api/oxi/devices/1
```
Result:
```
{"code":200,"success":true,"data":{"id":"1","hostname":"sw0","ip":"x.x.x.x","type":"2","description":null,"sections":null,"snmp_community":null,"snmp_version":"0","snmp_port":"161","snmp_timeout":"1000","snmp_queries":null,"snmp_v3_sec_level":"none","snmp_v3_auth_protocol":"none","snmp_v3_auth_pass":null,"snmp_v3_priv_protocol":"none","snmp_v3_priv_pass":null,"snmp_v3_ctx_name":null,"snmp_v3_ctx_engine_id":null,"rack":"0","rack_start":"0","rack_size":"0","location":"0","editDate":"2020-05-29 15:09:18","custom_os":"vrp","custom_group":"huawei","custom_enable":"nil"},"time":0.006}
```
Source config:
```
  default: http
  http:
    url: https://example.com/api/oxi/devices/1
    scheme: https
    hosts_location: data
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      ip: ip
      model: custom_os
      group: custom_group
    vars_map:
       enable: custom_enable
    headers:
       token: 'token'
```
