### ISSUE TITLE
 source returns no usable nodes (Oxidized::Core::NoNodesFound)

### ISSUE THREAD

**Issue by NatalNW** [ytti/oxidized#1848]
I have seen other issues like this, but no one help me to solve this problem. Is my first time that I'm try to do oxidized deploy.

```
source returns no usable nodes
Traceback (most recent call last):
        8: from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
        7: from /usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        6: from /usr/local/rvm/gems/ruby-2.6.3/bin/oxidized:23:in `<main>'
        5: from /usr/local/rvm/gems/ruby-2.6.3/bin/oxidized:23:in `load'
        4: from /usr/local/rvm/gems/ruby-2.6.3/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
        3: from /usr/local/rvm/gems/ruby-2.6.3/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
        2: from /usr/local/rvm/gems/ruby-2.6.3/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        1: from /usr/local/rvm/gems/ruby-2.6.3/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.6.3/gems/oxidized-0.26.3/lib/oxidized/core.rb:15:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
```

Follow my config file:

```YMAL
---
interval: 86400
use_syslog: false
debug: true
threads: 30
timeout: 80
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars:
  remove_secret: true
groups: {}
models: {}
log: "/etc/oxidized/log"
pid: "/etc/oxidized/pid"
stats:
  history_size: 15
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  file:
    directory: /var/lib/oxidized/configs
source:
  default: sql
  sql:
      adapter: mysql2
      database: oxidized
      table: nodes
      query:  "SELECT * FROM nodes WHERE backup = 1;"
      user: root
      password: ********
      map:
        ip: ip
        name: name
        model: model
        group: group
        username: username
        password: password
      vars_map:
        backup: backup
```

**Comment by NatalNW** [comment]
This happened becouse of two errors of mine. First, there was no nodes in my database, and second, after a create some "false nodes", the models was dont accepted by oxidized to do backup. To conclude, was just user problems.
