### ISSUE TITLE
Please allow non zero exit codes on non debug execution

### ISSUE THREAD

**Issue by deajan** [ytti/oxidized#1929]
Hello,

Using oxidized as service, when the service fails, the exit code stays 0 unless --debug is used.
I triggered a voluntary error to show the issue:

eg standard run:
```
[oxidized@supervision oxidized]$ oxidized
I, [2019-10-08T16:35:39.270186 #10536]  INFO -- : Oxidized starting, running as pid 10536
I, [2019-10-08T16:35:39.304077 #10536]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2019-10-08T16:35:39.308010 #10536] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
[oxidized@supervision oxidized]$ echo $?
0
```

debug run
```
[oxidized@supervision oxidized]$ oxidized --debug
I, [2019-10-08T16:35:30.463054 #10481]  INFO -- : Oxidized starting, running as pid 10481
I, [2019-10-08T16:35:30.497467 #10481]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2019-10-08T16:35:30.501791 #10481] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
Traceback (most recent call last):
        20: from /usr/local/bin/oxidized:23:in `<main>'
        19: from /usr/local/bin/oxidized:23:in `load'
        18: from /usr/local/share/gems/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
        17: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
        16: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        15: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        14: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `initialize'
        13: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `new'
        12: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:125:in `initialize'
        11: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:10:in `load'
        10: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `with_lock'
         9: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `synchronize'
         8: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:15:in `block in load'
         7: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:21:in `load'
         6: from /usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:74:in `read_http'
         5: from /usr/share/ruby/net/http.rb:1458:in `request'
         4: from /usr/share/ruby/net/http.rb:909:in `start'
         3: from /usr/share/ruby/net/http.rb:920:in `do_start'
         2: from /usr/share/ruby/net/http.rb:985:in `connect'
         1: from /usr/share/ruby/net/protocol.rb:44:in `ssl_socket_connect'
/usr/share/ruby/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) (OpenSSL::SSL::SSLError)
[oxidized@supervision oxidized]$ echo $?
1
```

Could you please have the exit code reflect the actual result of the run ?

Best regards.

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/bin/oxidized#L12

After this line add ```exit 1``` should do the trick

**Comment by deajan** [comment]
Brilliant !
My systemd unit file is now capable of restarting oxidized upon failure (which basically happens when running with a http source that doesn't yet list hosts).

Do you mind this `exit 1` being added to the master branch ?
