### ISSUE TITLE
Oxidized randomly crashes 

### ISSUE THREAD

**Issue by kastu707** [ytti/oxidized#1957]
Hi team, 

Oxidized have been working fine for us for few months already. We changed infrastructure lately and moved the VM from HyperV to VMWare. I'm not sure that's so relevant but this is only change since we build Oxidized to backup and check our network confs. 
Most of time Oxidized is running just fine and it doing the job, but it crashes randomly and I don't understand why... Here's the latest crash: 
```

--------------------------------------------------
[oxidized@oxidized ~]$ sudo cat .config/oxidized/crash
--------------------------------------------------
2019-10-31 05:04:48 UTC
Input/output error @ io_writev - <STDOUT> [Errno::EIO]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/events.rb:67:in `write'
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/events.rb:67:in `puts'
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/events.rb:67:in `log'
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/runner.rb:30:in `log'
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/single.rb:35:in `stop_blocked'
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/launcher.rb:292:in `graceful_stop'
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/puma/launcher.rb:190:in `run'
/usr/local/rvm/gems/ruby-2.5.1/gems/puma-3.12.0/lib/rack/handler/puma.rb:70:in `run'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-web-0.11.1/lib/oxidized/web.rb:29:in `block in run'
--------------------------------------------------

```
Thanks a lot for your insights and help!
K.

**Comment by kastu707** [comment]
Hey guys! 
Any clue on this? 

Thanks :)
