### ISSUE TITLE
Problem configuring http as source with librenms, argument retrieval error ?

### ISSUE THREAD

**Issue by mmisslin** [ytti/oxidized#2012]
Hi and thank you for all the work done here.

I can't manage to configure Oxidized to work with librenms api as a source.
When starting Oxidized I get the following error : 
```
 /usr/lib/ruby/2.5.0/resolv.rb:1219:in `create': cannot interpret as DNS name: nil (ArgumentError)
```
Here is my config file : 
 
```
---
 username: username
 password: password
 model: junos
 resolve_dns: true
 interval: 3600
 log: "/etc/oxidized/log"
 debug: true
 threads: 30
 timeout: 20
 retries: 3
 prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
 rest: 127.0.0.1:8888
 next_adds_job: false
 vars:
   remove_secret: true
   ssh_keys: "/etc/oxidized/.ssh/id_rsa"
 groups: {}
 models:
   junos:
     username: XXX
   powerconnect:
     username: XXX
     vars:
       enable: XXX
   os10:
     username: XXX
 pid: "/etc/oxidized/pid"
 crash:
   directory: "/etc/oxidized/crashes"
   hostnames: false
 stats:
   history_size: 10
 input:
   default: ssh, telnet
   debug: false
   ssh:
     secure: false
   ftp:
     passive: true
   utf8_encoded: false
 output:
   default: git
   git:
     single_repo: true
     user: XXX
     email: XXX
     repo: "/etc/oxidized/output/oxidized.git"
 source:
   default: http
   debug: true
   http:
     url: http://XXX/api/v0/oxidized
     scheme: http
     delimiter: !ruby/regexp /:/
   map:
     name: hostname
     model: os
   headers:
     X-Auth-Token: 'XXX'
 hooks:
   push_to_remote:
     type: githubrepo
     events:
     - post_store
     remote_repo: XXX@XXX/oxidized.git
     publickey: "/etc/oxidized/.ssh/id_rsa.pub"
     privatekey: "/etc/oxidized/.ssh/id_rsa"
   email_output:
     type: exec
     events:
     - post_store
     - node_fail
     cmd: '/var/lib/gems/2.5.0/gems/oxidized-0.27.0/extra/oxidized-report-git-commits
       | mail -s "Oxidized updates for ${OX_NODE_NAME}" XXX@XXX'
     async: true
     timeout: 120
```

When testing the librenms api i get the following return :
```
curl -H 'X-Auth-Token: XXX' http://XXX/api/v0/oxidized

[
    {
        "hostname": "cds-asd-fc-sw1",
        "os": "dell-os10",
        "ip": "10.30.10.31"
    },
...
    {
        "hostname": "s05-3300-b1",
        "os": "junos",
        "ip": "10.30.10.30"
    }
]
```

Here is the full return when issuing the "oxidized" command:

```
$ oxidized
 cannot interpret as DNS name: nil
 Traceback (most recent call last):
         26: from /usr/local/bin/oxidized:23:in `<main>'
         25: from /usr/local/bin/oxidized:23:in `load'
         24: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/bin/oxidized:8:in `<top (required)>'
         23: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/cli.rb:13:in `run'
         22: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
         21: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
         20: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `initialize'
         19: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `new'
         18: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:125:in `initialize'
         17: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:10:in `load'
         16: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `with_lock'
         15: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `synchronize'
         14: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:16:in `block in load'
         13: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:16:in `each'
         12: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:21:in `block (2 levels) in load'
         11: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:21:in `new'
         10: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:19:in `initialize'
          9: from /usr/lib/ruby/2.5.0/resolv.rb:93:in `getaddress'
          8: from /usr/lib/ruby/2.5.0/resolv.rb:115:in `each_address'
          7: from /usr/lib/ruby/2.5.0/resolv.rb:115:in `each'
          6: from /usr/lib/ruby/2.5.0/resolv.rb:116:in `block in each_address'
          5: from /usr/lib/ruby/2.5.0/resolv.rb:406:in `each_address'
          4: from /usr/lib/ruby/2.5.0/resolv.rb:509:in `each_resource'
          3: from /usr/lib/ruby/2.5.0/resolv.rb:519:in `fetch_resource'
          2: from /usr/lib/ruby/2.5.0/resolv.rb:1088:in `resolv'
          1: from /usr/lib/ruby/2.5.0/resolv.rb:1059:in `generate_candidates'
/usr/lib/ruby/2.5.0/resolv.rb:1219:in `create': cannot interpret as DNS name: nil (ArgumentError)
```

A look at the log files:

```
I, [2020-01-09T12:08:47.143914 #41424]  INFO -- : Oxidized starting, running as pid 41424
D, [2020-01-09T12:08:47.144465 #41424] DEBUG -- : Hook "push_to_remote" registered GithubRepo for event :post_store
D, [2020-01-09T12:08:47.144970 #41424] DEBUG -- : Hook "email_output" registered Exec for event :post_store
D, [2020-01-09T12:08:47.145084 #41424] DEBUG -- : Hook "email_output" registered Exec for event :node_fail
I, [2020-01-09T12:08:47.175068 #41424]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2020-01-09T12:08:47.195503 #41424] DEBUG -- : resolving DNS for ...
D, [2020-01-09T12:08:47.195555 #41424] DEBUG -- : IPADDR 
F, [2020-01-09T12:08:47.195842 #41424] FATAL -- : Oxidized crashed, crashfile written in /etc/oxidized/.config/oxidized/crash
```

It seems to me that the arguments from the API aren't properly passed into Oxidized but I don't know to fix this.

**Comment by mmisslin** [comment]
My bad, this was due to a YAML syntax error (missing spaces).

The "source" section should look as follow :

```
source:
  default: http
  debug: true
  http:
    url: http://XXX/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      ip: ip
    headers:
      X-Auth-Token: 'XXX'
```
