### ISSUE TITLE
Error message when using search function

### ISSUE THREAD

**Issue by sliddjur** [ytti/oxidized#2018]
I cannot use the search function in oxidized to search within the configuration

My setup is a ubuntu 18.04 vm, and I installed apt packages per instructions in the readme. The current oxidized versions are: 
```
sliddjur@librenms:/etc/oxidized$ gem list | grep oxidized
oxidized (0.27.0, 0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)
```

My oxidized config file:
```
---
interval: 3600
use_syslog: true
threads: 30
timeout: 20
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
groups:
  router1:
    username: oxidized
    vars:
      ssh_keys: "~/.ssh/id_rsa"
  router2:
    username: user2
    password: pass2

model_map:
  cisco: ios
  vyos: vyatta
  ciscosb: ciscosmb
vars: {}
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false

source:
  default: http
  debug: true
  http:
    url: https://librenms/api/v0/oxidized
    scheme: http
    delimeter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'xxx'

output:
  default: git
  git:
    user: 'user'
    email: 'asdf@example.com'
    single_repo: true
    repo: "/etc/oxidized/configs-git/"
```

The git output is saved with oxidized user, and files have permission 644.
The source is LibreNMS, all devices are put into groups.

This is the error message when I try to search:

```
sliddjur@librenms:/etc/oxidized$ curl http://127.0.0.1:8888/nodes/conf_search?format=json -d 'search_in_conf_textbox=vlan'
NoMethodError: undefined method `output' for nil:NilClass
	/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:176:in `block in yield_node_output'
	/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `synchronize'
	/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `with_lock'
	/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:174:in `yield_node_output'
	/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:62:in `fetch'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:56:in `block (2 levels) in <class:WebApp>'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:54:in `map'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:54:in `each'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:54:in `block in <class:WebApp>'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.12/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.12/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.12/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-1.6.12/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.5.0/gems/rack-1.6.12/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.12/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

And from oxidized GUI:
![image](https://user-images.githubusercontent.com/10002057/72788620-7f4cea80-3c32-11ea-8aca-c5eb11fc7920.png)

**Comment by sliddjur** [comment]
An update to this,

I get my routers from librenms api.
I discovered that when I ignore my `procurve` devices from getting into oxidized, the search functionality will work.
LibreNMS `config.php` file
`$config['oxidized']['ignore_os'] = array('procurve')`

So I have a few hundred procurve devices, and all of them that are fed from LibreNMS have a hostname, os, ip and a group field.
I cannot see any difference of devices in other os-groups coming from LibreNMS.

- all hosts but 3 are added by hostname - none of those are os:procurve
- all hosts but 3 have ip fields - none of those are os:procurve
- all hostnames are unique
- all procurve have hostname, ip, group and os field

**Comment by sliddjur** [comment]
I found the issue.

One of the procurve switches had a trailing `.` in the `name` field from LibreNMS.
