### ISSUE TITLE
undefined method error for Adtran on 0.27

### ISSUE THREAD

**Issue by ja-frog** [ytti/oxidized#2044]
The Adtran model is failing for me on version 0.27. May be associated with #2031 . Logs below.

Crash log:
undefined method `+' for nil:NilClass [NoMethodError]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/input/ssh.rb:102:in `cmd_shell'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/input/ssh.rb:48:in `cmd'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/model/adtran.rb:20:in `block (2 levels) in <class:Adtran>'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/input/cli.rb:26:in `block in connect_cli'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/input/cli.rb:24:in `each'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/input/cli.rb:24:in `connect_cli'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/input/cli.rb:13:in `get'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/node.rb:67:in `run_input'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/node.rb:44:in `block in run'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/node.rb:38:in `each'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/node.rb:38:in `run'
/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/job.rb:9:in `block in initialize'

Syslog(I have debug set to true in the config. Not certain that this is right output.):
Mar  9 15:34:25 centos8template oxidized[22761]: Oxidized starting, running as pid 22761
Mar  9 15:34:25 centos8template oxidized[22761]: lib/oxidized/nodes.rb: Loading nodes
Mar  9 15:34:25 centos8template oxidized[22761]: lib/oxidized/nodes.rb: Loaded 1 nodes
Mar  9 15:34:28 centos8template oxidized[22761]: negotiating protocol version
Mar  9 15:34:28 centos8template oxidized[22761]: sending KEXINIT
Mar  9 15:34:28 centos8template oxidized[22761]: got KEXINIT from server
Mar  9 15:34:28 centos8template oxidized[22761]: negotiating algorithms
Mar  9 15:34:30 centos8template oxidized[22761]: channel_open_confirmation: 0 0 32768 32768
Mar  9 15:34:30 centos8template oxidized[22761]: sending channel request "pty-req"
Mar  9 15:34:30 centos8template oxidized[22761]: channel_success: 0
Mar  9 15:34:30 centos8template oxidized[22761]: sending channel request "shell"
Mar  9 15:34:31 centos8template oxidized[22761]: channel_success: 0
Mar  9 15:34:31 centos8template oxidized[22761]: channel_data: 0 2b
Mar  9 15:34:31 centos8template oxidized[22761]: channel_data: 0 13b
Mar  9 15:34:31 centos8template oxidized[22761]: 172.30.4.26 raised NoMethodError with msg "undefined method `+' for nil:NilClass", 172.30.4.26 saved
Mar  9 15:34:32 centos8template oxidized[22761]: /osk10ts01.mahaska.org status no_connection, retry attempt 1

**Comment by ja-frog** [comment]
I played around a little bit and found that a revision of the adtran model was needed. I will put together a pull request with the updated variant.
