### ISSUE TITLE
ArgumentError - wrong number of arguments Git Repo

### ISSUE THREAD

**Issue by doublejz** [ytti/oxidized#2064]
ArgumentError - wrong number of arguments, wrong number of arguments (given 0, expected 1+). 
file: versions.haml location: count line: 24

```
[root@oxidized devices.git]# oxidized -v
0.27.0
[root@oxidized devices.git]#

```

```
[root@oxidized oxidized]# cd .config/oxidized/devices.git/
[root@oxidized devices.git]# git ls-files
192.168.1.1
192.168.1.4
[root@oxidized devices.git]# git log
commit d1a730881838a1c9e1fdea8184f4bb2ae7fe749d
Author: oxidized <email>
Date:   Wed Apr 8 21:24:31 2020 -0400

    update /192.168.1.4

commit de469bffe546eb4ebce99c858e318559a72ace69
Author: oxidized <email>
Date:   Wed Apr 8 21:23:04 2020 -0400

    update /192.168.1.1

commit ff447112b65eccb4c5d6e345c5ac4c3afdc61afa
Author: oxidized <omitted>
Date:   Wed Apr 8 21:05:51 2020 -0400

    update /192.168.1.1

commit 598104f1320c341ca93a0402513983787c51aaf3
Author: oxidized <omitted>
Date:   Wed Apr 8 21:05:42 2020 -0400

    update /192.168.1.1

commit c9201b6f4da50a309765989117c6211f7b2f35bc
Author: oxidized <omitted>
Date:   Wed Apr 8 21:03:53 2020 -0400

    update /192.168.1.1

commit ea8ac3c39bdf505124355deba1d278d1a5ead5b7
Author: oxidized <omitted>
Date:   Wed Apr 8 21:03:45 2020 -0400

    update /192.168.1.1

commit 91775b22a9dbe34565d6ae3f09706d485cefbde2
Author: oxidized <omitted>
Date:   Wed Apr 8 21:03:37 2020 -0400

    update /192.168.1.1

commit 9957938a7071c007473544c21036a4eb203dfa6a
Author: oxidized <omitted>
Date:   Wed Apr 8 21:01:59 2020 -0400

    update /192.168.1.4

commit 122c2deae2d23e33da099bccbf554cc549e551d9
Author: oxidized <omitted>
Date:   Wed Apr 8 20:59:50 2020 -0400

    update /192.168.1.1
[root@oxidized devices.git]#
```

```
[root@oxidized devices.git]# curl http://192.168.1.226:8888/node/version
NoMethodError: undefined method `include?' for nil:NilClass
        /usr/local/rvm/gems/ruby-2.7.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:156:in `block in <class:WebApp>'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /usr/local/rvm/gems/ruby-2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
        /usr/local/rvm/gems/ruby-2.7.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
        /usr/local/rvm/gems/ruby-2.7.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
        /usr/local/rvm/gems/ruby-2.7.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
        /usr/local/rvm/gems/ruby-2.7.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

```
[root@oxidized devices.git]# cat /home/oxidized/.config/oxidized/config
username: username
password: password
model: fortigate
resolve_dns: false
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.1.226:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10

input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true

output:
  default: git
  git:
    user: oxidized
    email: email
    repo: "/home/oxidized/.config/oxidized/devices.git"

source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  fortigate: fortios
  catos: catos
  faz: faz
[root@oxidized devices.git]#
```

www.doublejz.com/images/forums/oxidized/ArgErr.jpg

**Comment by doublejz** [comment]
Found [d96a592](https://github.com/ytti/oxidized/commit/d96a592be605149f8a4f8d45e8b35e1ed8f3049c)
