### ISSUE TITLE
Version 0.28.0 - dir_s_mkdir - ~

### ISSUE THREAD

**Issue by jacp9** [ytti/oxidized#2147]
Hi,
Oxidized seems to crash every now and then (random) with the below written into crash dump. 
Seems like its trying to create ~ directory? Any idea how that can be resolved?
It is running as dedicated service user on centos 7.9.

```
--------------------------------------------------
2020-07-09 12:33:40 UTC
Permission denied @ dir_s_mkdir - ~ [Errno::EACCES]
--------------------------------------------------
/opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:254:in `mkdir'
/opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:254:in `fu_mkdir'
/opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:228:in `block (2 levels) in mkdir_p'
/opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:226:in `reverse_each'
/opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:226:in `block in mkdir_p'
/opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:211:in `each'
/opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:211:in `mkdir_p'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/node.rb:80:in `rescue in run_input'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/node.rb:66:in `run_input'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
--------------------------------------------------
```

**Comment by jacp9** [comment]
Whatever it was is now fixed after reorganising oxidized directories - something likely related to permissions.
