### ISSUE TITLE
Debian 10 with ruby 2.5 support

### ISSUE THREAD

**Issue by bigtrodat** [ytti/oxidized#2183]
Hi, 
I have installed oxidized 0.28.0 in a recent Debian 10 (with build in ruby 2.5). When starting oxidized I get following error:
```
oxidized@SERVER:~$ oxidized -d
I, [2020-09-11T09:46:46.439239 #23445]  INFO -- : Oxidized starting, running as pid 23445
D, [2020-09-11T09:46:46.440440 #23445] DEBUG -- : Hook "push_to_remote" registered GithubRepo for event :post_store
I, [2020-09-11T09:46:46.490969 #23445]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-09-11T09:46:46.525637 #23445] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
```

and crashfile shows
```
2020-09-11 07:46:46 UTC
no implicit conversion of String into Integer [TypeError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:53:in `block in string_navigate'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:52:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:52:in `string_navigate'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:29:in `block (2 levels) in load'
/var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:28:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:23:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:23:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

I guess the reason for this error is, that oxidized only supports ruby 2.3 and not 2.5. Correct?
Is there a way to install ruby 2.3 in a recent Debian 10?
As an alternative solution path: Has anybody experience running oxidized in an Kubernetes container?

Thanks a million for your support!
Best
Daniel

**Comment by wk** [comment]
Hi!

Oxidized has been tested to successfully run with Ruby 2.5, Ruby 2.3 is the minimal version supported.

The error above suggests some form of a configuration error, potentially relating to configuring an HTTP source as part of an effort to integrate Oxidized with an external system. You might be able to receive further assistance if you include the configuration leading to this error.
