### ISSUE TITLE
 undefined method `default' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by fiast** [ytti/oxidized#2252]
Hello, i have installed oxidized 0.28.0  in ubuntu 18.0
```
uname -a
Linux zabbix 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

when i start oxidized i have got an error
```
oxidized@zabbix:~/oxidized$ oxidized
undefined method `default' for nil:NilClass
Traceback (most recent call last):
        12: from /usr/local/bin/oxidized:23:in `<main>'
        11: from /usr/local/bin/oxidized:23:in `load'
        10: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
         9: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
         8: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
         7: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
         6: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
         5: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
         4: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
         3: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
         2: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
         1: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:12:in `block in load': undefined method `default' for nil:NilClass (NoMethodError)
```

my config is 

```
oxidized@zabbix:~/oxidized$ cat ~/.config/oxidized/config
username: test
password: test
model: routeros
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
log: "/home/oxidized/.config/oxidized/log"
crash:
directory: "/home/oxidized/.config/oxidized/crashes"
hostnames: false
stats:
history_size: 10
input:
default: ssh
debug: true
ssh:
secure: false
map:
verify_host_key: never
utf8_encoded: true
output:
default: git
git:
user: oxidized
email: 79132465097@yandex.ru
repo: "/home/oxidized/.config/oxidized/oxidized.git"
git:
user: oxidized
email: 79132465097@yandex.ru
repo: "/home/oxidized/.config/oxidized/devices/devices.git"
source:
default: csv
csv:
file: "/home/oxidized/.config/oxidized/mikrotik/router.db"
delimiter: !ruby/regexp /:/
map:
name: 0
model: 1
ip: 2
port: 3
username: 4
password: 5

model_map:
#cisco: ios
#juniper: junos
mikrotik: routeros

```

router.db
```
oxidized@zabbix:~/oxidized$ cat ~/.config/oxidized/mikrotik/router.db
ul7_gw01:routeros:10.11.10.10:22222:oxidized:
```

How to solve this error?

**Comment by pjes1** [comment]
I have similar error:
/var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:43:in `method_missing': undefined method `[]' for nil:NilClass (NoMethodError)

Unlike you, I have git:
`output:
  default: git
  git:
    user: oxidized
    email: servis@ucm.sk
    directory: "/srv/oxidized/configs/devices.git"`

Everything was working when I had output file.

**Comment by antonsukhanov** [comment]
Maybe it will be useful for somebody.

I solved this issue after adding a group to a router in the router.db file.

config:
![image](https://user-images.githubusercontent.com/9820700/185371728-1dd27810-38c7-4e96-a2cd-321da24b19ef.png)

router.db:
![image](https://user-images.githubusercontent.com/9820700/185371834-8369cbb3-2f1e-4006-bc7c-74fd9dfcf260.png)
