### ISSUE TITLE
Librenms and Cisco issue

### ISSUE THREAD

**Issue by Zyzto** [ytti/oxidized#2293]
I have an issue where only IOS Cisco devices error oxidized when trying to pull config through LibreNMS+Oxidized. the error on oxidized logs

after I added the device I cound't find it on webgui on oxidized and the jobs count I see it's missing my IOS cisco devices noting that IOSXE works just fine and every other type work just fine

LOG
```
D, [2021-04-21T23:02:03.952186 #26] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 7
D, [2021-04-21T23:02:04.952613 #26] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 7
D, [2021-04-21T23:02:05.953347 #26] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 7
2021-04-21 23:02:06 - Oxidized::NodeNotFound - unable to find '10.100.100.101':
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:95:in `find_node_index'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:56:in `block in show'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:55:in `show'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:118:in `block in <class:WebApp>'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2021-04-21 23:02:06 - Oxidized::NodeNotFound - unable to find '10':
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:95:in `find_node_index'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:56:in `block in show'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:55:in `show'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:118:in `block in <class:WebApp>'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2021-04-21 23:02:06 - NoMethodError - undefined method `output' for nil:NilClass:
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:176:in `block in yield_node_output'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:174:in `yield_node_output'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:99:in `version'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:163:in `block in <class:WebApp>'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2021-04-21 23:02:06 - NoMethodError - undefined method `output' for nil:NilClass:
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:176:in `block in yield_node_output'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:174:in `yield_node_output'
	/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:62:in `fetch'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:82:in `block in <class:WebApp>'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
D, [2021-04-21T23:02:06.954009 #26] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 7
```

since it can't even detect the node config I don't think the config matter

and I don't see it on oxidized so there's no point of assign group in custom.config.php in librenms, but I tried it and didn't work

**Comment by chalarm** [comment]
https://docs.librenms.org/Extensions/Oxidized/

**Comment by Zyzto** [comment]
I found the solution, for some reason it didn't add it cause the os name was ciscosb and oxidized didn't want to add it. So I just mapped it to another os. Though the logs are confusing.
