### ISSUE TITLE
NoMethodError at /node/version

### ISSUE THREAD

**Issue by kefiras** [ytti/oxidized#230]
Hello,
I am getting the error upon trying to get 'version' of the device. Local URL:
http://localhost:8888/node/version?node_full=10.15.15.22
I am using Ubuntu 15.04 with kernel 3.19.0-26-generic with ruby 1.9.3 installed from RVM.
Thanks for help on this

```
2015-10-27 12:49:15 - NoMethodError - undefined method `version' for #<Oxidized::OxidizedFile:0x007fd5ec4a7738>:
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/oxidized-0.8.1/lib/oxidized/nodes.rb:159:in `block in version'
    <internal:prelude>:10:in `synchronize'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/oxidized-0.8.1/lib/oxidized/nodes.rb:110:in `with_lock'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/oxidized-0.8.1/lib/oxidized/nodes.rb:155:in `version'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/oxidized-web-0.5.1/lib/oxidized/web/webapp.rb:145:in `block in <class:WebApp>'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
    /home/wojtas/.rvm/gems/ruby-1.9.3-p551/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by ytti** [comment]
Version is actually version of the config, it's right now only implemented for 'git' output. You're running 'file' output which does not have it implemented and it's crashing. Clearly a bug, clearly it should gracefully fail. But that's the bottom line.

I'm not sure what 'version' could mean for file? Perhaps it could date of the file, but that always changes, we always overwrite the file, without caring what was there before...

**Comment by cchance27** [comment]
ya this caught me off guard i thought file would work with versioning, but switching to git fixes that issue

**Comment by ytti** [comment]
We're now giving empty version for 'file', perhaps better than nothing. Certainly better than crash.

**Comment by cchance27** [comment]
Silly question but why not just serve the standard version page but with
only the 1 version available with maybe a footer that says versioning
disabled in file mode

**Comment by ytti** [comment]
I'm happy to accept pull request for such. I've pretty much not ran anything by now on oxidized-web part. So what ever behaviour users want, implement it, and I'll accept PR.
