### ISSUE TITLE
crash on startup "Is a directory @ rb_sysopen - /home/oxidized/.config/oxidized/crashes/"

### ISSUE THREAD

**Issue by clontarfx** [ytti/oxidized#2308]
I have no idea what this means. Is it not expecting a directory? The README says it should be...

```oxidized@ITDVZX001:~/.config/oxidized$ oxidized -d    
Puma starting in single mode...
* Version 3.11.4 (ruby 2.7.0-p0), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
Use Ctrl-C to stop
#<Oxidized::Job:0x00005616273e21a8 /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:7 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        8: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
        7: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
        6: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
        5: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
        4: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:67:in `run_input'
        3: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/input/telnet.rb:24:in `connect'
        2: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/input/telnet.rb:24:in `new'
        1: from /var/lib/gems/2.7.0/gems/net-telnet-0.2.0/lib/net/telnet.rb:340:in `initialize'
/var/lib/gems/2.7.0/gems/net-telnet-0.2.0/lib/net/telnet.rb:340:in `+': no implicit conversion of nil into String (TypeError)
        7: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
        6: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
        5: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
        4: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
        3: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:66:in `run_input'
        2: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:82:in `rescue in run_input'
        1: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:82:in `open'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:82:in `initialize': Is a directory @ rb_sysopen - /home/oxidized/.config/oxidized/crashes/ (Errn)
Is a directory @ rb_sysopen - /home/oxidized/.config/oxidized/crashes/
Traceback (most recent call last):
        8: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
        7: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
        6: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
        5: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
        4: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:67:in `run_input'
        3: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/input/telnet.rb:24:in `connect'
        2: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/input/telnet.rb:24:in `new'
        1: from /var/lib/gems/2.7.0/gems/net-telnet-0.2.0/lib/net/telnet.rb:340:in `initialize'
/var/lib/gems/2.7.0/gems/net-telnet-0.2.0/lib/net/telnet.rb:340:in `+': no implicit conversion of nil into String (TypeError)
        7: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
        6: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
        5: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
        4: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
        3: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:66:in `run_input'
        2: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:82:in `rescue in run_input'
        1: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:82:in `open'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:82:in `initialize': Is a directory @ rb_sysopen - /home/oxidized/.config/oxidized/crashes/ (Errn)```

**Comment by clontarfx** [comment]
Fixed, wrong delimiter in my router.db.

Talk about a useless crash message 😂
