### ISSUE TITLE
Bypass SSL 

### ISSUE THREAD

**Issue by mmihir82** [ytti/oxidized#2312]
Hello, I have LibreNMS with HTTPS running. I'm having hard time get the SSL certs when using the LibreNMS as Source to pull the Hosts. 
It works when I do curl. 
```
 curl -H "X-Auth-Token: xxxxx" https://network-librenms-eu.ingress.net/api/v0/oxidized -v -k
  ```
But when when running oxidized from container it doesn't work. 
here is the errors:
```
May 28 08:15:20 8dd41b251aee oxidized[922]: Oxidized starting, running as pid 922
May 28 08:15:20 8dd41b251aee oxidized[922]: lib/oxidized/nodes.rb: Loading nodes
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /usr/lib/ruby/2.5.0/net/http.rb:985:in `connect'
	from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
	from /usr/lib/ruby/2.5.0/net/http.rb:1458:in `request'
```

**Comment by mmihir82** [comment]
Here is my source config:
```
input:
  default: ssh
  debug: true
  ssh:
    secure: false
  utf8_encoded: true
output:
  default: file
source:
  default: http
  debug: true
  http:
    url: https://network-librenms-eu.ingress.net//api/v0/oxidized
    scheme: https
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: xxxx
  ```
