### ISSUE TITLE
Oxidized Crash - failed to parse loose object: invalid header [Rugged::ObjectError]

### ISSUE THREAD

**Issue by nbeard49** [ytti/oxidized#2358]
Greetings,

I've been running the latest version of Oxidized (0.28.0) on an Ubuntu Server 18.04.4 LTS system for quite a while at this point, but lately the service appears to be continually crashing after process restarts. The crash file that is written is included below:

```
--------------------------------------------------
2021-09-01 18:34:16 UTC
failed to parse loose object: invalid header [Rugged::ObjectError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:184:in `target'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:184:in `update_repo'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:160:in `update'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

I've tried reinstalling, but that doesn't appear to fix the issue. The service will run for a period of time successfully collecting device backups before this happens. Please let me know what else is needed for troubleshooting output as I'm no Ruby dev :)

Is anybody else seeing a similar issue?

**Comment by mortzu** [comment]
Is your git repository healthy?
