### ISSUE TITLE
Oxidized reports Port 443 in use

### ISSUE THREAD

**Issue by averagecdn** [ytti/oxidized#2359]
Issue that oxidized is reporting that port 443 is in use. oxidized is running on ubuntu 20 with librenms (nginx). 

```
oxidized@librenms:~/.config/oxidized$` cat crash
--------------------------------------------------
2021-09-02 17:52:21 UTC
Failed to open TCP connection to localhost:443 (Connection refused - connect(2) for "localhost" port 443) [Errno::ECONNREFUSED]
--------------------------------------------------
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
/usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
/usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:74:in `read_http'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:21:in `load'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------

```

**Comment by systeembeheerder** [comment]
That is not what the crash log says, it is "connection refused" Where did you find port in use?

**Comment by mortzu** [comment]
Maybe its from the HTTP source module?
