### ISSUE TITLE
git repo - too many open files crash

### ISSUE THREAD

**Issue by ghost** [ytti/oxidized#2369]
Hello All!

Our oxidized service has been running without issues but yesterday it crashed with the following message:

`first 'could not open '/var/lib/oxidized/git-repos/GB008789.git/refs/heads/master': Too many open files' was raised while opening git repo, then 'no implicit conversion of Rugged::Repository into String' was while trying to create git repo [Oxidized::Git::GitError]`

Full crash log below:

```
--------------------------------------------------
2021-09-27 04:12:41 UTC
first 'could not open '/var/lib/oxidized/git-repos/GB008789.git/refs/heads/master': Too many open files' was raised while opening git repo, then 'no implicit conversion of Rugged::Repository into String' was while trying to create git repo [Oxidized::Git::GitError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:165:in `rescue in rescue in update'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:162:in `rescue in update'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:158:in `update'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

I'm not sure how can I troubleshoot further. Anyone has experienced similar issues?

Best regards!

**Comment by mortzu** [comment]
Try rising the open files limit: https://www.ibm.com/docs/en/sim/6.0.0.22?topic=problems-too-many-files-open-unix-linux
