### ISSUE TITLE
Fetch failure when using groups to specify username and password

### ISSUE THREAD

**Issue by murrant** [ytti/oxidized#242]
Fetching the config fails with this error:
```
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct) [TypeError]
--------------------------------------------------
/usr/local/lib64/ruby/gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:70:in `initialize'
/usr/local/lib64/ruby/gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:70:in `open'
/usr/local/lib64/ruby/gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:70:in `block in initialize'
/usr/lib64/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/lib64/ruby/2.0.0/timeout.rb:97:in `timeout'
/usr/local/lib64/ruby/gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:67:in `initialize'
/usr/local/lib64/ruby/gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:207:in `new'
/usr/local/lib64/ruby/gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:207:in `start'
/usr/local/lib64/ruby/gems/2.0.0/gems/oxidized-0.9.0/lib/oxidized/input/ssh.rb:25:in `connect'
/usr/local/lib64/ruby/gems/2.0.0/gems/oxidized-0.9.0/lib/oxidized/node.rb:57:in `run_input'
/usr/local/lib64/ruby/gems/2.0.0/gems/oxidized-0.9.0/lib/oxidized/node.rb:36:in `block in run'
/usr/local/lib64/ruby/gems/2.0.0/gems/oxidized-0.9.0/lib/oxidized/node.rb:31:in `each'
/usr/local/lib64/ruby/gems/2.0.0/gems/oxidized-0.9.0/lib/oxidized/node.rb:31:in `run'
/usr/local/lib64/ruby/gems/2.0.0/gems/oxidized-0.9.0/lib/oxidized/job.rb:8:in `block in initialize'
```

Config snippet:
```
groups: 
  routers:
    username: user
    password: pwd
```

**Comment by ytti** [comment]
Can you post full config

**Comment by murrant** [comment]
Full sanitized config: https://fnpaste.com/AYJJ
