### ISSUE TITLE
Oxidized won't start - looks for router.db in incorrect location despite ENV variable and config

### ISSUE THREAD

**Issue by kclay27** [ytti/oxidized#2497]
I am running Rocky Linux 8.5. I can't get oxidized to start properly. It keeps looking for the router.db file in the wrong location.

I've changed the ENV variable for OXIDIZED_HOME to '/etc/oxidized' as well as set the router.db file path in config to '/etc/oxidized'. Despite this, oxidized keeps looking for the router.db file in the default home directory. I've also ensured there is not a duplicate config file in /root/oxidized/.config.

The crash error is as follows:
```
--------------------------------------------------
2022-03-12 00:43:32 UTC
No such file or directory @ rb_sysopen - /home/oxidized/.config/oxidized/router.db [Errno::ENOENT]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/source/csv.rb:56:in `initialize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/source/csv.rb:56:in `open'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/source/csv.rb:56:in `open_file'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/source/csv.rb:23:in `load'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/usr/local/share/gems/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

When I try to start in manually:
```
I, [2022-03-11T17:43:32.336508 #66964]  INFO -- : Oxidized starting, running as pid 66964
I, [2022-03-11T17:43:32.336993 #66964]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2022-03-11T17:43:32.337088 #66964] FATAL -- : Oxidized crashed, crashfile written in /etc/oxidized/crash
No such file or directory @ rb_sysopen - /home/oxidized/.config/oxidized/router.db
```

Here is my service file:
```
[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
Environment="OXIDIZED_HOME=/etc/oxidized"
ExecStart=/usr/local/bin/oxidized
User=oxidized
KillSignal=SIGKILL
Restart=on-failure
RestartSec=300s

[Install]
WantedBy=multi-user.target
```

Here is the config file located at "/etc/oxidized/config":
```
---
input:
  default: ssh
  debug: false
  ssh:
    secure: false

output:
  file:
    directory: /etc/oxidized/output/configs

source:
  default: csv
  csv:
    file: /etc/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
    vars_map: {}

model_map:
  juniper: junos
  cisco: ios

vars: {}

```
I'm wondering if this is a Rocky specific issue or if anyone else has come across this. Any assistance or advice is appreciated. Thanks.

**Comment by kclay27** [comment]
Ended up being a user permissions issue. Not relevant.
