### ISSUE TITLE
TPLINK SWITCH (TL-SH5428) backup not work ,it seems end without correct identification .

### ISSUE THREAD

**Issue by lion00** [ytti/oxidized#2508]
TPLINK SWITCH  error ：
2022-03-29 01:52:09 UTC
bad value for range [ArgumentError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/tplink.rb:46:in `block in <class:TPLink>'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/model.rb:124:in `instance_exec'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/model.rb:124:in `cmd'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/model.rb:162:in `block in get'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/model.rb:161:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/model.rb:161:in `get'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/input/cli.rb:14:in `get'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:67:in `run_input'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'

the log  end：
.........(Skip some content)
interface vlan 1                                                                
 ip address 192.168.1.253 255.255.255.0                                         
 ipv6 enable                                                                    
 ip helper-address 192.168.1.1                                                  
\#                                                                               
interface vlan 5                                                                
Press any key to continue (Q to quit)                                           
Press any key to continue (Q to quit)                                           
Press any key to continue (Q to quit)                                           
interface vlan 10                                                               
 ip address 192.168.10.1 255.255.255.0                                          
 no ipv6 enable                                                                 
\#                                                                               
interface vlan 20                                                               
 ip address 192.168.20.1 255.255.255.0                                          
 no ipv6 enable                                                                 
\#                                                                               
interface vlan 22                                                               
 shutdown                                                                       
 ip address 192.168.22.254 255.255.255.0                                        
 description "guestvlan"                                                        
 no ipv6 enable                                                                 
\#                                                                               
interface vlan 30                                                               
 ip address 192.168.30.254 255.255.255.0                                        
 no ipv6 enable                                                                 
\#                                                                               
interface vlan 31                                                               
 ip address 192.168.31.254 255.255.255.0                                        
 no ipv6 enable                                                                 
\#                                                                               
interface vlan 32                                                               
Press any key to continue (Q to quit)                                           
Press any key to continue (Q to quit)                                           
Press any key to continue (Q to quit)    
\#
interface vlan 40                                                               
 ip address 192.168.40.254 255.255.255.0                                        
 description "IOTS"                                                             
 no ipv6 enable                                                                 
\#                                                                               
interface vlan 50                                                               
 ip address 192.168.50.1 255.255.255.0                                          
 no ipv6 enable                                                                 
\#                                                                               
interface vlan 52                                                               
 ip address 192.168.52.1 255.255.255.0                                          
 no ipv6 enable                                                                 
 ip helper-address 192.168.10.2                                                 
\#                                                                               
interface vlan 100                                                              
 ip address 192.168.100.254 255.255.255.0                                       
 no ipv6 enable          

\#                                                                               
   \#                                                                              
   \#                                                                           
   \#                                                                              
\#                                                                               
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#      

TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#                                                                      
                                                                                
TL-SH5428#  
                                                                                
i think it seems end without correct identification .(full log in files)
[192.168.1.253-ssh.txt](https://github.com/ytti/oxidized/files/8367751/192.168.1.253-ssh.txt)
[log.txt](https://github.com/ytti/oxidized/files/8367747/log.txt)

**Comment by lion00** [comment]
It seems docker's issue, I install it in ubuntu, it  works
