### ISSUE TITLE
Oxidized and Ruby 3.0

### ISSUE THREAD

**Issue by xbeaudouin** [ytti/oxidized#2552]
Hello,

Recently migred my FreeBSD from 12.2 to 13.1... and Ruby has bumped to 3.0.

I have the following issue :  
```
# cat crash
--------------------------------------------------
2022-05-25 08:55:17 UTC
wrong number of arguments (given 2, expected 1) [ArgumentError]
--------------------------------------------------
/usr/local/lib/ruby/gems/3.0/gems/puma-5.6.4/lib/rack/handler/puma.rb:63:in `run'
/usr/local/lib/ruby/gems/3.0/gems/oxidized-web-0.13.1/lib/oxidized/web.rb:29:in `block in run'
--------------------------------------------------
```

Do you know if ruby has changed something on puma ?

Regards

**Comment by xbeaudouin** [comment]
Forget it, it working again.
