### ISSUE TITLE
resove_dns: false not working, im using oxidized with librenms as source

### ISSUE THREAD

**Issue by arreddy1** [ytti/oxidized#2554]
Configured librenms as source
when query librenms getting device list as below ( im not using dns for librenms, added devices with ip address )

[
    {
        "hostname": "myswitch_ip",
        "os": "ios",
        "ip": null,
        "group": "default"
    },
    {
        "hostname": "myswitch_ip",
        "os": "nxos",
        "ip": null,
        "group": "default"
    }

so im mapping ip to hostname in oxidized config like below

source:
  default: http
  debug: true
  http:
    url: http://librenmsip/api/v0/oxidized
    map:
      ip: hostname  <<<<< im mapping hostname to ip
      model: os
      group: group
    headers:
      X-Auth-Token: 'mytoken'

when i run oxidized. getting below error about name resolution failed eventhough resove_dns is set to false

I, [2022-05-27T18:36:05.939537 #24364]  INFO -- : Oxidized starting, running as pid 24364
I, [2022-05-27T18:36:05.985528 #24364]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2022-05-27T18:36:06.015773 #24364] DEBUG -- : resolving DNS for ...
D, [2022-05-27T18:36:06.015844 #24364] DEBUG -- : IPADDR 172.31.236.100
D, [2022-05-27T18:36:06.015951 #24364] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ios'
D, [2022-05-27T18:36:06.015988 #24364] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2022-05-27T18:36:06.016022 #24364] DEBUG -- : node.rb: returning node key 'model' with value 'ios'
D, [2022-05-27T18:36:06.016050 #24364] DEBUG -- : lib/oxidized/node.rb: Loading model "ios"
D, [2022-05-27T18:36:06.018144 #24364] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2022-05-27T18:36:06.018192 #24364] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2022-05-27T18:36:06.018228 #24364] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2022-05-27T18:36:06.018260 #24364] DEBUG -- : lib/oxidized/model/model.rb Added show vtp status to the commands list
D, [2022-05-27T18:36:06.018290 #24364] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2022-05-27T18:36:06.018320 #24364] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2022-05-27T18:36:06.018546 #24364] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value ''
D, [2022-05-27T18:36:06.018592 #24364] DEBUG -- : node.rb: returning node key 'input' with value 'ssh, telnet'
D, [2022-05-27T18:36:06.129021 #24364] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'file' and node value ''
D, [2022-05-27T18:36:06.129101 #24364] DEBUG -- : node.rb: returning node key 'output' with value 'file'
D, [2022-05-27T18:36:06.130296 #24364] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2022-05-27T18:36:06.130347 #24364] DEBUG -- : node.rb: setting node key 'username' to value 'myswitch username' from global
D, [2022-05-27T18:36:06.130385 #24364] DEBUG -- : node.rb: returning node key 'username' with value 'myswitch username'
D, [2022-05-27T18:36:06.130414 #24364] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2022-05-27T18:36:06.130445 #24364] DEBUG -- : node.rb: setting node key 'password' to value 'myswitchpassword' from global
D, [2022-05-27T18:36:06.130476 #24364] DEBUG -- : node.rb: returning node key 'password' with value 'myswitchpassword'

I, [2022-05-27T18:36:06.132222 #24364]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
D, [2022-05-27T18:36:06.582631 #24364] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
Puma starting in single mode...
* Version 3.11.4 (ruby 2.7.0-p0), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://http:
#<Thread:0x000055fc56d7f5e8 /var/lib/gems/2.7.0/gems/oxidized-web-0.13.1/lib/oxidized/web.rb:28 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        10: from /var/lib/gems/2.7.0/gems/oxidized-web-0.13.1/lib/oxidized/web.rb:29:in `block in run'
         9: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/rack/handler/puma.rb:70:in `run'
         8: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/launcher.rb:184:in `run'
         7: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/single.rb:87:in `run'
         6: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/runner.rb:144:in `load_and_bind'
         5: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:88:in `parse'
         4: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:88:in `each'
         3: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:105:in `block in parse'
         2: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `add_tcp_listener'
         1: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `new'
/var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `initialize': getaddrinfo: Temporary failure in name resolution (SocketError)
F, [2022-05-27T18:36:06.652090 #24364] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
getaddrinfo: Temporary failure in name resolution
Traceback (most recent call last):
        10: from /var/lib/gems/2.7.0/gems/oxidized-web-0.13.1/lib/oxidized/web.rb:29:in `block in run'
         9: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/rack/handler/puma.rb:70:in `run'
         8: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/launcher.rb:184:in `run'
         7: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/single.rb:87:in `run'
         6: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/runner.rb:144:in `load_and_bind'
         5: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:88:in `parse'
         4: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:88:in `each'
         3: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:105:in `block in parse'
         2: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `add_tcp_listener'
         1: from /var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `new'
/var/lib/gems/2.7.0/gems/puma-3.11.4/lib/puma/binder.rb:270:in `initialize': getaddrinfo: Temporary failure in name resolution (SocketError)

Appreciate any help/guidence

Thanks

**Comment by arreddy1** [comment]
Re installed , issue resolved
