### ISSUE TITLE
Issues pulling data from netbox

### ISSUE THREAD

**Issue by feriniguez** [ytti/oxidized#2622]
Hello, I have some issues while pulling data from netbox.

This is the message I get:

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Sep 16 19:39:25 oxidized syslog-ng[13]: syslog-ng starting up; version='3.13.2'
*** Booting runit daemon...
*** Runit started as PID 22
Sep 16 19:39:26 oxidized cron[28]: (CRON) INFO (pidfile fd = 3)
Sep 16 19:39:26 oxidized cron[28]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
execution expired
/usr/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/lib/ruby/2.5.0/net/http.rb:937:in `open'
	from /usr/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
	from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	from /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
	from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
	from /usr/lib/ruby/2.5.0/net/http.rb:1458:in `request'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:77:in `read_http'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:21:in `load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
	from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

This is my config:

```
---
username: oxidized-bot
password: xyz
model: junos
# oxidized will attempt to pull all your devices within the interval; 12hrs
interval: 43200
log: /root/.config/oxidized/logs/oxidized.log
debug: true
threads: 30
timeout: 45
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
crash:
  directory: /root/oxidized/oxidized/crashes
  hostnames: true
vars:
  remove_secret: true
  auth_methods: [ "password" ]
  ssh_hmac: hmac-sha1-96, hmac-md5,hmac-sha1, hmac-md5-96, hmac-sha2-512, hmac-sha2-256
  ssh_no_keepalive: true
rest: 127.0.0.1:8888/oxidized
pid: /root/.config/oxidized/pid
input:
  default: ssh,http
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    type_as_directory: true
    user: config
    repo: "/root/.config/oxidized/backups/.git"
hooks:
   first_hook:
     type: exec
     events: [post_store]
     cmd: 'echo "$OX_NODE_NAME commit" > /root/.config/oxidized/backups/$OX_NODE_GROUP.git/description'
     timeout: 10
source:
  default: http
  http:
    url: https://netbox-lab/api/dcim/devices/
    scheme: https
    hosts_location: results
    delimiter: !ruby/regexp /:/
    read_timeout: 120
    user: false
    map:
      name: name
      model: platform.name
      ip: primary_ip.address
      group: site.name
    headers:
      Authorization: Token xyz
model_map:
  cisco: ios
  juniper: junos

```

Using curl I can get the json containing the device's list.:
```
curl --insecure -H "Authorization: Token xyz" -H "Accept: application/json; indent=4" https://netbox-lab/api/dcim/devices/
```
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 1839,
            "url": "https://netbox-lab/api/dcim/devices/1839/",
            "display": "can-xyz-1e-ap-1",
            "name": "can-xyz-1e-ap-1",
            "device_type": {
                "id": 44,
                "url": "https://netbox-lab/api/dcim/device-types/44/",
                "display": "AIR-SAP1602I-A-K9",
                "manufacturer": {
                    "id": 1,
                    "url": "https://netbox-lab/api/dcim/manufacturers/1/",
                    "display": "Cisco",
                    "name": "Cisco",
                    "slug": "cisco"
                },
                "model": "AIR-SAP1602I-A-K9",
                "slug": "air-sap1602i-a-k9"
            },
            "device_role": {
                "id": 6,
                "url": "https://netbox-lab/api/dcim/device-roles/6/",
                "display": "WiFi",
                "name": "WiFi",
                "slug": "wifi"
            },
            "tenant": null,
            "platform": {
                "id": 1,
                "url": "https://netbox-lab/api/dcim/platforms/1/",
                "display": "ios",
                "name": "ios",
                "slug": "ios"
            },
            "serial": "FGL1913X6NH",
            "asset_tag": null,
            "site": {
                "id": 109,
                "url": "https://netbox-lab/api/dcim/sites/109/",
                "display": "USA-PAT-L1",
                "name": "USA-PAT-L1",
                "slug": "usa-pat-l1"
            },
            "primary_ip": {
                "id": 1988,
                "url": "https://netbox-lab/api/ipam/ip-addresses/1988/",
                "display": "dead:beef:e:5:86b8:2ff:fed1:9e21/128",
                "family": 6,
                "address": "dead:beef:e:5:86b8:2ff:fed1:9e21/128"
            },
            [.....]
        }
    ]

```

Still don't know what is happening. 

I would appreciate any clues...

Thanks!

**Comment by feriniguez** [comment]
added 'secure: false' to config. same result.

**Comment by davama** [comment]
```
execution expired
/usr/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
```

increase read_timeout maybe?

**Comment by feriniguez** [comment]
Tried from a different oxidized install using the same config.... Now I'm getting this message:

```
Sep 16 22:17:37 oxidized cron[27]: (CRON) INFO (pidfile fd = 3)
Sep 16 22:17:37 oxidized cron[27]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
superclass mismatch for class HTTP
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/input/http.rb:6:in `<module:Oxidized>': superclass mismatch for class HTTP (TypeError)
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/input/http.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/manager.rb:9:in `load'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/manager.rb:60:in `loader'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/manager.rb:35:in `add_input'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:161:in `block in resolve_input'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:160:in `map'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:160:in `resolve_input'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:23:in `initialize'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:21:in `new'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:21:in `block (2 levels) in load'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:16:in `each'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:16:in `block in load'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
	from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

**Comment by feriniguez** [comment]
Ok I got this thing work.

I had this in my config:

```
input:
  default: ssh,http
  debug: false
  ssh:
    secure: false
```

We use http to pull configs from some routers using restconf. 
because of this message: 
``<module:Oxidized>': superclass mismatch for class HTTP (TypeError)`
I thought of removing the htt part on this section. So my config now looks like this:
```
input:
  default: ssh
  debug: false
  ssh:
    secure: false
```
And It worked. Now I'm thinking how to restore the functionality of getting configs via restconf. I'm wondering if this can be a bug.

Has this happened to any of you?
