### ISSUE TITLE
could not find repository from '/var/lib/oxidized/devices.git''

### ISSUE THREAD

**Issue by Paddys2** [ytti/oxidized#2684]
Hi ,

Appreciate if some one can help in fixing this error.

F, [2022-12-16T15:32:42.452256 #1849] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
first 'could not find repository from '/var/lib/oxidized/devices.git'' was raised while opening git repo, then 'failed to make directory '/var/lib/oxidized/devices.git/objects': Permission denied' was while trying to create git repo
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:165:in `rescue in rescue in update': first 'could not find repository from '/var/lib/oxidized/devices.git'' was raised while opening git repo, then 'failed to make directory '/var/lib/oxidized/devices.git/objects': Permission denied' was while trying to create git repo (Oxidized::Git::GitError)
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:162:in `rescue in update'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:158:in `update'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        from /usr/local/bin/oxidized:25:in `load'
        from /usr/local/bin/oxidized:25:in `<main>'

**Comment by Paddys2** [comment]
Please let me know if some once come across this issue?

Also please find the crash log

oxidized@ip-10-200-26-17:~/.config/oxidized$ cat crash
--------------------------------------------------
2022-12-16 15:54:28 UTC
first 'could not find repository from '/var/lib/oxidized/devices.git'' was raised while opening git repo, then 'failed to make directory '/var/lib/oxidized/devices.git/objects/info': Permission denied' was while trying to create git repo [Oxidized::Git::GitError]
--------------------------------------------------
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:165:in `rescue in rescue in update'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:162:in `rescue in update'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:158:in `update'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:25:in `load'
/usr/local/bin/oxidized:25:in `<main>'
--------------------------------------------------
