### ISSUE TITLE
Versions can not be displayed

### ISSUE THREAD

**Issue by quotengrote** [ytti/oxidized#2760]
Hi,

if Oxidized is used with this Image: `oxidized/oxidized:latest` i can not display the versions for a device anymore.

## Error
![2023-04-21 10_55_27-ArgumentError at _node_version - Vivaldi](https://user-images.githubusercontent.com/38253905/233592721-732570b9-bb5f-4a10-824a-33a7e037acaf.png)

```
2023-04-21 08:55:24 - ArgumentError - wrong number of arguments (given 0, expected 1+):
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/views/versions.haml:24:in `count'
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/views/versions.haml:24:in `__tilt_9520'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/template.rb:191:in `bind_call'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/template.rb:191:in `evaluate'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/haml.rb:28:in `evaluate'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/template.rb:109:in `render'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:823:in `render'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:677:in `haml'
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:241:in `out'
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:165:in `block in <class:WebApp>'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by quotengrote** [comment]
any news on this?

**Comment by bacala** [comment]
I have noticed the same issue. If you try to call it in json format it returns "node not found" which is actually the reason why we get ArgumenError. It tries to call .count on string instead of array. I would say that ```nodes.version``` doesn't work but the ```nodes.show``` yes. So it could be a help to troubleshoot it further.
