### ISSUE TITLE
Oxidixed doesn`t work with Git

### ISSUE THREAD

**Issue by goro22052** [ytti/oxidized#2762]
Hi, I installed git
and run these commands

```
git config --global user.email "admin@tj.ua" 
git config --global user.name "oxidized"

cd ~/.config/oxidized
git init oxidized.git
git init devices.git
```

then I created the config file

```
model: routeros
resolve_dns: true
interval: 3600
use_syslog: true
threads: 10
timeout: 180
retries: 5
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "~/.config/oxidized/pid"
log: "~/.config/oxidized/logs/"
crash: "~/.config/oxidized/crashes/"
stats:
  history_size: 10
input:
  default: ssh
  debug: true
  ssh:
    secure: false
map:
  verify_host_key: never
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: admin@tj.ua
    single_repo: true
    repo: "~/.config/oxidized/devices/devices.git"
source:
  default: csv
  csv:
    file: "~/.config/oxidized/mikrotik/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
      port: 3
      username: 4
      password: 5
model_map:
  Cisco: ios
  mikrotik: routeros
```

then I runed oxidized and I pushed the button version in the web interface

and  I saw the error in the web interface

```
ArgumentError at /node/version
wrong number of arguments (given 0, expected 1+)
file: versions.haml location: count line: 240`

And I saw the errors in the console

`2023-04-21 15:55:14 - ArgumentError - wrong number of arguments (given 0, expected 1+):
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/views/versions.haml:24:in `count'
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/views/versions.haml:24:in `__tilt_1420'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/template.rb:191:in `bind_call'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/template.rb:191:in `evaluate'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/haml.rb:28:in `evaluate'
        /var/lib/gems/3.0.0/gems/tilt-2.1.0/lib/tilt/template.rb:109:in `render'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:823:in `render'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:677:in `haml'
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:241:in `out'
        /var/lib/gems/3.0.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:165:in `block in <class:WebApp>'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/3.0.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /var/lib/gems/3.0.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
        /var/lib/gems/3.0.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
        /var/lib/gems/3.0.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
```

How I can fix it?

**Comment by adam75south** [comment]
This will fix it. You have to edit git.rb and replace line 82
https://github.com/ytti/oxidized/pull/2758/commits/80edee15161384e805ae30c21b7669f58d809fb7
