### ISSUE TITLE
Trying to make Netbox my source

### ISSUE THREAD

**Issue by NordloSydost-Pajje** [ytti/oxidized#2793]
Hi,

I trying to fetch infromation from Netbox to use as source for Oxidized but i'm having problems.

My config Source-part is:

```
source:
  default: http
  debug: true
  http:
    url: https://xxxxxxxxxxx/api/dcim/devices/?cf_Backup_Oxidized=True
    scheme: https
    secure: false
    no_check_certificate: true
    host_location: results
    delimiter: !ruby/regexp /:/
    map:
      name: name
      ip: primare_ip.address
      model: platform.slug
      group: device_type.manufacturer.slug
    headers:
      Authorization: 'Token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      Accept: 'application/json; indent=4'
```

when i try to start Oxidized i get a crashfile lilke:
```
--------------------------------------------------
2023-05-14 16:36:33 UTC
no implicit conversion of String into Integer [TypeError]
--------------------------------------------------
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:54:in `block in string_navigate'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:53:in `each'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:53:in `string_navigate'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:29:in `block (2 levels) in load'
/var/lib/gems/3.0.0/gems/asetus-0.4.0/lib/asetus/configstruct.rb:18:in `each'
/var/lib/gems/3.0.0/gems/asetus-0.4.0/lib/asetus/configstruct.rb:18:in `each'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:28:in `block in load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:23:in `each'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:23:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:16:in `block in load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:133:in `synchronize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:133:in `with_lock'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:11:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:128:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:25:in `load'
/usr/local/bin/oxidized:25:in `<main>'
--------------------------------------------------
```

If i do a curl to the configured url i get this (beutified):
```
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 20,
      "url": "https:/xxxxxxxxxxxxxxxx/api/dcim/devices/20/",
      "display": "xxxxxxxxxxxxxxxx",
      "name": "xxxxxxxxxxxxxxxx",
      "device_type": {
        "id": 20,
        "url": "https://xxxxxxxxxxxxxxxx/api/dcim/device-types/20/",
        "display": "FortiGate 200F",
        "manufacturer": {
          "id": 1,
          "url": "https://xxxxxxxxxxxxxxxx/api/dcim/manufacturers/1/",
          "display": "Fortinet",
          "name": "Fortinet",
          "slug": "fortinet"
        },
        "model": "FortiGate 200F",
        "slug": "fg-200f"
      },
      "device_role": {
        "id": 37,
        "url": "https://xxxxxxxxxxxxxxxx/api/dcim/device-roles/37/",
        "display": "FWC",
        "name": "FWC",
        "slug": "FWC"
      },
      "tenant": {
        "id": 3,
        "url": "https://xxxxxxxxxxxxxxxx/api/tenancy/tenants/3/",
        "display": "xxxxxxxxxxxxxxxx",
        "name": "xxxxxxxxxxxxxxxx",
        "slug": "xxxxxxxxxxxxxxxx"
      },
      "platform": {
        "id": 1,
        "url": "https://xxxxxxxxxxxxxxxx/api/dcim/platforms/1/",
        "display": "Fortinet",
        "name": "Fortinet",
        "slug": "fortinet"
      },
      "serial": "xxxxxxxxxxxxxxxx",
      "asset_tag": null,
      "site": {
        "id": 6,
        "url": "https://nxxxxxxxxxxxxxxxx/api/dcim/sites/6/",
        "display": "xxxxxxxxxxxxxxxx",
        "name": "xxxxxxxxxxxxxxxx",
        "slug": "xxxxxxxxxxxxxxxx"
      },
      "location": null,
      "rack": {
        "id": 6,
        "url": "https://xxxxxxxxxxxxxxxx/api/dcim/racks/6/",
        "display": "xxxxxxxxxxxxxxxx",
        "name": "xxxxxxxxxxxxxxxx"
      },
      "position": 23,
      "face": {
        "value": "front",
        "label": "Front"
      },
      "parent_device": null,
      "status": {
        "value": "active",
        "label": "Active"
      },
      "airflow": {
        "value": "left-to-right",
        "label": "Left to right"
      },
      "primary_ip": {
        "id": 305,
        "url": "https://xxxxxxxxxxxxxxxx/api/ipam/ip-addresses/305/",
        "display": "xxxxxxxxxxxxxxxx",
        "family": 4,
        "address": "xxxxxxxxxxxxxxxx"
      },
      "primary_ip4": {
        "id": 305,
        "url": "https://xxxxxxxxxxxxxxxx/api/ipam/ip-addresses/305/",
        "display": "xxxxxxxxxxxxxxxx",
        "family": 4,
        "address": "xxxxxxxxxxxxxxxx"
      },
      "primary_ip6": null,
      "cluster": null,
      "virtual_chassis": null,
      "vc_position": null,
      "vc_priority": null,
      "description": "",
      "comments": "",
      "local_context_data": null,
      "tags": [],
      "custom_fields": {
        "Backup_Oxidized": true
      },
      "config_context": {},
      "created": "2023-03-31T13:54:53.852646+02:00",
      "last_updated": "2023-05-13T19:56:12.210374+02:00"
    }
  ]
}
```

Can anyone give me some tips on what the probelm could be?

**Comment by yoakim** [comment]
Never done source from netbox, but your key for the IP mapping is wrong (spelling).
Maybe check that first!

**Comment by NordloSydost-Pajje** [comment]
I have changed te spelling error (thanx for that) but still the same error.

**Comment by NordloSydost-Pajje** [comment]
I solved it and i am embarrassed to say it was my own fault. I did get one of the config variables wrong.

I typed "host_location: results" in the config but i should be "hosts_location: results".

Now i got it working with some help from the post regarding "oxidized superclass mismatch for class http", [https://github.com/ytti/oxidized/issues/2154](url)

**Comment by yoakim** [comment]
Gött, var också tvungen att göra super class fixen.
