### ISSUE TITLE
RouterOS end of file reached [EOFError]

### ISSUE THREAD

**Issue by E-t-z** [ytti/oxidized#2812]
Running Oxidized via (official) Docker image and, it seems that latest has some issues.

```
I, [2023-05-29T14:40:49.947090 #356]  INFO -- : Oxidized starting, running as pid 356
I, [2023-05-29T14:40:50.036518 #356]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-29T14:40:50.040498 #356] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
end of file reached
```

```
--------------------------------------------------
2023-05-29 14:43:49 UTC
end of file reached [EOFError]
--------------------------------------------------
/usr/lib/ruby/3.0.0/net/protocol.rb:227:in `rbuf_fill'
/usr/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
/usr/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
/usr/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
/usr/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
/usr/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
/usr/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
/usr/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
/usr/lib/ruby/3.0.0/net/http.rb:1521:in `request'
/usr/lib/ruby/3.0.0/net/http.rb:1514:in `block in request'
/usr/lib/ruby/3.0.0/net/http.rb:960:in `start'
/usr/lib/ruby/3.0.0/net/http.rb:1512:in `request'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:78:in `read_http'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:21:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:16:in `block in load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:133:in `synchronize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:133:in `with_lock'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:11:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:128:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:25:in `load'
/usr/local/bin/oxidized:25:in `<main>'
--------------------------------------------------
```

**Comment by E-t-z** [comment]
Caused by
