### ISSUE TITLE
crash when http source node count exceed over ~2K

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#2846]
hello,

Notice that when the netbox api sends node count that is too large (approx: ~2K+), oxidized crashes with:

```
I, [2023-06-29T00:56:28.503756 #19]  INFO -- : Oxidized starting, running as pid 19
I, [2023-06-29T00:56:28.593332 #19]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-06-29T00:56:37.981672 #19] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
undefined method `new' for nil:NilClass
```

My crash file:

```
--------------------------------------------------
2023-06-29 00:56:47 UTC
undefined method `new' for nil:NilClass [NoMethodError]
--------------------------------------------------
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/manager.rb:17:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/manager.rb:60:in `loader'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/manager.rb:48:in `add_model'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/node.rb:179:in `resolve_model'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/node.rb:23:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:22:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:22:in `block (2 levels) in load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:17:in `each'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:17:in `block in load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:133:in `synchronize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:133:in `with_lock'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:11:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/nodes.rb:128:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:25:in `load'
/usr/local/bin/oxidized:25:in `<main>'
--------------------------------------------------
```

Tried to see how low i could go when  it comes to number of nodes without crashing:

- On site with `2047` nodes, it is fine, no issue.
- another site with `2300+` nodes, it crashes.

So the threshold is somewhere in between...

Not sure where to look or what to change...

Any input is appreciated.

Thank you,
Dave

**Comment by davama** [comment]
Just as a note:

our production servers uses `sqLite` as the source with one of them with up to `10,085` nodes and no issue.

So I'm finger is pointing at `net::HTTP` ... but I don't know really...

**Comment by davama** [comment]
found the issue...

looks like a new extended module was not properly configured.

i found it when it failed on said device that required the new module. I set all debug settings to true and ran it with ruby

```
root@oxidized-container:~# irb3.0 --verbose /usr/local/bin/oxidized 
...
...
D, [2023-06-29T19:47:05.033802 #74] DEBUG -- : resolving DNS for p-olt-1...
D, [2023-06-29T19:47:05.033855 #74] DEBUG -- : IPADDR 2x:x:x
D, [2023-06-29T19:47:05.033967 #74] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'nokia_olt'
D, [2023-06-29T19:47:05.034020 #74] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2023-06-29T19:47:05.034078 #74] DEBUG -- : node.rb: returning node key 'model' with value 'nokia_olt'
D, [2023-06-29T19:47:05.034134 #74] DEBUG -- : lib/oxidized/node.rb: Loading model "nokia_olt"
D, [2023-06-29T19:47:05.036174 #74] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2023-06-29T19:47:05.036253 #74] DEBUG -- : lib/oxidized/model/model.rb Added show equipment ont interface to the commands list
D, [2023-06-29T19:47:05.036311 #74] DEBUG -- : lib/oxidized/model/model.rb Added show equipment ont status pon to the commands list
D, [2023-06-29T19:47:05.036494 #74] DEBUG -- : lib/oxidized/model/model.rb Added show equipment ont status x-pon to the commands list
D, [2023-06-29T19:47:05.036548 #74] DEBUG -- : lib/oxidized/model/model.rb Added show vlan residential-bridge extensive to the commands list
F, [2023-06-29T19:47:05.037090 #74] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
```

that's a relief

i can continue with migration to http source
