### ISSUE TITLE
Oxidized not running on Rocky Linux 9.3

### ISSUE THREAD

**Issue by JensVeha** [ytti/oxidized#2998]
Install wass successful, however why I try to run in manually I get the following errors:

```
[jens@belvlx004 bin]$ ./oxidized
Invalid gemspec in [/usr/local/share/gems/specifications/oxidized-0.29.1.gemspec]: /usr/local/share/gems/specifications/oxidized-0.29.1.gemspec:71: syntax error, unexpected '.'
mplecov-cobertura>.freeze, ["~> 2.1.0"])
                  ^
/usr/local/share/gems/specifications/oxidized-0.29.1.gemspec:71: syntax error, unexpected ')', expecting '.' or &. or :: or '['
...obertura>.freeze, ["~> 2.1.0"])
...                              ^
/usr/local/share/gems/specifications/oxidized-0.29.1.gemspec:73: syntax error, unexpected `end', expecting end-of-input
  end
  ^~~
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- oxidized (LoadError)
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/cli.rb:4:in `<class:CLI>'
        from /usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/cli.rb:2:in `<module:Oxidized>'
        from /usr/local/share/gems/gems/oxidized-0.29.1/lib/oxidized/cli.rb:1:in `<top (required)>'
        from ./oxidized:7:in `require_relative'
        from ./oxidized:7:in `<main>'
```

Fresh install of Rocky Linux 9.3. Any ideas what may cause this or any ideas on how to fix it?

**Comment by cppmonkey** [comment]
What packages have you installed?

I've just built a vagrant/ansible script that builds oxidized out.  Though I'm sure I saw the issue above when I upgraded from CentOS 8 to Rocky 9

Ensure you have epel enabled
```
# dnf install epel-release
# dnf install make, cmake, which, sqlite-devel, openssl-devel, ruby, gcc, ruby-devel, libicu-devel, gcc-c++ libssh2-devel
# gem install oxidized
# gem install oxidized-web
# useradd -c "oxidized system account" -m -s /bin/bash oxidized
# cp /usr/local/share/gems/gems/oxidized-0.29.1/extra/oxidized.service /etc/systemd/system
# systemctl enable oxidized
```

See what version of things you have installed
```
[vagrant@rocky9-01 ~]$ sudo dnf install make cmake which sqlite-devel openssl-devel ruby gcc ruby-devel libicu-devel gcc-c++ libssh2-devel
Last metadata expiration check: 4:16:34 ago on Sun 10 Dec 2023 05:48:40 PM UTC.
Package make-1:4.3-7.el9.x86_64 is already installed.
Package cmake-3.20.2-8.el9.x86_64 is already installed.
Package which-2.21-29.el9.x86_64 is already installed.
Package sqlite-devel-3.34.1-6.el9_1.x86_64 is already installed.
Package openssl-devel-1:3.0.7-24.el9.x86_64 is already installed.
Package ruby-3.0.4-160.el9_0.x86_64 is already installed.
Package gcc-11.4.1-2.1.el9.x86_64 is already installed.
Package ruby-devel-3.0.4-160.el9_0.x86_64 is already installed.
Package libicu-devel-67.1-9.el9.x86_64 is already installed.
Package gcc-c++-11.4.1-2.1.el9.x86_64 is already installed.
Package libssh2-devel-1.10.0-1.el9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

```
[vagrant@rocky9-01 ~]$ sudo gem list

*** LOCAL GEMS ***

abbrev (default: 0.1.0)
asetus (0.4.0)
base64 (default: 0.1.0)
bcrypt_pbkdf (1.1.0)
benchmark (default: 0.1.1)
bigdecimal (3.0.0)
bundler (2.2.33)
cgi (default: 0.2.1)
csv (default: 3.1.9)
date (default: 3.1.3)
dbm (default: 1.1.0)
debug (default: 0.2.1)
delegate (default: 0.2.0)
did_you_mean (default: 1.5.0)
digest (default: 3.0.0)
drb (default: 2.0.5)
ed25519 (1.3.0)
english (default: 0.7.1)
erb (default: 2.2.0)
etc (default: 1.3.0)
fcntl (default: 1.0.1)
fiddle (default: 1.0.8)
fileutils (default: 1.5.0)
find (default: 0.1.0)
forwardable (default: 1.3.2)
gdbm (default: 2.1.0)
getoptlong (default: 0.1.1)
io-console (0.5.7)
io-nonblock (default: 0.1.0)
io-wait (default: 0.2.0)
ipaddr (default: 1.2.2)
json (2.5.1)
logger (default: 1.4.3)
matrix (default: 0.3.1)
mutex_m (default: 0.1.1)
net-ftp (default: 0.1.2)
net-http (default: 0.1.1)
net-imap (default: 0.1.1)
net-pop (default: 0.1.1)
net-protocol (default: 0.1.1)
net-smtp (default: 0.2.1)
net-ssh (7.2.0)
net-telnet (0.2.0)
nkf (default: 0.1.0)
observer (default: 0.1.1)
open-uri (default: 0.1.0)
open3 (default: 0.1.1)
openssl (default: 2.2.1)
optparse (default: 0.1.1)
ostruct (default: 0.3.1)
oxidized (0.29.1)
pathname (default: 0.1.0)
pp (default: 0.2.1)
prettyprint (default: 0.1.1)
prime (default: 0.1.2)
pstore (default: 0.1.1)
psych (3.3.2)
racc (default: 1.5.2)
rdoc (6.3.3)
readline (default: 0.0.2)
readline-ext (default: 0.1.1)
reline (default: 0.2.5)
resolv (default: 0.2.1)
resolv-replace (default: 0.1.0)
rinda (default: 0.1.1)
rugged (1.7.1)
securerandom (default: 0.1.0)
set (default: 1.0.1)
shellwords (default: 0.1.0)
singleton (default: 0.1.1)
slop (4.10.1)
stringio (default: 3.0.1)
strscan (default: 3.0.1)
syslog (default: 0.1.0)
tempfile (default: 0.1.1)
time (default: 0.1.0)
timeout (default: 0.1.1)
tmpdir (default: 0.1.2)
tracer (default: 0.1.1)
tsort (default: 0.1.0)
un (default: 0.1.0)
uri (default: 0.10.1)
weakref (default: 0.1.1)
yaml (default: 0.1.1)
zlib (default: 2.0.0)
```

I'm sure I had a 2 versions of one of the GEMs and removing it resolved this issue
