### ISSUE TITLE
docker-compose GPG encryption of router.db

### ISSUE THREAD

**Issue by cristianmlastre** [ytti/oxidized#3199]
I am encountering issues while attempting to encrypt my router.db file using GPG.

oxidized-oxidized-1  | GPGME::Error::Canceled
oxidized-oxidized-1  | /var/lib/gems/3.0.0/gems/gpgme-2.0.22/lib/gpgme/ctx.rb:435:in `decrypt_verify': Operation cancelled (GPGME::Error::Canceled)
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/gpgme-2.0.22/lib/gpgme/crypto.rb:172:in `block in decrypt'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/gpgme-2.0.22/lib/gpgme/ctx.rb:79:in `new'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/gpgme-2.0.22/lib/gpgme/crypto.rb:170:in `decrypt'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/source/csv.rb:55:in `open_file'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/source/csv.rb:23:in `load'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/nodes.rb:16:in `block in load'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/nodes.rb:133:in `synchronize'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/nodes.rb:133:in `with_lock'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/nodes.rb:11:in `load'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/nodes.rb:128:in `initialize'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/core.rb:14:in `new'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/core.rb:14:in `initialize'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/core.rb:4:in `new'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/core.rb:4:in `new'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/cli.rb:13:in `run'
oxidized-oxidized-1  | 	from /var/lib/gems/3.0.0/gems/oxidized-0.29.0/bin/oxidized:8:in `<top (required)>'
oxidized-oxidized-1  | 	from /usr/local/bin/oxidized:25:in `load'
oxidized-oxidized-1  | 	from /usr/local/bin/oxidized:25:in `<main>'

My config:

source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db.gpg"
    delimiter: !ruby/regexp /:/
    gpg: true
    gpg_password: 'S3cr3t'
    map:

I'm encrypting the file out of the container using the command 'gpg -c router.db' and setting the passphrase 'S3cr3t'.
Tried too using gpg2 -c router.db. None worked.

When using gpg: false, all loads correctly.

I'm using docker-compose from a Oracle Linux host.

Any help please?

Thank you!

**Comment by cristianmlastre** [comment]
Issue fixed, the issue was related to permissions on gpg folder.
