### ISSUE TITLE
Installing gem package oxidized-script is failing

### ISSUE THREAD

**Issue by LuksNuke** [ytti/oxidized#3200]
Hello,

There is an error when I try to install gem package `oxidized-script`, I think this is a typing error. It is failing in the process of creating the Makefile.

The following output shows that there is an undefined method `exists?()` in file `extconf.rb`. I think the actual method name should be `exist?()` without the 's'.

```sh
$ sudo gem install oxidized-script 
Building native extensions. This could take a while...
ERROR:  Error installing oxidized-script:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.2.0/gems/rugged-0.99.0/ext/rugged
/usr/bin/ruby3.2 -I/usr/lib/ruby/vendor_ruby extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)3.2
        --with-sha1dc
        --without-sha1dc
        --use-system-libraries
extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
        from extconf.rb:100:in `chdir'
        from extconf.rb:100:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.2.0/gems/rugged-0.99.0 for inspection.
Results logged to /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/gem_make.out
```

The logfile `mkmf.log` shows that all required dependencies are already installed:

```sh
$ cat  /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/mkmf.log
find_executable: checking for gmake... -------------------- yes

--------------------

find_executable: checking for cmake... -------------------- yes

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------
```

**Comment by robertcheramy** [comment]
This is an issue in oxidized-script. Open an Issue there.
