### ISSUE TITLE
Type error when pulling config from Cisco switch: "wrong argument type nil (expected String) (TypeError)"

### ISSUE THREAD

**Issue by packetuser** [ytti/oxidized#3278]
First of all, thanks to the maintainers for a great project!

I'm running Oxidized 0.30.1 on Ubuntu. I'm attempting to pull the config from a Cisco 9500 (full model is C9500-48Y4C, running IOS XE 17.09.04a). I have successfully set up Oxidized for dozens of Cisco 9200 switches, but this one is problematic.

Here's my config:

```
username: oxidized
password: password
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: true
run_once: false
threads: 30
use_max_threads: false
timeout: 30
retries: 0
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  #file:
  #  directory: "/home/oxidized/.config/oxidized/configs"
  git:
    user: username
    email: username@server.com
    repo: "/home/oxidized/repo/devices.git"

source:
  default: csv
  csv:
    file: "~/.config/oxidized/devices.db"
    delimiter: !ruby/regexp /:/
    map:
      ip: 0
      model: 1
      username: 2
      password: 3


model_map:
  juniper: junos
  cisco: ios

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: https://gitlab-server.foo/oxidized-test.git
    username: username
    password: very-long-password

```

Here's the device database file:
`1.1.1.1:ios:oxidized:password`

This is what I get when I run oxidized:

```
I, [2024-09-25T12:18:05.892453 #1549097]  INFO -- : Oxidized starting, running as pid 1549097
D, [2024-09-25T12:18:05.893464 #1549097] DEBUG -- : Hook "push_to_remote" registered GithubRepo for event :post_store
I, [2024-09-25T12:18:05.894152 #1549097]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2024-09-25T12:18:05.894349 #1549097] DEBUG -- : resolving DNS for ...
D, [2024-09-25T12:18:05.894435 #1549097] DEBUG -- : IPADDR 1.1.1.1
D, [2024-09-25T12:18:05.894571 #1549097] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ios'
D, [2024-09-25T12:18:05.894664 #1549097] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2024-09-25T12:18:05.894722 #1549097] DEBUG -- : node.rb: returning node key 'model' with value 'ios'
D, [2024-09-25T12:18:05.894768 #1549097] DEBUG -- : lib/oxidized/node.rb: Loading model "ios"
D, [2024-09-25T12:18:05.896495 #1549097] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2024-09-25T12:18:05.896587 #1549097] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2024-09-25T12:18:05.896638 #1549097] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2024-09-25T12:18:05.896703 #1549097] DEBUG -- : lib/oxidized/model/model.rb Added show vtp status to the commands list
D, [2024-09-25T12:18:05.896745 #1549097] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2024-09-25T12:18:05.897017 #1549097] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2024-09-25T12:18:05.897081 #1549097] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2024-09-25T12:18:05.968591 #1549097] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2024-09-25T12:18:05.968839 #1549097] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2024-09-25T12:18:05.987859 #1549097] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value 'oxidized'
D, [2024-09-25T12:18:05.988049 #1549097] DEBUG -- : node.rb: setting node key 'username' to value 'oxidized' from global
D, [2024-09-25T12:18:05.988127 #1549097] DEBUG -- : node.rb: returning node key 'username' with value 'oxidized'
D, [2024-09-25T12:18:05.988187 #1549097] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value 'password'
D, [2024-09-25T12:18:05.988246 #1549097] DEBUG -- : node.rb: setting node key 'password' to value 'default-password' from global
D, [2024-09-25T12:18:05.988307 #1549097] DEBUG -- : node.rb: returning node key 'password' with value 'password'
I, [2024-09-25T12:18:05.988433 #1549097]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2024-09-25T12:18:06.205660 #1549097] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2024-09-25T12:18:06.205860 #1549097] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2024-09-25T12:18:06.206010 #1549097] DEBUG -- : lib/oxidized/worker.rb: Added / to the job queue
D, [2024-09-25T12:18:06.206099 #1549097] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2024-09-25T12:18:06.206818 #1549097] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for  at 2024-09-25 16:18:06 UTC
D, [2024-09-25T12:18:06.207007 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to
D, [2024-09-25T12:18:06.207160 #1549097] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
Puma starting in single mode...
* Version 3.11.4 (ruby 3.0.2-p107), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
D, [2024-09-25T12:18:06.501918 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at
D, [2024-09-25T12:18:07.206278 #1549097] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2024-09-25T12:18:07.305520 #1549097] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at
D, [2024-09-25T12:18:07.305627 #1549097] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x000055c45b99a6b8 /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/model/ios.rb:132> at
D, [2024-09-25T12:18:07.305695 #1549097] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal length 0", block: nil at
D, [2024-09-25T12:18:07.305713 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb terminal length 0 @  with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2024-09-25T12:18:07.305935 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at
D, [2024-09-25T12:18:07.708405 #1549097] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal width 0", block: nil at
D, [2024-09-25T12:18:07.708489 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb terminal width 0 @  with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2024-09-25T12:18:07.708792 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at
D, [2024-09-25T12:18:08.111131 #1549097] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2024-09-25T12:18:08.111219 #1549097] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2024-09-25T12:18:08.111238 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb show version @  with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2024-09-25T12:18:08.111562 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at
D, [2024-09-25T12:18:08.207561 #1549097] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2024-09-25T12:18:08.514100 #1549097] DEBUG -- : lib/oxidized/model/model.rb Executing show vtp status
D, [2024-09-25T12:18:08.514169 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb show vtp status @  with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2024-09-25T12:18:08.514398 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at
D, [2024-09-25T12:18:08.919610 #1549097] DEBUG -- : lib/oxidized/model/model.rb Executing show inventory
D, [2024-09-25T12:18:08.920384 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb show inventory @  with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2024-09-25T12:18:08.920709 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at
D, [2024-09-25T12:18:09.208839 #1549097] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2024-09-25T12:18:09.324242 #1549097] DEBUG -- : lib/oxidized/model/model.rb Executing show running-config
D, [2024-09-25T12:18:09.324456 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb show running-config @  with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2024-09-25T12:18:09.324714 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at
D, [2024-09-25T12:18:09.727568 #1549097] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at
D, [2024-09-25T12:18:09.727636 #1549097] DEBUG -- : lib/oxidized/input/ssh.rb exit @  with expect: nil
D, [2024-09-25T12:18:09.832204 #1549097] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for  successfully
D, [2024-09-25T12:18:09.832442 #1549097] DEBUG -- : lib/oxidized/job.rb: Config fetched for  at 2024-09-25 16:18:09 UTC
F, [2024-09-25T12:18:10.211520 #1549097] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
wrong argument type nil (expected String)
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/output/git.rb:181:in `add': wrong argument type nil (expected String) (TypeError)
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/output/git.rb:181:in `update_repo'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/output/git.rb:164:in `update'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/output/git.rb:60:in `store'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/worker.rb:72:in `process_success'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/worker.rb:50:in `process'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/worker.rb:16:in `block in work'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/worker.rb:16:in `each'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/worker.rb:16:in `work'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:53:in `block in run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:51:in `loop'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:51:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:37:in `initialize'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/cli.rb:13:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.30.1/bin/oxidized:5:in `<top (required)>'
        from /usr/local/bin/oxidized:25:in `load'
        from /usr/local/bin/oxidized:25:in `<main>'
```

**Comment by robertcheramy** [comment]
It looks like ether file or oid is not set, which should not be, in git.rb:181
https://github.com/ytti/oxidized/blob/4330f449dca5c40561108fbf182b5624db942070/lib/oxidized/output/git.rb#L181

Is/was your disk full or have you made any manual changes to the git repository in `/home/oxidized/repo/devices.git` ?
Could you try again after having removed /home/oxidized/repo/devices.git (make a backup fist or you will loose your history! Restore the backup after the test to restore your history) ?

**Comment by packetuser** [comment]
I deleted /home/oxidized/repo/devices.git directory entirely and the issue persists as before.

I have verified that my problem was not device related; I tried with another device and I'm having the same issue.

**Comment by packetuser** [comment]
Another interesting thing to note - I tried outputting to a file, and I get a similar error:

```
--------------------------------------------------
2024-09-26 14:42:55 UTC
no output git config, edit ~/.config/oxidized/config [Oxidized::NoConfig]
--------------------------------------------------
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/output/git.rb:25:in `setup'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/manager.rb:18:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/manager.rb:61:in `loader'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/manager.rb:40:in `add_output'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/node.rb:170:in `resolve_output'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/node.rb:25:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:22:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:22:in `block (2 levels) in load'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:17:in `each'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:17:in `block in load'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:133:in `synchronize'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:133:in `with_lock'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:11:in `load'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/nodes.rb:128:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/3.0.0/gems/oxidized-0.30.1/bin/oxidized:5:in `<top (required)>'
/usr/local/bin/oxidized:25:in `load'
/usr/local/bin/oxidized:25:in `<main>'
--------------------------------------------------
```

**Comment by packetuser** [comment]
Ok this is strange - I did a test by switching output to file (which worked), then back to git, and the problem disappeared. I can't explain it!

**Comment by robertcheramy** [comment]
Thanks for the hint, I can reproduce the issue.
