### ISSUE TITLE
oxidized-script fails to install on ubuntu 24.04 (ruby 3.2)

### ISSUE THREAD

**Issue by anubisg1** [ytti/oxidized#3288]
as per title

```
root@OXIDIZED:/home/azureuser# gem install oxidized-script
Building native extensions. This could take a while...
ERROR:  Error installing oxidized-script:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.2.0/gems/rugged-0.99.0/ext/rugged
/usr/bin/ruby3.2 -I/usr/lib/ruby/vendor_ruby extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)3.2
        --with-sha1dc
        --without-sha1dc
        --use-system-libraries
extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
        from extconf.rb:100:in `chdir'
        from extconf.rb:100:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.2.0/gems/rugged-0.99.0 for inspection.
Results logged to /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/gem_make.out
```

**Comment by robertcheramy** [comment]
This is an oxidized-script issue. Please open an issue there.
