### ISSUE TITLE
Non existent output directory should have friendly error message

### ISSUE THREAD

**Issue by dorkmatt** [ytti/oxidized#374]
In the case of non existent directory specified for output, suggest a friendly error message like "mkdir -p that directory, silly!".
```
matt@monitor:~$ oxidized
I, [2016-03-30T22:52:02.093164 #15964]  INFO -- : Oxidized starting, running as pid 15964
resolving DNS for 100.64.0.2...
F, [2016-03-30T22:52:02.325780 #15964] FATAL -- : Oxidized crashed, crashfile written in /home/matt/.config/oxidized/crash
no output file config, edit ~/.config/oxidized/config
/var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/output/file.rb:15:in `setup': no output file config, edit ~/.config/oxidized/config (Oxidized::NoConfig)
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/manager.rb:19:in `load'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/manager.rb:40:in `add_output'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/node.rb:160:in `resolve_output'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/node.rb:20:in `initialize'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:18:in `new'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:18:in `block (2 levels) in load'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:14:in `each'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:14:in `block in load'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:110:in `synchronize'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:110:in `with_lock'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/nodes.rb:105:in `initialize'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.0.0/gems/oxidized-0.13.1/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

**Comment by ytti** [comment]
if you have 'debug: true' on main level, it causes oxidized to raise backtrace. 

Without 'debug: true' it should have just output:
'no output file config, edit ~/.config/oxidized/config' nothing else (while also creating example output configuration section in config)

**Comment by dorkmatt** [comment]
Got it, when using debug: false a useful message appears.
