### ISSUE TITLE
Since upgrade to 0.14.1, unable to view old config versions

### ISSUE THREAD

**Issue by thecityofguanyu** [ytti/oxidized#423]
As the title indicates, since the upgrade to 0.14.1, viewing old versions of configs appears to no longer work. Another user in the IRC channel confirmed having the same issue since upgrading. The following error is displayed:

![error](http://i.imgur.com/hyjKG2M.png)

For reference, the URL is attempts to use is:

```
http://oxidized/node/version/view?node=r7606&group=&oid=bd85a81b76d5e8507962727596acc2f03c185e9f&date=2016-05-03%2012:24:54%20-+0500&num=15
```

Diff functionality between versions still appears to work just fine. A diff URL:

```
http://oxidized/node/version/diffs?node=r7606&group=&oid=9cd9231954a1935b0c7f5d2f3fffdafc822d9002&date=2016-05-13%2004:32:17%20-+0500&num=16
```

Gem versions:

```
gem list | grep ox
oxidized (0.14.1, 0.12.2, 0.9.0)
oxidized-script (0.1.2, 0.1.1)
oxidized-web (0.7.0, 0.5.2)
```

**Comment by rush131** [comment]
Hi, just did a fresh install today, and I have the same problem. Here is my config:

```
username: username
password: password
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8080
vars: {}
groups: {}
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  file:
    directory: "/etc/oxidized/configs"
  git:
    single_repo: true
    user: Oxidizied
    email: oxidized@bla.com
    repo: "/etc/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/etc/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos
  mikrotik: routeros
```

**Comment by ytti** [comment]
This is probably because #413  was fixed, just don't know yet why it broke for some people.

**Comment by ytti** [comment]
Could someone remove line 113 and 114 https://github.com/ytti/oxidized/blob/fa03cc5b59015418064c2e4c707fe4ec2491aecf/lib/oxidized/output/git.rb#L113

We should then get traceback messages which might be bit more helpful

**Comment by rush131** [comment]
Requested trace:

![trace](https://cloud.githubusercontent.com/assets/11402967/15392868/233342ec-1dca-11e6-97da-1417a42b54be.png)

**Comment by ytti** [comment]
@rush131 do you have crash log in ~/.config/oxidized that is not actually the traceback i'm looking for

**Comment by rush131** [comment]
Nope, no crash log is generated. All I get is this when running in debug mode:

```
2016-05-19 14:14:29 - NoMethodError - undefined method `content' for nil:NilClass:
        /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.14.1/lib/oxidized/output/git.rb:112:in `get_version'
        /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:169:in `block in get_version'
        /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:110:in `synchronize'
        /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:110:in `with_lock'
        /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:165:in `get_version'
        /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-web-0.7.0/lib/oxidized/web/webapp.rb:176:in `block in <class:WebApp>'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
        /usr/local/rvm/gems/ruby-2.1.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
        /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
        /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
        /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
        /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by ytti** [comment]
That is helpful. ```repo.blob_at(oid,node).content``` 

In this line, ```repo.blob_at(oid, node)``` returns nil, to which we call ```#content``` which is invalid. So either oid or node are wrong. 

Could you, above that line, add:
```
p oid
p node
```

And tell me what it printed, and how it matches your git repo.

Thanks for your trouble so far.

**Comment by rush131** [comment]
So the debug now prints:
```
"3db334bab54a2dbc6986c3b1cddee3e1e8c479a6"
"/10.2.60.99"
```
And my GIT repo shows:
```
commit	3db334bab54a2dbc6986c3b1cddee3e1e8c479a6
tree	1c0bb13205870884d0749be70e4d22a653e3a577	
parent	4b3f8af2d9e68252da7bea661163b3c4c5e74207
```

The "commit" field matches oid, but I'm not sure if the "/" in node name could be the problem.

**Comment by ytti** [comment]
But the file definitely is in the root of your repo?

**Comment by rush131** [comment]
Yes it is.

**Comment by ytti** [comment]
Could you do ```gem install pry``` and add in the top of the file ```require 'pry'```

Then before line  ```repo.blob_at(oid,node).content``` add line ```binding.pry```

Now when you run oxidized, it should stop executing and should throw you in the pry shell. Here you can try to give some other arguments as 'oid' and 'node'. Also you can verify if 'repo' is actually the repo we're interested in. 

Right now my guess is, we're setting 'repo' incorrectly.

**Comment by rush131** [comment]
Node name is the problem. Node name is set to "/10.2.60.99", probably due to group joining. When I set the node name to "10.2.60.99" using pry, I get the correct config printout on the web.

```
[1] pry(#<Oxidized::Git>)> p node
"/10.2.60.99"
=> "/10.2.60.99"
[2] pry(#<Oxidized::Git>)> node="10.2.60.99"
=> "10.2.60.99"
```

Please note, I have ```single_repo: true``` in the config, but I am currently not using any groups. Could this have any impact?

**Comment by thecityofguanyu** [comment]
>Please note, I have single_repo: true in the config, but I am currently not using any groups. Could this have any impact?

I do not have <code>single_repo: true</code> explicitly set in the config, but I am only using one repo and also do not use any groups.

**Comment by rush131** [comment]
OK did  some further testing. Before line ``` 112:           node = File.join group, node``` the node name is "10.2.60.99", and after this line, the node name is "/10.2.60.99". So how to fix this without breaking groups?

**Comment by ytti** [comment]
Can you change the line to ```node = File.join group, node unless group.empty?``` and report back?

**Comment by thecityofguanyu** [comment]
>Can you change the line to node = File.join group, node unless group.empty? and report back?

I can confirm that this change resolved the issue for me.

**Comment by ytti** [comment]
I'll release 0.14.2 shortly, thanks everyone for your help.
