### ISSUE TITLE
Crash when no Repo is defined in oxidized-0.16.1

### ISSUE THREAD

**Issue by TestingBytes** [ytti/oxidized#512]
I upgraded to oxidized-0.16.1 from oxidized-0.15 and I now get a crash on line 184 of nodes.rb:
```
--------------------------------------------------
2016-07-27 18:06:21 UTC
undefined method `[]' for nil:NilClass [NoMethodError]
--------------------------------------------------
/var/lib/gems/2.1.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:43:in `method_missing'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/node.rb:184:in `resolve_repo'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/node.rb:26:in `initialize'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:19:in `new'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:15:in `each'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:126:in `synchronize'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:126:in `with_lock'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/nodes.rb:121:in `initialize'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.1.0/gems/oxidized-0.16.1/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

I don't have a repo defined in my config - the crash seems to be related to this change (it goes away when I revert this change):

dd6f5df411a3ba0e9158d6c1fc5293aa53c47a29

**Comment by k1br0k** [comment]
I was actually signing up to ask this very question (n00b here) when I noticed this had just been posted.  I've been beating my head against the wall for the last couple days trying to figure this out.  This was my first install of Oxidized and I originally grabbed the latest rev.  As soon as I removed 0.16 and installed 0.15, everything started working just fine.

**Comment by ytti** [comment]
I'm sure @danilopopeye will get it sorted in no time. I'll release 0.16.2 when possible.

**Comment by danilopopeye** [comment]
> I don't have a repo defined in my config

could you post you config?

**Comment by TestingBytes** [comment]
```
---
username: XXX
password: XXX
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.1.101:12345
vars: {enable: XXX}
groups: {}
pid: "/root/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
model_map:
  cisco: ios
  juniper: junos
```

**Comment by danilopopeye** [comment]
> I'm sure @danilopopeye will get it sorted in no time

done! my bad, this issue was on me :confounded:

**Comment by k1br0k** [comment]
Yes!  You guys are awesome.  Thanks.

**Comment by ytti** [comment]
many thanks @danilopopeye 

Nah most of the blame is on me, for not having oxidized tested. But there won't be release 1 until that is done, so may never :)
