### ISSUE TITLE
Issues with backing up config on Cisco ASA

### ISSUE THREAD

**Issue by laf** [ytti/oxidized#574]
Hi Folks,

Current versions:
`oxidized-script-0.3.1`
`oxidized-web-0.7.1`
`oxidized-0.16.3`

We backup config for a large number of Cisco ASA's which works fine for 99% of them. However a few we are having issues with. Trying to use oxs to debug this I get the following:

``` bash
[oxidized@localhost ~]# oxs somehost.com 'show ver' -v -d
execution expired
/usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/ruby_compat.rb:25:in `select': execution expired (Timeout::Error)
        from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/ruby_compat.rb:25:in `io_select'
        from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:210:in `process'
        from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
        from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from /usr/local/share/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
        from /usr/local/share/gems/gems/oxidized-0.16.3/lib/oxidized/input/ssh.rb:129:in `block in expect'
        from /usr/local/share/gems/gems/oxidized-0.16.3/lib/oxidized/input/ssh.rb:128:in `expect'
        from /usr/local/share/gems/gems/oxidized-0.16.3/lib/oxidized/input/ssh.rb:122:in `cmd_shell'
        from /usr/local/share/gems/gems/oxidized-0.16.3/lib/oxidized/input/ssh.rb:62:in `cmd'
        from /usr/local/share/gems/gems/oxidized-0.16.3/lib/oxidized/model/model.rb:84:in `cmd'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/script.rb:23:in `cmd'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/cli.rb:39:in `run'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/bin/oxs:5:in `<top (required)>'
        from /usr/local/bin/oxs:23:in `load'
        from /usr/local/bin/oxs:23:in `<main>'

```

Even if I set the timeout to 120 seconds it doesn't work - however I do get a different response of unable to connect.

``` bash
[oxidized@localhost ~]# oxs -t 120  somehost.com 'show ver' -v -d
unable to connect
/usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/script.rb:111:in `connect': unable to connect (Oxidized::Script::NoConnection)
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/script.rb:90:in `initialize'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/cli.rb:118:in `new'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/cli.rb:118:in `connect'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/cli.rb:35:in `run'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/bin/oxs:5:in `<top (required)>'
        from /usr/local/bin/oxs:23:in `load'
        from /usr/local/bin/oxs:23:in `<main>'
```

What's the best way to debug this further?

**Comment by laf** [comment]
I should also mention, we're using a custom asa.rb model but I have removed this and not seen a difference :(

**Comment by ytti** [comment]
I'd first turn on input debug, to get session log. Then if needed even tshark/tcpdump capture, to see just how far it goes.

With debug turned on, logs should show what it was expecting before it timed out:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ssh.rb#L58

**Comment by laf** [comment]
Do you need to turn input debug on even with using oxs to test?

**Comment by ytti** [comment]
uhh, hmm right, can't hurt, but probably not much good. But turning on debugging itself should show which line it is expecting, that likely will help.

**Comment by laf** [comment]
Ok, set now.

This is the output I get. First block is without `-t 120` (reported as execution expired (Timeout::Error)) and the second is with (reported as unable to connect (Oxidized::Script::NoConnection)).

```bash
I, [2016-09-28T08:40:54.602001 #10039]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2016-09-28T08:41:00.660891 #10039] DEBUG -- : resolving DNS for fw.domain.com...
D, [2016-09-28T08:41:00.779070 #10039] DEBUG -- : lib/oxidized/node.rb: Loading model "asa"
D, [2016-09-28T08:41:00.800002 #10039] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2016-09-28T08:41:00.800204 #10039] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2016-09-28T08:41:00.800268 #10039] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2016-09-28T08:41:00.800345 #10039] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2016-09-28T08:41:00.800424 #10039] DEBUG -- : lib/oxidized/model/model.rb Added more system:running-config to the commands list
I, [2016-09-28T08:41:00.914498 #10039]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2016-09-28T08:41:00.915230 #10039] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to fw.domain.com
D, [2016-09-28T08:41:01.652746 #10039] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^\r*([\w.@()-\/]+[#>]\s?)$/ at fw.domain.com
D, [2016-09-28T08:41:02.457237 #10039] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at fw.domain.com
D, [2016-09-28T08:41:02.457486 #10039] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0000000284d328@/usr/local/share/gems/gems/oxidized-0.16.3/lib/oxidized/model/asa.rb:56> at fw.domain.com
D, [2016-09-28T08:41:02.457639 #10039] DEBUG -- : lib/oxidized/input/ssh.rb ENABLE @ fw.domain.com with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-09-28T08:41:02.457825 #10039] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^\r*([\w.@()-\/]+[#>]\s?)$/ at fw.domain.com
D, [2016-09-28T08:41:02.868896 #10039] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal pager 0", block: nil at fw.domain.com
D, [2016-09-28T08:41:02.868984 #10039] DEBUG -- : lib/oxidized/input/ssh.rb terminal pager 0 @ fw.domain.com with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-09-28T08:41:02.869138 #10039] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^\r*([\w.@()-\/]+[#>]\s?)$/ at fw.domain.com
D, [2016-09-28T08:41:03.279680 #10039] DEBUG -- : lib/oxidized/model/model.rb Executing more system:running-config
D, [2016-09-28T08:41:03.279817 #10039] DEBUG -- : lib/oxidized/input/ssh.rb more system:running-config @ fw.domain.com with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-09-28T08:41:03.280008 #10039] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^\r*([\w.@()-\/]+[#>]\s?)$/ at fw.domain.com





I, [2016-09-28T08:42:00.580116 #10416]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2016-09-28T08:42:05.472257 #10416] DEBUG -- : resolving DNS for fw.domain.com...
D, [2016-09-28T08:42:05.590661 #10416] DEBUG -- : lib/oxidized/node.rb: Loading model "asa"
D, [2016-09-28T08:42:05.592991 #10416] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2016-09-28T08:42:05.593117 #10416] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2016-09-28T08:42:05.593208 #10416] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2016-09-28T08:42:05.593288 #10416] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2016-09-28T08:42:05.593377 #10416] DEBUG -- : lib/oxidized/model/model.rb Added more system:running-config to the commands list
I, [2016-09-28T08:42:05.724681 #10416]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2016-09-28T08:42:05.725437 #10416] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to fw.domain.com

```

**Comment by ytti** [comment]
So it looks like in the first instance it actually connects, can enable, can set pager, starts running running-config, but never sees prompt after running-config.
Now for this instance, we'd really need to see the output, what is 'more system:running-config' outputting, as it's not seeing prompt? Is there prompt really? Is matching the regexp? Are there some non-printable characters?


In the second instance, it does not seem to even connect.

**Comment by laf** [comment]
I can send you the full output privately if that's ok?

The end of the command we get back to a prompt:

```bash
!
service-policy global_policy global
prompt hostname context
no call-home reporting anonymous
Cryptochecksum:3eb0b840256c1cd202a30c11eaedad3c
: end

dc-fw1-a#
```

I don't see any non-printable chars in the output. The config is pretty similar to the others with the exception that it's got a lot of config entries on this fw.

The second instance is weird, it's the same oxs command but the difference is I tagged -t 120 on to increase the default timeout value.

**Comment by ytti** [comment]
Yeah the second one sounds odd, probably separate/distinct bug. For some reason it does not seem to accept that prompt.

Did you view the file with some command which displays non-printable chars? Maybe there is like \r on the beginning of the line or some such?

**Comment by laf** [comment]
Straight from the cli via SSH is how I've just double checked the config itself.

**Comment by ytti** [comment]
Yeah but cli via SSH will interpret non-printables and may not expose that there are crap in the beginning. Like you wouldn't see \r in the beginning of the prompt if ti were there.

We'd need log file and view log file with something like 'vim' to truly see what was offered.

**Comment by laf** [comment]
Sorry I thought you mean the config output. The log files was via tail -f, just checked with vim and in the logs I've posted already no special chars can be seen :(

**Comment by laf** [comment]
I'll come back to this when I've got more time to debug.

**Comment by InsaneSplash** [comment]
I find that if I include a timeout value, no matter the number, I receive an unable to connect error.

```
oxs -g ens001 -o routeros --timeout 100 '/system routerboard print' 
We had the following error on node 01:
unable to connect
```

**Comment by laf** [comment]
Yeah I see the same as well

**Comment by InsaneSplash** [comment]
Glad Im not the only one :) I have 1000 nodes to update, but would prefer to reduce the timeout if the node is not available.
