### ISSUE TITLE
Backup fails after updating to 0.17

### ISSUE THREAD

**Issue by roedie** [ytti/oxidized#583]
Today I've updated oxidized to version 0.17 and somehow my smartedges will not backup anymore. Debug output gives:
```
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
D, [2016-10-10T21:03:50.918496 #23621] DEBUG -- : x.x.x.x raised Net::SSH::Disconnect with msg "connection closed by remote host"
D, [2016-10-10T21:03:50.918652 #23621] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for se100
D, [2016-10-10T21:03:50.918790 #23621] DEBUG -- : lib/oxidized/job.rb: Config fetched for se100 at 2016-10-10 19:03:50 UTC
W, [2016-10-10T21:03:51.903758 #23621]  WARN -- : se100 status no_connection, retry attempt 1
```

My routerdb looks like:
```
#0   :1    :2    :3    :4       :5       :6     :7    :8             :9
#name:model:group:input:username:password:enable:proxy:ssh_encryption:ssh_kext
se100:ipos:somegroup:ssh::::::
```
I'm a bit lost why this is happening. Especially with the ssh error right in the beginning.  Any pointers or ideas?

Sander

**Comment by ytti** [comment]
I'm traveling until 21st or so, currently on somewhere over greenland with terrible Internet.

Could this be caused by e638e7c9685d375afbfba2 - can you change the 'empty' :::  to :nil:nil:

**Comment by roedie** [comment]
Yes that works. But it is confusing to be honest.

I though it would be a wise idea to put nil in all unused parts of my config to make it readable. But then stuff breaks as well. So, some fields need nil and some don't. See:
```
D, [2016-10-11T09:06:23.238354 #31388] DEBUG -- : resolving DNS for somehost...
D, [2016-10-11T09:06:23.239934 #31388] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value 'nil'
D, [2016-10-11T09:06:23.240249 #31388] DEBUG -- : node.rb: returning node key 'input' with value 'nil'
F, [2016-10-11T09:06:23.255732 #31388] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
nil not found for node x.x.x.x
/var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/node.rb:142:in `block in resolve_input': nil not found for node x.x.x.x (Oxidized::MethodNotFound)
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/node.rb:140:in `map'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/node.rb:140:in `resolve_input'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/node.rb:17:in `initialize'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:19:in `new'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:15:in `each'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:126:in `synchronize'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:126:in `with_lock'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/nodes.rb:121:in `initialize'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.1.0/gems/oxidized-0.17.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```
While I do understand this field wants 'ssh' or 'telnet' it would be great if it would just do the defaults when it has nil in it. Since using :: in that part works that way.

Also, just removing the ::::: from the end of the router definition works as well.

**Comment by ytti** [comment]
That looks weird, it looks like we're getting string 'nil', not type nil. 

If it were type nil, then it should return ssh, telnet: https://github.com/ytti/oxidized/blob/master/lib/oxidized/node.rb#L203

I can't immediately figure out, why it's string "nil" not nil, like it should.

This
https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/csv.rb#L35

should turn it into type nil, because of:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/source.rb#L13

Somehow it looks like that's not working, and string 'nil' gets returned.

**Comment by roedie** [comment]
Please understand that I'm not the best coder and Ruby is definitely not my cup of tea, but, if I look at the following:
```
@cfg.vars_map.each do |key, position|
        vars[key.to_sym] = node_var_interpolate data[position]
end
```
Doesn't that mean that it only sends vars of vars_map to node_var_interpolate and not the vars that are in map?

So, with the following config:
```
    map:
      name: 0
      model: 1
      group: 2
      input: 3
      username: 4
      password: 5
    vars_map:
      enable: 6
      ssh_proxy: 7
      ssh_encryption: 8
      ssh_kex: 9
      ssh_port: 10
```
the settings 0 to 5 will not be send to node_var_interpolate and will just be processed as strings. That would explain what I am seeing.

AFAIK only setting 0 is mandatory and all others might have default settings which are inherited from the config and may have 'nil' in the router.db.

**Comment by ytti** [comment]
Good catch, that's it!

**Comment by roedie** [comment]
Woah, you're fast ;-)

**Comment by ytti** [comment]
Lemme know if it works and I'll release 0.7.1

**Comment by roedie** [comment]
Yup, this fixes it.
