### ISSUE TITLE
CiscoSMB Model doesn't work on cisco SG series (still small business)

### ISSUE THREAD

**Issue by Atroskelis** [ytti/oxidized#610]
I have a couple of cisco SG-200 specifically, and the model doesn't match. Not even the prompt.

I've tried modifying the model file, and i've reached to the point where the oxs commands returns the output of most commands (like show clock) but i cannot manage to make it output the "show running-config" command, as it ends with 

Here is the diff of what i've done to the file (i wasn't sure i could make a new model file and use it)

```
[oxidized@oxidized model]$ diff ciscosmb.rb backupsmb 
6c6
<   prompt /\n?([\w.@()-]+[#>]\s?)/

---
>   prompt /^\r?([\w.@()-]+[#>]\s?)$/
37,38c37,38
<     username /Username:/
<     password /Password:/

---
>     username /^User Name:/
>     password /^\r?Password:$/
41a42
>     post_login 'terminal datadump' # Disable pager
[oxidized@oxidized model]$
```

here's the output using the oxs 

```
[oxidized@oxidized model]$ oxs -m ciscosmb -u cisco -p <pass> -v -d <redacted> 'show clock'         
D, [2016-11-08T12:40:25.614364 #8714] DEBUG -- : resolving DNS for <redacted>...
D, [2016-11-08T12:40:25.614839 #8714] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'telnet' and node value ''
D, [2016-11-08T12:40:25.614877 #8714] DEBUG -- : node.rb: returning node key 'input' with value 'telnet'
D, [2016-11-08T12:40:25.619064 #8714] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2016-11-08T12:40:25.619114 #8714] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2016-11-08T12:40:25.633508 #8714] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ciscosmb'
D, [2016-11-08T12:40:25.633572 #8714] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2016-11-08T12:40:25.633599 #8714] DEBUG -- : node.rb: returning node key 'model' with value 'ciscosmb'
D, [2016-11-08T12:40:25.633626 #8714] DEBUG -- : lib/oxidized/node.rb: Loading model "ciscosmb"
D, [2016-11-08T12:40:25.634408 #8714] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2016-11-08T12:40:25.634453 #8714] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2016-11-08T12:40:25.634476 #8714] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2016-11-08T12:40:25.634493 #8714] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2016-11-08T12:40:25.634728 #8714] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2016-11-08T12:40:25.634768 #8714] DEBUG -- : node.rb: setting node key 'username' to value 'username' from global
D, [2016-11-08T12:40:25.634792 #8714] DEBUG -- : node.rb: returning node key 'username' with value 'username'
D, [2016-11-08T12:40:25.634808 #8714] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2016-11-08T12:40:25.634826 #8714] DEBUG -- : node.rb: setting node key 'password' to value 'password' from global
D, [2016-11-08T12:40:25.634843 #8714] DEBUG -- : node.rb: returning node key 'password' with value 'password'
D, [2016-11-08T12:40:26.735439 #8714] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at <redacted>
D, [2016-11-08T12:40:26.735520 #8714] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal width 0", block: nil at <redacted>
D, [2016-11-08T12:40:26.735546 #8714] DEBUG -- : Telnet: terminal width 0 @<redacted>
D, [2016-11-08T12:40:26.778612 #8714] DEBUG -- : lib/oxidized/model/model.rb Executing show clock
D, [2016-11-08T12:40:26.778681 #8714] DEBUG -- : Telnet: show clock @<redacted>
## HOST - <redacted>
## OXS - show clock

12:44:37 DFL(UTC+8) Nov 08 2016 
No time source

[oxidized@oxidized model]$ oxs -m ciscosmb -u cisco -p <pass> -v -d <redacted> 'show run'  
D, [2016-11-08T12:40:30.285016 #8717] DEBUG -- : resolving DNS for <redacted>...
D, [2016-11-08T12:40:30.285504 #8717] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'telnet' and node value ''
D, [2016-11-08T12:40:30.285543 #8717] DEBUG -- : node.rb: returning node key 'input' with value 'telnet'
D, [2016-11-08T12:40:30.289605 #8717] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2016-11-08T12:40:30.289652 #8717] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2016-11-08T12:40:30.304237 #8717] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ciscosmb'
D, [2016-11-08T12:40:30.304306 #8717] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2016-11-08T12:40:30.304335 #8717] DEBUG -- : node.rb: returning node key 'model' with value 'ciscosmb'
D, [2016-11-08T12:40:30.304360 #8717] DEBUG -- : lib/oxidized/node.rb: Loading model "ciscosmb"
D, [2016-11-08T12:40:30.305120 #8717] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2016-11-08T12:40:30.305164 #8717] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2016-11-08T12:40:30.305187 #8717] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2016-11-08T12:40:30.305205 #8717] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2016-11-08T12:40:30.305552 #8717] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2016-11-08T12:40:30.305600 #8717] DEBUG -- : node.rb: setting node key 'username' to value 'username' from global
D, [2016-11-08T12:40:30.305625 #8717] DEBUG -- : node.rb: returning node key 'username' with value 'username'
D, [2016-11-08T12:40:30.305643 #8717] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2016-11-08T12:40:30.305661 #8717] DEBUG -- : node.rb: setting node key 'password' to value 'password' from global
D, [2016-11-08T12:40:30.305678 #8717] DEBUG -- : node.rb: returning node key 'password' with value 'password'
D, [2016-11-08T12:40:31.386393 #8717] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at <redacted>
D, [2016-11-08T12:40:31.386471 #8717] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal width 0", block: nil at <redacted>
D, [2016-11-08T12:40:31.386497 #8717] DEBUG -- : Telnet: terminal width 0 @<redacted>
D, [2016-11-08T12:40:31.429370 #8717] DEBUG -- : lib/oxidized/model/model.rb Executing show run
D, [2016-11-08T12:40:31.429416 #8717] DEBUG -- : Telnet: show run @<redacted>
timed out while waiting for more data
/usr/local/share/gems/gems/oxidized-0.18.0/lib/oxidized/input/telnet.rb:107:in `waitfor': timed out while waiting for more data (Timeout::Error)
        from /usr/local/share/gems/gems/net-telnet-0.1.1/lib/net/telnet.rb:696:in `cmd'
        from /usr/local/share/gems/gems/oxidized-0.18.0/lib/oxidized/input/telnet.rb:43:in `cmd'
        from /usr/local/share/gems/gems/oxidized-0.18.0/lib/oxidized/model/model.rb:84:in `cmd'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/script.rb:23:in `cmd'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/lib/oxidized/script/cli.rb:39:in `run'
        from /usr/local/share/gems/gems/oxidized-script-0.3.1/bin/oxs:5:in `<top (required)>'
        from /usr/local/bin/oxs:23:in `load'
        from /usr/local/bin/oxs:23:in `<main>'
```

I assume it's because of [this](https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/telnet.rb#L105) line. My suspicion is that after running a "Show run"  there's a sneaky control character after the config and that's somehow caught in the 'line' variable.

Does anyone have any suggestions regarding this ?  Using the model without any modifications wont run any commands. The ios module doesn't work as well.

Many thanks!

**Comment by ytti** [comment]
You can turn on debugging:
```
input:
  debug: true
```

You should get file of the actual session, viewing it with appropriate editor, you'll see if there are any  special unprintable chars. 

@SaaldjorMike any comment on the differences? Is this newer release of the same device?

Can we handle both in same model? Perhaps /(foo)|(bar)/ regexp for login/prompt?

**Comment by Atroskelis** [comment]
Hello, i have made some progress. 

Apparently the syntax 'terminal width 0' is not available on the SG series, it's now "term len 0 "

After fixing that i ran into another problem:

On telnet, the SG's require a double exit to disconnect.

The last logs entries **after getting the config** and running the pre_logout is this:


```
D18-5u#exit
D18-5u>
```

Basically i would need a way to make it do 'exit' twice.

**Comment by ytti** [comment]
You would just add another exit in the config.

**Comment by Atroskelis** [comment]
doing


```
  cfg :telnet, :ssh do
    post_login 'terminal len 0'
    pre_logout 'exit'
    pre_logout 'exit'
  end
```

Has no effect.

**Comment by SaaldjorMike** [comment]
@ytti I'll see if I can get around to testing it on my devices later this week (most likely thursday). Dont have any devices with telnet to test though.

**Comment by SaaldjorMike** [comment]
So I just updated my oxidized gems. So now I'm running:

```
oxidized (0.18.0)
oxidized-script (0.3.1)
oxidized-web (0.7.1)
```

I ended up doing two fixes to get it running for all my switches. One was to remove banners on the
switches with for some reason broke it. The other thing was to revert the
changes to line 36 which I commented on earlier:
[https://github.com/ytti/oxidized/commit/c39e8ebb2e19d718d039dc0c659d76b4469a750f](https://github.com/ytti/oxidized/commit/c39e8ebb2e19d718d039dc0c659d76b4469a750f#commitcomment-16105058)

**Comment by ytti** [comment]
Now SSH should work, even if we specify username/login prompt and SSH does not actually present them. Some models support device where some support SSH auth, some require CLI auth even on SSH.

**Comment by Atroskelis** [comment]
For my SG200's, the prompt is identical if you SSH or telnet, but i dont think i can configure the switches to NOT need 2 'exit' commands.

**Comment by ytti** [comment]
How it should work, today

a) even if we expect SSH prompt, if it's not presented, it should work. I.e. same model should work with SSH auth and SSH noath + CLI auth

b) having extra 'exit' commands should not break anything, even if we get disconnected before


If one of them is not true, then it's a bug.

**Comment by Atroskelis** [comment]
For the SG's i have, there's no difference between the prompt received using SSH or Telnet. 

Doing dual 'pre_logout 'exit'' in the 'cfg :telnet, :ssh do' does not seem to have any effect. By effect i mean only 1 'exit' is shown in the Telnet log.

```
oxidized: D, [2016-11-17T19:06:59.272644 #6064] DEBUG -- : resolving DNS for <redacted>-sw-d18.6u...
oxidized: D, [2016-11-17T19:08:18.112879 #6064] DEBUG -- : lib/oxidized/worker.rb: Added <redacted>-sw-d18.6u to the job queue
oxidized: D, [2016-11-17T19:08:18.114797 #6064] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for <redacted>-sw-d18.6u at 2016-11-17 17:08:18 UTC
oxidized: D, [2016-11-17T19:08:19.216284 #6064] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:19.216313 #6064] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal len 0", block: nil at <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:19.216330 #6064] DEBUG -- : Telnet: terminal len 0 @<redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:19.265378 #6064] DEBUG -- : Telnet: show version @<redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:19.492919 #6064] DEBUG -- : Telnet: show running-config @<redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:20.602375 #6064] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:20.602440 #6064] DEBUG -- : Telnet: exit @<redacted>-sw-d18.6u
oxidized: W, [2016-11-17T19:08:50.684393 #6064]  WARN -- : 172.16.31.77 raised Timeout::Error with msg "timed out while waiting for more data"
oxidized: D, [2016-11-17T19:08:50.684468 #6064] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:50.684513 #6064] DEBUG -- : lib/oxidized/job.rb: Config fetched for <redacted>-sw-d18.6u at 2016-11-17 17:08:50 UTC
oxidized: W, [2016-11-17T19:08:51.122253 #6064]  WARN -- : <redacted>-sw-d18.6u status no_connection, retry attempt 1
oxidized: D, [2016-11-17T19:08:51.122640 #6064] DEBUG -- : lib/oxidized/worker.rb: Added <redacted>-sw-d18.6u to the job queue
oxidized: D, [2016-11-17T19:08:51.123990 #6064] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for <redacted>-sw-d18.6u at 2016-11-17 17:08:51 UTC
oxidized: D, [2016-11-17T19:08:52.237431 #6064] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:52.237474 #6064] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal len 0", block: nil at <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:52.237510 #6064] DEBUG -- : Telnet: terminal len 0 @<redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:52.280393 #6064] DEBUG -- : Telnet: show version @<redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:52.505471 #6064] DEBUG -- : Telnet: show running-config @<redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:53.615785 #6064] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:08:53.615845 #6064] DEBUG -- : Telnet: exit @<redacted>-sw-d18.6u
oxidized: W, [2016-11-17T19:09:23.702337 #6064]  WARN -- : 172.16.31.77 raised Timeout::Error with msg "timed out while waiting for more data"
oxidized: D, [2016-11-17T19:09:23.702404 #6064] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for <redacted>-sw-d18.6u
oxidized: D, [2016-11-17T19:09:23.702457 #6064] DEBUG -- : lib/oxidized/job.rb: Config fetched for <redacted>-sw-d18.6u at 2016-11-17 17:09:23 UTC
oxidized: W, [2016-11-17T19:09:25.844835 #6064]  WARN -- : <redacted>-sw-d18.6u status no_connection, retries exhausted, giving up
```

**Comment by ytti** [comment]
Can you add here: https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ssh.rb#L86

```, Timeout::Error```and report back

**Comment by ytti** [comment]
It looks like you're not getting disconnected from the device. Is that with two exits? Since we're still running ssh loop, it means ssh is still connected. It really should not be connected anymore.

**Comment by Atroskelis** [comment]
Hello, i think i managed to fix the ssh method of connecting to these devices.

The magic combination is : 

Let me know if i can push this contribution. The tested device was a Cisco SG200. 

```
class CiscoSMB < Oxidized::Model

  # Cisco Small Business 200, 300, 500, and ESW2 series switches
  # http://www.cisco.com/c/en/us/support/switches/small-business-300-series-managed-switches/products-release-notes-list.html

  prompt /^\r?([\w.@()-]+[#>]\s?)$/
  comment  '! '

  cmd :all do |cfg|
    lines = cfg.each_line.to_a[1..-2]
    # Remove \r from beginning of response
    lines[0].gsub!(/^\r.*?/, '') if lines.length > 0
    lines.join
  end

  cmd :secret do |cfg|
    cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
    cfg.gsub! /username (\S+) privilege (\d+) (\S+).*/, '<secret hidden>'
    cfg
  end

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[0..-1].join
    cfg.gsub! /^Current configuration : [^\n]*\n/, ''
    cfg.sub! /^(ntp clock-period).*/, '! \1'
    cfg.gsub! /^\ tunnel\ mpls\ traffic-eng\ bandwidth[^\n]*\n*(
                  (?:\ [^\n]*\n*)*
                  tunnel\ mpls\ traffic-eng\ auto-bw)/mx, '\1'
    cfg
  end

  cfg :telnet, :ssh do
    username /Username:/
    password /Password:/
  end

  cfg :telnet, :ssh do
    post_login 'terminal len 0'
    pre_logout 'exit'
    pre_logout 'exit'
  end

end
```

**Comment by ytti** [comment]
Yup, this should work. You don't need two cfg blocks, you can put them under single block.

**Comment by lunacite** [comment]
My SG500s and SG300s both give:

"Username: not matching configured prompt (?-mix:^\r?([\w.@()-]+[#>]\s?)$)"
or
"User Name: not matching configured prompt (?-mix:^\r?([\w.@()-]+[#>]\s?)$)"
after I tried to fix that string.

**Comment by ytti** [comment]
Are you using SSH or Telnet? Do your SG300/SG500 use SSH auth or is SSH 'noauth' and presents CLI auth? If CLI auth what does it look like?

**Comment by lunacite** [comment]
ssh, CLI auth, the only thing that comes up is "User Name:"

**Comment by Atroskelis** [comment]
Do you have the config posted here? I have the suspicion that some devices ask for "User Name" and some for "Username", check if your ciscosmb.rb has the proper login scheme.

**Comment by ytti** [comment]
We can trivially make regexp to accept both. ```/User ?[nN]ame:/```

**Comment by lunacite** [comment]
I should probably add that I'm using the docker container, but I've pulled the latest commit by @Atroskelis and rebuilt the image & still isn't working. I manually changed the ciscosmb.rb to "User Name:" which matches my prompt and it still won't make it past.

**Comment by lunacite** [comment]
This was due to `ip ssh password-authentication` not being set

**Comment by ytti** [comment]
Does this mean this issue can be closed?

**Comment by lunacite** [comment]
Yes, it's working for me. The logic that detects CLI authentication is based on version number, not the fact that ip ssh password-authentication may not be set

**Comment by Atroskelis** [comment]
The original issue was solved, so from my point of view, it can be closed.

Many thanks for your support!

**Comment by azharkamal** [comment]
> For my SG200's, the prompt is identical if you SSH or telnet, but i dont think i can configure the switches to NOT need 2 'exit' commands.

hi do you have isue wtich SD200 beca
