### ISSUE TITLE
no implicit conversion of String into Integer [API calls] 

### ISSUE THREAD

**Issue by hbadreldin** [ytti/oxidized#645]
Here is my config: (All my indentations are OK)

> 
```
username: nms1
password: nms1
model: nos
interval: 3600
log: /home/oxidized/.config/oxidized/logs/oxidized.log
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
vars: {}
groups: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: /home/oxidized/.config/oxidized/configs
source:
  default: http
  debug: true
  http:
    url: http://localhost/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '01582bf94c03104ecb7953dsadsadwed'
```

Here the error message:

```
> [oxidized@linux06 ~]$ oxidized -d
no implicit conversion of String into Integer
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:43:in `[]': no implicit conversion of String into Integer (TypeError)
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:43:in `block (2 levels) in load'
        from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:42:in `block in load'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `each'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `load'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `synchronize'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `with_lock'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:121:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/share/gems/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```

Thanks,
Hosam

**Comment by hbadreldin** [comment]
I'm trying to call the LibreNMS API, but keep getting this error message.

**Comment by ytti** [comment]
ping @laf 

Code seems to assume JSON is Array of Objects (Hashes). And 
https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/http.rb#L38 ```line``` here is actually hash of node, so might be more aptly named ```node```. And ```position``` is they key name from the JSON node object.

But what is happening run time, it seems ```line``` is actually Array, not Object. And as we call array[string] it pukes.
So question is, why is it Array? Can we see the JSON you're getting?

```scheme``` and ```delimiter``` definitely don't do anything there, won't break anything, but won't help either.

**Comment by laf** [comment]
@ytti 

The output of the API call will be:

```
[
    {
        "hostname": "web-1",
        "os": "linux"
    },
    {
        "hostname": "poller-1",
        "os": "linux"
    }
]
```

**Comment by ytti** [comment]
I'd really love to see what @hbadreldin is actually getting, as it seems he is not getting JSON like that. @hbadreldin can you give like ```curl``` output or such?

**Comment by hbadreldin** [comment]
I did not get any other mirrors in the debug for LibreNMS. The above error message is all what I got. If you want me to try something specific I can.

**Comment by laf** [comment]
@hbadreldin to get the output from the api run:

`curl -H 'X-Auth-Token: YOUR_AUTH_TOKEN' https://YOUR_WEB_ADDRESS/api/v0/oxidized`

**Comment by hbadreldin** [comment]
Here you go:

Last login: Tue Dec 20 22:38:23 GMT 2016 on pts/0
[oxidized@vm06 ~]$ curl -H 'X-Auth-Token: 01582bf94c03104ecb7953dsadsadwed' http://localhost/api/v0/oxidized
{
    "status": "error",
    "message": "API Token is missing or invalid; please supply a valid token"
}
[oxidized@vm06 ~]$

**Comment by ytti** [comment]
I guess we found the problem.

**Comment by laf** [comment]
Yup, @hbadreldin carry this on in the post you created on community.librenms.org.

@ytti I'd say you can close this.
