### ISSUE TITLE
Ironware Encode ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by nmusser** [ytti/oxidized#680]
I've got a couple of Brocade XMR NetIron 16-slot Chassis' that are failing out of Oxidized with the following meesage:

`E, [2017-02-01T07:18:01.844266 #13376] ERROR -- : xx.xx.xx.xx raised Encoding::CompatibilityError with msg "incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)", /etc/oxidized/.config/oxidized/crash.xx.xx.xx.xx saved`

The crash file contains the following:

```
2017-02-01 13:18:57 UTC
"\xFF" from ASCII-8BIT to UTF-8 [Encoding::UndefinedConversionError]
--------------------------------------------------
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/model/ironware.rb:33:in `encode!'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/model/ironware.rb:33:in `block in <class:IronWare>'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/model/model.rb:94:in `instance_exec'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/model/model.rb:94:in `cmd'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/model/model.rb:136:in `block in get'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/model/model.rb:135:in `each'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/model/model.rb:135:in `get'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/input/cli.rb:14:in `get'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/node.rb:61:in `run_input'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/node.rb:38:in `block in run'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/node.rb:33:in `each'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/node.rb:33:in `run'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/job.rb:9:in `block in initialize'
```

The line of code that seems to be causing it to crash is this:
```

cmd 'show chassis' do |cfg|
    cfg.encode!("UTF-8", :invalid => :replace) #sometimes ironware returns broken encoding
```

And the ouput of show chassis that I believe it's crashing on is this:

```
telnet@redacted#show chassis
*** NetIron 16-slot Chassis ***

---POWERS ---
Power 1: ( 32006000���� 08288610471 - AC 1200W): Installed (OK)
Power 2: ( 32006000���� 08288610472 - AC 1200W): Installed (OK)
Power 3: ( 32006000���� 08288610476 - AC 1200W): Installed (OK)
Power 4: ( 32006000���� 08288610477 - AC 1200W): Installed (OK)
Power 5: (     32015000 AA450750041 - AC 1200W): Installed (OK)
Power 6: not present
Power 7: not present
Power 8: (     32015000 AA500750006 - AC 1200W): Installed (OK)
Total power budget for chassis = 7200 W
Total power used by system core = 762 W
Total power used by LPs = 1715 W
Total power available = 4723 W
Slot Power-On Priority and Power Usage:
[etc]
```

Those characters appear to be [0xfffd](http://www.unicodemap.org/details/0xFFFD/index.html). 

For the time being I'm just commenting out the _show chassis_ section to get it to work.

**Comment by ytti** [comment]
You probably want something like this:

```
cmd 'show chassis' do |cfg|
  cfg = cfg.b
  ...
```

This way it's treated as binary string, instead of UTF8 string.

**Comment by wendelj** [comment]
Looks like this should have been fixed by this PR 26 days ago:
https://github.com/ytti/oxidized/commit/853a1dd57776955c20377f6f13a5a71e892d89f0

**Comment by ytti** [comment]
@nmusser please reopen if not.

**Comment by nmusser** [comment]
That PR fixed the problem! Thanks!
