### ISSUE TITLE
 [2017-04-13T15:38:28.818177 #4304] FATAL -- : Oxidized crashed!!!

### ISSUE THREAD

**Issue by c0lored** [ytti/oxidized#809]
When I try to start Oxidized It crashes. 

### 

```
encadmin@CFP-LIBRE:~/.config/oxidized$ cat crash
--------------------------------------------------
2017-04-13 19:38:28 UTC
no implicit conversion of String into Integer [TypeError]
--------------------------------------------------
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:43:in `[]'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:43:in `block (2 levels) in load'
/var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:42:in `block in load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `synchronize'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `with_lock'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:121:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
```

--------------------------------------------------

----------------------------------------------------
YAML
------------------------------------------------------

```
---
username: ---
password: ---
model: cisco
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
vars: {}
groups: {}
pid: "/home/encadmin/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
   directory: /home/encadmin/.config/oxidized/configs
source:
  default: http
  debug: true
  http:
    url: http://cfp-libre/api/v0/oxidized
    map:
     name: hostname
     model: os
     group: group
  headers:
     X-Auth-Token: '01582bf94c03104ecb7953dsadsadwed'

model_map:
  cisco: ios
--------------------------------
Please help.
```

**Comment by davromaniak** [comment]
Hi.

I see several issues in your config file : 
- Line 23 : there's only 3 spaces before "directory:", YAML works with blocks of 2 spaces, in your case it should be 4 spaces.
- Lines 30, 31, 32 and 34 : there are 5 spaces instead of 6 in this case.
- Line 35 : I don't remember a blank line is allowed in YAML, so I think it should cause you some issues.

Thanks.

**Comment by ytti** [comment]
Also please fetch the source with ```curl``` to show what kind of data you're seeing. I suspect you're not getting the JSON at all with your request.
