### ISSUE TITLE
oxidized is crashing after upgrade to 0.20.0

### ISSUE THREAD

**Issue by paszczus** [ytti/oxidized#876]
Hello,
Oxidized is starting, i am able to see web page, few configs are received and then it is crashing:

```
--------------------------------------------------
2017-05-28 15:56:52 UTC
Address already in use - bind(2) for "172.16.21.22" port 8888 [Errno::EADDRINUSE]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/binder.rb:240:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/binder.rb:240:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/binder.rb:240:in `add_tcp_listener'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/binder.rb:99:in `block in parse'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/binder.rb:85:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/binder.rb:85:in `parse'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/runner.rb:129:in `load_and_bind'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/single.rb:84:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/puma/launcher.rb:172:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/puma-3.2.0/lib/rack/handler/puma.rb:51:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-web-0.9.1/lib/oxidized/web.rb:28:in `block in run'
```

Of course there was no another copy of oxidized running at the same time.

**Comment by rbeumer** [comment]
Are you sure there is nothing already listening on TCP port 8888?

> $ netstat --listening -t -n | grep 8888

**Comment by ytti** [comment]
Waiting for answer to question posted buy @rbeumer

**Comment by laf** [comment]
@paszczus Any update on this?

**Comment by laf** [comment]
@paszczus If you are still having issues then please reply and we can re-open this issue.
