### ISSUE TITLE
WebUI not working after Nginx config changes

### ISSUE THREAD

**Issue by tslytsly** [ytti/oxidized#915]
Hi,
The server that I run oxidized on is also our LibreNMS server.
I have just configured LNMS to use HTTPS, this involved changing the Nginx config to redirect port 80 to port 443.
As far as I can tell this should not have affected Oxidized.

But now it doesn't seem to start correctly.

The logs show that it is crashing, this is the "crash" file that is produced:
```
--------------------------------------------------
2017-07-04 19:31:07 UTC
execution expired [Net::OpenTimeout]
--------------------------------------------------
/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
/usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
/usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:36:in `loa$
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in `block in $
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchron$
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_loc$
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:122:in `initiali$
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `new'/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

Any help would be appreciated.

PS. this is my sanitised config (passwords replaced with #### server IP removed):
```
---
username: ########
password: #########
model: routeros
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
log: "/etc/oxidized/log/oxidized.log"
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: <server_IP>:8888
vars:
  enable: enable
groups: {}
pid: "/etc/oxidized/pid"
input:
  default: ssh, telnet
  debug: true
  debug: /etc/oxidized/log/oxidized_log_input
  ssh:
    secure: true
output:
  default: git
  git:
    user: ########
    email: ########
    repo: "/etc/oxidized/oxidized.git"
source:
  default: http
  debug: false
  http:
    url: https://#############/api/v0/oxidized
    scheme: https
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '########################'
groups:
  !!REDACTED!!
model_map:
  cisco: ios
  juniper: junos
  avaya-ers: ios
  avaya: ios

hooks:
   write_log_for_failed_nodes:
     type: exec
     events: [node_fail]
     cmd: 'echo "Doing long running stuff for $OX_NODE_NAME" >> /etc/oxidized/log/ox_node_fail.log; sleep 60'
     async: true
     timeout: 120
   write_log_for_store_operations_nodes:
     type: exec
     events: [post_store]
     cmd: 'echo "Config written for for $OX_NODE_NAME" >> /etc/oxidized/log/ox_node_store.log; sleep 60'
     async: true
     timeout: 120
```

**Comment by laf** [comment]
The change to nginx shouldn't have any effect on Oxidized here as you're starting it on a different port. Check you don't have another version of oxidized running on port 8888

**Comment by tslytsly** [comment]
Fixed it.
The problem was that I went from:
```
http:
    url: http://<ServerInternalIP>/api/v0/oxidized
```

to:
```
http:
    url: https://<ServerExternalDNS>/api/v0/oxidized
```

This was causing a hairpin NAT problem.

Set up a split DNS to provide the _internal ip_ when a local device does a DNS lookup and all is well again.
