### ISSUE TITLE
Error Loading Config

### ISSUE THREAD

**Issue by maladd3** [ytti/oxidized#953]
On a new installation, I'm getting an error loading config when I try to run oxidized.

[oxidized@Oxidized ~]$ oxidized 
Error loading config: (<unknown>): found character that cannot start any token while scanning for the next token at line 34 column 1
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/config.rb:52:in `rescue in load': Error loading config: (<unknown>): found character that cannot start any token while scanning for the next token at line 34 column 1 (Oxidized::InvalidConfig)
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/config.rb:49:in `load'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:24:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `new'
	from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'

Line 34 is username: 2

source:
  default: csv
  csv:
    map:
        username: 2
        password: 3
    vars_map:
        ssh_port: 4

    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  cisco: ios

**Comment by maladd3** [comment]
I figured it out with a fresh install.
