### ISSUE TITLE
Request to API for devices times out

### ISSUE THREAD

**Issue by rzig** [ytti/oxidized#959]
Hi. I recently tried to set up oxidized and have it get a list of devices from LibreNMS with the documentation [here](http://docs.librenms.org/Extensions/Oxidized/). When LibreNMS was accessible over HTTP, everything worked great, but after making it HTTPS only, now I'm getting the following error:

```
Connection timed out - connect(2)
/usr/share/ruby/net/http.rb:878:in `initialize': Connection timed out - connect(2) (Errno::ETIMEDOUT)
        from /usr/share/ruby/net/http.rb:878:in `open'
        from /usr/share/ruby/net/http.rb:878:in `block in connect'
        from /usr/share/ruby/timeout.rb:52:in `timeout'
        from /usr/share/ruby/net/http.rb:877:in `connect'
        from /usr/share/ruby/net/http.rb:862:in `do_start'
        from /usr/share/ruby/net/http.rb:851:in `start'
        from /usr/share/ruby/net/http.rb:1373:in `request'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:36:in `load'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in `block in load'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchronize'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_lock'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:10:in `load'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:122:in `initialize'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `new'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `initialize'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
        from /opt/librenms/.gem/ruby/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```
Here's my config:
```
username: user
password: password
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /opt/librenms/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/opt/librenms/.config/oxidized/configs"
source:
  default: http
  debug: false
  http:
    url: https://my-librenms-server.com:1776/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: super-secret
model_map:
  cisco: ios
  juniper: junos
```

I have verified that the endpoint can be reached with Postman. Nothing shows up in the LibreNMS access log when oxidized sends the request, but the log does show when I send a request in Postman. How should I go about fixing this?

**Comment by laf** [comment]
You are missing `scheme: https`: https://github.com/ytti/oxidized#source-http

**Comment by laf** [comment]
No further information has been provided so this issue is being closed.

If you have more information to provide then please do so and we will re-open this issue.
