### ISSUE TITLE
Cannot find hook

### ISSUE THREAD

**Issue by alexwbai** [ytti/oxidized#969]
I deeply apologize if this is dumb on my part (and may be likely so as I cannot find a similar reported issue here) but I am running into an issue where oxidized cannot find the awssns hook.  The default installation hook directories and files have remained unchanged since installation.  Other than this the application is working.

... excerpt from config file
model_map:
  cisco: iosbai
  westell: weos
hooks:
  hook_script:
    type: awssns
    events: [node_fail,node_success,post_store]
    region: us-east-1
    topic_arn: arn:aws:sns:us-east-1:643080791059:Alextest

The error I receive is:

_[oxidized@scriptor oxidized]$ oxidized
cannot find hook "awssns"
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/hook.rb:43:in `rescue in register': cannot find hook "awssns" (KeyError)
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/hook.rb:40:in `register'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/hook.rb:8:in `block (2 levels) in from_config'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/hook.rb:7:in `each'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/hook.rb:7:in `block in from_config'
	from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/hook.rb:6:in `from_config'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:13:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
	from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'_

Any thoughts?

**Comment by alexwbai** [comment]
Quick update.  If I comment the "require 'aws-sdk'" at the beginning of the awssns hook file I get past the above but then during debug I see it cannot initialize the AWSSNS constant
E, [2017-08-14T14:25:20.744420 #10791] ERROR -- : Hook hook_script (#<AwsSns:0x00000000f5fc58>) failed (#<NameError: uninitialized constant AwsSns::Aws>) for event :node_success

I have tried installing the aws-sdk for Ruby and also added it to the Gem File (but I continue to receive the initial error that the hook cannot be found.

**Comment by alexwbai** [comment]
I'm closing this.  For some reason that I cannot explain it is working now.  I logged in this morning and do not receive the error.
