### ISSUE TITLE
Undefined method 'dig'

### ISSUE THREAD

**Issue by CarbonJeepers** [ytti/oxidized#998]
When I run `oxidized -d` (version 0.20) on CentOS 7 I get the following:

```
I, [2017-08-28T14:59:40.423407 #17139]  INFO -- : Oxidized starting, running as pid 17139
I, [2017-08-28T14:59:40.490572 #17139]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2017-08-28T14:59:40.846621 #17139] FATAL -- : Oxidized crashed, crashfile written in /var/lib/oxidized/.config/oxidized/crash
undefined method `dig' for ["status", "error"]:Array
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load': undefined method `dig' for ["status", "error"]:Array (NoMethodError)
        from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /usr/local/share/gems/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:42:in `block in load'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:38:in `each'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:38:in `load'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in `block in load'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchronize'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_lock'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:10:in `load'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:122:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```
I've made sure I've met dependencies to the best of my abilities but I can't rule out a snafu on my part. Bug? User error? I'm not sure.

**Comment by laf** [comment]
This, I think, is because the http url you've provided isn't returning data correctly.

**Comment by laf** [comment]
No further information has been provided so this issue is being closed.

If you have anymore information, please reply and we can re-open this issue.
